### ISSUE TITLE
support dev-server hot load?

### ISSUE THREAD

**Issue by Dreampie** [webpack-contrib/copy-webpack-plugin#1]

**Comment by kevlened** [comment]
I haven't tested hot load with the plugin yet. It may work, because I add listeners for all the files you need. However, I don't know if hot load would reload the entire page if you updated the page itself.

If you find a way to support this, I'm open to investigate, or a PR would be even better!

**Comment by rauschma** [comment]
This is a relatively small project where you can test whether it works: https://github.com/rauschma/webpack-babel-demo

Currently it only works partially for me – changing the HTML file does not hot-reload the page, but if I reload the page manually, I do see the change. Alas, I have no idea how to fix this. Given how useful your plugin is, this may warrant asking webpack’s author.

**Comment by Dreampie** [comment]
webpack devServer  already on watch，why own watch？

**Comment by kevlened** [comment]
I was reading the [hot module replacement docs](https://webpack.github.io/docs/hot-module-replacement-with-webpack.html) and they say:

    webpack/hot/dev-server reloads the entire page after the HMR update fails

So one way for this plugin to reload the page is to include a module that will fail the build whenever a specified file(s) is changed

**Comment by rauschma** [comment]
There is more information here: https://github.com/webpack/webpack/issues/418#issuecomment-53878977

But this seems to be about files that are actually required somewhere. Thus, I’m not sure that copy-webpack-plugin applies. I’d file an issue and ask how to implement this best for your plugin (which provides an important service): https://github.com/webpack/webpack/issues

**Comment by kevlened** [comment]
webpack-dev-server is supported in v2.0.1

However, you still have to refresh the page manually if the HTML file changes
