### ISSUE TITLE
Use `indexOf` instead `_.includes`.

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/copy-webpack-plugin#100]
Why? It is faster and increases performance (if you have many files) :smile: 
/cc @kevlened

**Comment by mikesherov** [comment]
This is addressed by the use of `Set`, and can now be closed since https://github.com/webpack-contrib/copy-webpack-plugin/pull/130 landed.

**Comment by evilebottnawi** [comment]
@mikesherov :+1:
