### ISSUE TITLE
[Feature] Support manifest file

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/copy-webpack-plugin#104]
Why?
In some projects, I use external library (example `jquery`) and for the implamentation of this, I use this plugin (just copy files from another directory to other). The plugin supports the use of `hash`, but do not know original file path and resulting file path (include `hash` and other stuff). There is no manifest file :sob:

**Comment by SebastianS90** [comment]
Assuming you name your destination files `[name].[hash:10].[ext]`, try out this plugin:
```javascript
new StatsWriterPlugin({
    fields: ['assets'],
    filename: 'manifest.json',
    transform(stats) {
        const manifest = {};
        stats.assets.map(asset => asset.name)
            .sort()
            .forEach((file) => {
                manifest[file.replace(/\.[a-f0-9]{10}\./, '.')] = file;
                                               // 10 is length of hash
            });
        return JSON.stringify(manifest, null, 2) + '\n';
    }
})
```
Isn't that something you can work with?

**Comment by Levdbas** [comment]
The guys from webpack-manifest-plugin have included a hook in their latest RC release which other plugins can use to give before and after filenames and locations. Maybe this can be used to solve the hashing issue in a more convienient way? I am by no means capable of guessing if this can work but its merely a suggestion.

https://github.com/danethurber/webpack-manifest-plugin/pull/76

**Comment by IAMtheIAM** [comment]
Here's a slightly modified version that works with any length hash as long as it is inbetween two `.` characters

```js
   new StatsWriterPlugin({
      fields: ['assets'],
      filename: 'webpack-manifest.json',
      transform(stats) {
         const manifest = {};
         stats.assets.map(asset => asset.name)
            .sort()
            .forEach((file) => {
               manifest[file.replace(/\.([^.]*)/, '.')] = file; // matches anything between two dots `.` such as app.bundle.636876e2051c910a7ef8.js
            });
         return JSON.stringify(manifest, null, 2) + '\n';
      }
   }),
```

**Comment by deguif** [comment]
Hi,

For anyone wanting to use [danethurber/webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin) and be able to generate asset manifest which were copied with this plugin, here's my solution:

In webpack.config.js
```js
const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');
const ManifestPlugin = require('webpack-manifest-plugin');
...

module.exports = function (env) {
    return {
        ...
        output: {
            path: path.resolve(__dirname, 'web/dist'),
            publicPath: '/dist/',
        },
        plugins: [
            new CopyPlugin([
                {
                     context: path.join('/xxx/yyy', 'images'),
                     from: '**/*{.gif,.jpg,.jpeg,.png,.svg}',
                     to: 'images/[path][name].[ext]',
                     // to: 'production' === env.NODE_ENV ? 'images/[path][name].[hash].[ext]' : 'images/[path][name].[ext]',
                     toType: 'template',
                },
            ]),
            // Order matters, manifest plugin should be registered after copy plugin
            new ManifestPlugin({
                fileName: path.resolve(__dirname, 'var/assets/images/manifest.json'),
                publicPath: '/dist/',
                filter: (file) => file.name.startsWith('images/'),
                /*map: (file) => {
                    if ('production' === env.NODE_ENV) {
                        // Remove hash in manifest key
                        file.name = file.name.replace(/(\.[a-f0-9]{32})(\..*)$/, '$2');
                    }
                    return file;
                },*/
            }),
        ],
    };
}
```

__This will only work with version 2.x of [danethurber/webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin) currently in rc2__
See issue danethurber/webpack-manifest-plugin#75 and commit danethurber/webpack-manifest-plugin@4cb95ce41ec683078a6581949ec544f4a7d4a3d2

My example copy images from a `/xxx/yyy/images` to a `web/dist/images` folder and generate a manifest for images only in `var/assets/images/manifest.json` ([Symfony 3](https://symfony.com) project). For using hash when copying the assets you will need a little adaption on manifest plugin, you can use the `map`hook to remove hash from filename (See my commented code).

I hope this will help people from this thread.

**Comment by Levdbas** [comment]
I do thank you a lot for the  code that removes the hash from the file names. It works like a charm and simplifies my PHP function that includes the right asset a lot!

`map: (file) => {
                    if ('production' === env.NODE_ENV) {
                        // Remove hash in manifest key
                        file.name = file.name.replace(/(\.[a-f0-9]{32})(\..*)$/, '$2');
                    }
                    return file;
                },`

**Comment by airtonix** [comment]
Why are you guys removing the hash in production? the whole point of the hash is for production use.

Instead you should be creating a function in your backend that reads the manifest and resolves a logical url `/static/vendor/jquery.min.js` to the hashed url `static/vendor/jquery.min-34mj34jh3k4h5.js`.

**Comment by evilebottnawi** [comment]
@jasonwilliams Should be fix it https://github.com/danethurber/webpack-manifest-plugin/issues/141

**Comment by jasonwilliams** [comment]
@evilebottnawi for more info on the issue im having i created a ticket here:
https://github.com/danethurber/webpack-manifest-plugin/issues/144

**Comment by budarin** [comment]
I also have the problem when hasing filenames
Webpack: 4.19.1

```js
plugins: [
        new CopyWebpackPlugin([
            { from: './src/common/manifest.json', to: '[hash].[ext]' },
            { from: './src/common/favicon.ico', to: '[hash].[ext]' },
        ]),
        new ManifestPlugin({
            fileName: 'assets-manifest.json',
            writeToFileEmit: true,
        }),
...
}
```
here is assets-manifest.json
```json
...
  "83e7b321450bbcdc5013d2822838febc.json": "/83e7b321450bbcdc5013d2822838febc.json",
  "4d263d3006aa8249f115a0318f48d3b3.ico": "/4d263d3006aa8249f115a0318f48d3b3.ico",
...
```
instead of having original names as the key - here is hashed name in both positions: key and value

**Comment by evilebottnawi** [comment]
@budarin problem in implementation what we need event in `manifest` plugin (there are not one plugin) and event are difference, we can handle all plugins events. We should add hook on event https://github.com/danethurber/webpack-manifest-plugin/blob/master/lib/plugin.js#L191 and all copied files will be in manifest

**Comment by kst83** [comment]
Would be great if you could release a version including this on npmjs.com

**Comment by chezhe** [comment]
@budarin Have you fix the problem —— key and value both hashed?

**Comment by chezhe** [comment]
@evilebottnawi I met same problem with @budarin 
webpack config

```
plugins: [
    new CopyPlugin([{
      from: 'public/src/img',
      test: /\.(png|jpe?g|gif|svg)$/i,
      to: 'img/[name].[md5:hash:hex:8].[ext]'
    }, {
      from: 'public/src/media',
      to: 'media/'
    }]),
    extractCSS,
    new ManifestPlugin({
      fileName: 'manifest.json',
      writeToFileEmit: true,
    }),
  ]
```

And got manifest

```
  "img/1-0-logo.e9833416.svg": "img/1-0-logo.e9833416.svg",
  "img/2-0-logo.89e800b4.svg": "img/2-0-logo.89e800b4.svg",
  "img/404.bfada369.png": "img/404.bfada369.png",
```

Any suggestion?

**Comment by evilebottnawi** [comment]
What is `ManifestPlugin` plugin? We need implement hook for this and plugins should use this hook

**Comment by chezhe** [comment]
> What is `ManifestPlugin` plugin? We need implement hook for this and plugins should use this hook

Here is `webpack-manifest-plugin`

**Comment by chezhe** [comment]
> What is `ManifestPlugin` plugin? We need implement hook for this and plugins should use this hook

https://github.com/webpack-contrib/copy-webpack-plugin/issues/104#issuecomment-370390225

This works for me, thanks for your reply.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/538
