### ISSUE TITLE
[Feature] Manually modify output path

### ISSUE THREAD

**Issue by patkec** [webpack-contrib/copy-webpack-plugin#107]
Hi!

It would be great if something like this would be supported:

```javascript
{
  context: './src/',
  from: '**/i18n/*',
  to: function(url) {
    return path.resolve('i18n', url.replace('i18n/', ''));
  }
}
```
Basically, we want to get all localization files and output them under a single i18n folder, preserving folder structure but without i18n.

I can also try adding this via PR during next days, if anyone else is interested.

**Comment by kevlened** [comment]
I like the idea of a `to` function!

**Comment by ivogallego** [comment]
Actually I'd include as parameters of the function all the available parameters in the template patterns, but I love the idea and actually need it!!

**Comment by julianxhokaxhiu** [comment]
Please consider solving this issue, either accepting the PR or implementing it yourself. This is a must in my opinion.

**Comment by evilebottnawi** [comment]
PR welcome :+1:

**Comment by darielnoel** [comment]
+1
