### ISSUE TITLE
npm is missing documentation

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/copy-webpack-plugin#109]
I'm not sure if you have noticed, but the [npm page](https://www.npmjs.com/package/copy-webpack-plugin) of this plugin is missing the readme.

I didn't see anything obviously wrong in the package setup, but maybe the readme is getting ignored for some reason. If I install the package, it's missing the readme.

**Comment by kevlened** [comment]
Oh wow, that's new. It existed for a while. I'll have to investigate.

**Comment by claudiuconstantin** [comment]
Still an issue

![image](https://cloud.githubusercontent.com/assets/1537573/22510431/a3011918-e89a-11e6-9d37-14c25273296f.png)

**Comment by bebraw** [comment]
Could this be a problem on npm's side? I know they've been doing some CDN related work and fixing bits. Perhaps that broke something for this particular package.

**Comment by michael-ciniawsky** [comment]
Seem to be working now https://www.npmjs.com/package/copy-webpack-plugin 👍  :)
