### ISSUE TITLE
[Bug] Behaves as if `flatten === true` if `from` is not a glob

### ISSUE THREAD

**Issue by thejohnfreeman** [webpack-contrib/copy-webpack-plugin#112]
With `output.path` as `build`:

```js
new CopyWebpackPlugin([
  { from: 'dir/index.html' }
])
// Copies to `build/index.html`. Loses intermediate directory.
```

```js
new CopyWebpackPlugin([
  { from: 'dir/*.html' }
])
// Copies to `build/dir/index.html`. Preserves intermediate directory.
```

I think these two configurations should behave the same, and the first behavior should only happen if I also pass `flatten: true`.

**Comment by evilebottnawi** [comment]
@thejohnfreeman breaking changes :disappointed: 
@michael-ciniawsky what do you think about this? Should we interpreted all from `content` and include intermediate directory?

**Comment by michael-ciniawsky** [comment]
Yep, I agree that the behavior should be consistent and ideally aligns with how `glob`  handles it by default

**Comment by evilebottnawi** [comment]
Let's do it in `6.0.0` because it can break many cases for people and we already have many breaking changes for `5.0.0`.
