### ISSUE TITLE
[Refactor] a debug level to show only files that have been copied

### ISSUE THREAD

**Issue by raymanoz** [webpack-contrib/copy-webpack-plugin#116]
The current behaviour of debug: 'info' is to report on everyfile being copied or not, when any file has changed, so you see a lot of this:
```
[copy-webpack-plugin] skipping 'path/to/file.js', because it hasn't changed
```

The actual file that is being copied out gets drowned out in a sea of these messages.

It would be nice to have a debug level that does not report on files that are not being copied. Another option is to move this excessive debug message to the debug level, and only show what's being copied in the info level.

**Comment by evilebottnawi** [comment]
I don't think `skipping 'path/to/file.js', because it hasn't changed` should be on other debug level, using `info` we provide all basic operations from read to write and messages why somethings happen/not happen so this messages expected. Feel free to feedback.
