### ISSUE TITLE
[Bug] Possible race condition with `url/file-loader`

### ISSUE THREAD

**Issue by klaszlo** [webpack-contrib/copy-webpack-plugin#118]
The relevant part of webpack.config:

    ...
    loaders: [
      {
        test: /\.(png|jpg)$/,
        use: 'file-loader?name=[path][name].[ext]'
      },
     {
        // HTML LOADER
        // Reference: https://github.com/webpack/raw-loader
        // Allow loading html through js
        test: /\.html$/,
        use: 'html-loader?exportAsEs6Default'
      }
    ...
    plugins: [
    new CopyWebpackPlugin([
      {from: PATH.uploads, to: path.join(PATH.build, 'uploads') }
    ]), //sometime it just do not copy everything recursively.

Some `.html` file references some `.png` file inside the `uploads` dir, resulting only some of the file got copied.
However it is nondeterministic, it either copies recursively, or just copies part of the directory.
I believe the `file-loader` plugin and the `CopyWebpackPlugin` do not play nice together.

I tried with blobs also (`**/*`) the same result.

Is there anyone else with similar experience?

**Comment by klaszlo** [comment]
In the meantime I solved it with the following webpack snippet:

     new WebpackShellPlugin({ safe: true,
         onBuildEnd:[ 'pwd; echo \\"cp -R ' + PATH.uploads + ' ' + PATH.build + '\\"; cp -R ' + PATH.uploads + ' ' + PATH.build ]
     }),

**Comment by yargalot** [comment]
This also happens with url-loader

**Comment by michael-ciniawsky** [comment]
If the file is loaded by `file-loader` && `copy-webpack-plugin` chance a high this leads to subtile bugs, you need to `ignore`  files in `copy-webpack-plugin` if you want to load them via `file-loader`

**Comment by jayseeg** [comment]
Was this closed because a use case wasn't posted?

I've got a use case that hits this bug.

I'm using `file-loader` with `image-webpack-loader` to fingerprint & optimize images. Once optimized, I need to move this folder up the tree into a parent rails app's public folder using `CopyWebpackPlugin`. Unfortunately, it just copies over previous contents before finishing the image optimization.

```
config.plugins = [
  ...
  new CopyWebpackPlugin([{
    from: path.join(__dirname, 'app', 'assets', 'build', 'spa-images'),
    to: path.join(__dirname, '..', '..', '..', 'public', 'spa-images')
  }])
];

config.module = {
  rules: [  {
      test: /\.(svg|png|jp?eg)$/,
      use: [
        'file-loader?name=spa-images/[name]-[hash].[ext]',
        {
          loader: 'image-webpack-loader',
          options: {
            mozjpeg: {
              progressive: false,
              quality: 75
            },
            optipng: {
              enabled: false,
            },
            pngquant: {
              quality: '75-90',
              speed: 4
            }
          }
        }
      ]
    }
  ]
};
```

Is it expected/accepted that `CopyWebpackPlugin` won't work on files accessed by `file-loader`?

**Comment by evilebottnawi** [comment]
@yargalot can you create new issue with reproducible test repo?

**Comment by jayseeg** [comment]
@evilebottnawi—if I get the time,... I'm up against a tight deadline right now & just abandoned `copy-webpack-plugin` in favor of `webpack-shell-plugin` to take advantage of the `onBuildEnd` hook as @yargalot suggested.

I'll probably just stick with that since it's pretty easy to `cp` or `rsync`.
