### ISSUE TITLE
[Refactor] make `from` optional when `transform` is used

### ISSUE THREAD

**Issue by somombo** [webpack-contrib/copy-webpack-plugin#123]
I'd like to propose that the `from` property of a `pattern object, be optional whenever it's used with a transform function (... or perhaps idempotently always optional). Here is a possible application of this:

```javascript
var externalContent = "## Hello World! \n\n\n" + 
                                     "I got this text from some other function ...";

new CopyWebpackPlugin([{
  // from: '', // <-- No need for `from`. 
  // File content is coming from `return` of transform function below instead.
  to: './README.md',
  transform: function() {

    return externalContent;
  }
}]);
```

Note (as can be shown if you turn on `debug`), that when one uses `from: ''` empty string the plugin tries to copy **every** single thing in the current path. Rather than **not** copy anything at all which is what is desired. 

Can this be fixed?
Thoughts?

**Comment by evilebottnawi** [comment]
@somombo for you use case better create separate plugin, also webpack have build-in `BannerPlugin` https://webpack.js.org/plugins/banner-plugin/. `CopyWebpackPlugin` using only for copying files. Thank you!
