### ISSUE TITLE
Ignore file that does not exist

### ISSUE THREAD

**Issue by PlayMa256** [webpack-contrib/copy-webpack-plugin#126]
Hello, is there a way to ignore the files that does not exist instead of throwing errors?

**Comment by hellivan** [comment]
As far as I remember, webpack 1.x version of copy-webpack-plugin ignored non-existing files, didn't it? Anyways, having a flag for such a behavior would be great.

**Comment by PlayMa256** [comment]
@hellivan i'm using 2.x so i'm not aware of that. Indeed, a flag to not throw errors and stop the bundling would be really nice!

**Comment by singuerinc** [comment]
@PlayMa256 If you use the `context` property you don't get any error if the folder/file doesn't exist.

```
{ context: path.resolve(__dirname, "a", "b"), from: "**/*", to: "c" }
```

**Comment by derekdon** [comment]
I don't suppose it's possible to do this when you're not using globs? 
```
{ from: 'a' },
{ from: 'b/c', to: 'c' },
{ from: 'd' }
```
I'd like to just get a warning when a specific "from" file doesn't exist, not break the build.

**Comment by zemzela** [comment]
I'm looking into this as a workaround for [https://github.com/webpack/webpack/issues/5360](url)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky what do you think about this option?

**Comment by michael-ciniawsky** [comment]
hmm... imho it's simply an `{Error}` (`ENOENT`) 😛. But if this is common in build chains (CI) to sneak in for some reason we can consider to relax it into a warning. But e.g sole 'misconfiguration' (adding patterns for non-existent files) isn't enough to justify changing the current behavior tbh.

**Comment by zanettin** [comment]
would be nice to have an option like this or just another `debug` option `ignore` or `silent`. we run several apps through the same webpack config and have to include the plugin conditionally now. thanks for all your work on that plugin 💪

**Comment by clm2609** [comment]
Im having the same issue as @zanettin , would love the option to convert from error to warning

**Comment by D-Pow** [comment]
I know this is a bit old, but came across this same issue recently and it seems the plugin has been updated with a [`noErrorOnMissing`](https://webpack.js.org/plugins/copy-webpack-plugin/#noerroronmissing) option that would solve this issue.

**Comment by YaminoYuki** [comment]
> I know this is a bit old, but came across this same issue recently and it seems the plugin has been updated with a [`noErrorOnMissing`](https://webpack.js.org/plugins/copy-webpack-plugin/#noerroronmissing) option that would solve this issue.

This really useful..thanx
