### ISSUE TITLE
[Chore] Recent update of node-dir breaks copy-webpack-plugin

### ISSUE THREAD

**Issue by valichek** [webpack-contrib/copy-webpack-plugin#128]
Please, check `4.x.x`  for same issue. https://github.com/fshost/node-dir/issues/50

**Comment by djflex68** [comment]
Having the same issue

**Comment by evilebottnawi** [comment]
Closed, because latest version don't use this package, just remove unnecessary packages from `package.json` (see https://github.com/webpack-contrib/copy-webpack-plugin/pull/171)
