### ISSUE TITLE
[Bug] DOT files are always treated as directories

### ISSUE THREAD

**Issue by infoeon** [webpack-contrib/copy-webpack-plugin#137]
DOT files are always treated as directories.

{from: path.resolve(__dirname, 'application/admin/.htaccess'), to: 'admin/.htaccess', toType: 'file'}

will result in a folder /admin/.htaccess/ being created when a file /admin/.htaccess should be created. If the "to" is changed to something like 'admin/zzz.htaccess' then it creates it as a file. It appears that the "toType" is ignored if it has a leading dot.

**Comment by michael-ciniawsky** [comment]
This is more related to the missing file extension I guess, but nevertheless buggy

**Comment by evilebottnawi** [comment]
Close this issue, because it is will be fixed after update `loader-utils` and we already issue about this https://github.com/webpack-contrib/copy-webpack-plugin/issues/117

**Comment by pgilad** [comment]
This is still not working

**Comment by evilebottnawi** [comment]
@pgilad it can be fixed only in major version :disappointed:

**Comment by pgilad** [comment]
I understand, but this bug is from aug 2017, was closed 3 months ago and it wasn't fixed. So I recommend opening it (Because it's still relevant) and perhaps providing an alternative solution 😄

**Comment by evilebottnawi** [comment]
@pgilad we already have issue https://github.com/webpack-contrib/copy-webpack-plugin/issues/117.

Too little time and a lot of work, if you wanna help feel free to PR:
1. We need upgrade `webpack-default` (https://github.com/webpack-contrib/copy-webpack-plugin/pull/146)
2. When fix and merge issue with milestone v5
3. :star: We release major version :+1:

**Comment by luigimannoni** [comment]
For people googling for this issue and came on this.
If you have updated the plugin and having this issue you're probably adding to the config the `to` key which is causing to spawn a folder called `.htaccess` at the root of the build directory (or whatever dot file you're trying to copy).

If your dot file needs to sit at the root then your config should have only the `from` key pointing to your dot file.

This works:
```
  new CopyWebpackPlugin([
    {
      from: './src/static/.htaccess',
    },
  ]);
```
 
This DOES NOT work:
```
  new CopyWebpackPlugin([
    {
      from: './src/static/.htaccess',
      to: '.htaccess',
    },
  ]);
```

This for example will copy the file at the `<build folder>/server/root/.htaccess`:
```
  new CopyWebpackPlugin([
    {
      from: './src/static/.htaccess',
      to: 'server/root',
    },
  ]);
```

Hope that clears things a little bit

**Comment by milesfrain** [comment]
Very strange that adding `to` only makes a directory for files _without_ an extension. If the files have an extension, then including `to` has no effect.

``` js    
new CopyPlugin({            
  patterns: [            
    {from: 'public/foo.js'},                // Copies to /foo.js
    {from: 'public/bar.js', to: 'bar.js'},  // Copies to /bar.js       
    {from: 'public/foo'},                   // Copies to /foo
    {from: 'public/bar', to: 'bar'},        // Unexpectedly creates a directory. Copies to /bar/bar 
  ],            
}),        
```

**Comment by eujeniogonzalez** [comment]
It's still not working

`
    new CopyWebpackPlugin({
      patterns: [
        {
          from: path.join(__dirname, 'public', 'fonts'),
          to: path.join(__dirname, 'build', 'fonts'),
          noErrorOnMissing: true
        },
        {
          from: path.join(__dirname, 'public', 'images'),
          to: path.join(__dirname, 'build', 'images'),
          noErrorOnMissing: true
        },
        {
          from: './public/.htaccess',
          to: './build',
          noErrorOnMissing: true
        }
      ],
    })
`
