### ISSUE TITLE
[Bug] Plugin patterns copy parents 

### ISSUE THREAD

**Issue by nickenchev** [webpack-contrib/copy-webpack-plugin#141]
```js
{
  "to": "assets",
  "from": {
    "glob": "src/assets/**/*",
    "dot": true
  }
}
```

this ends up creating "dist/assets/src/assets" instead of copying all sub-dirs/files from src/assets into assets/

Why would I end up with assets/src/assets if the glob pattern is all subdirectories/files inside src/assets?

Thanks

**Comment by jcardoz** [comment]
I have the same issue. Attaching my code below.
`new CopyWebpackPlugin([{
      "from": "src/assets/**/*.*",
      "to": "assets",
      "toType": "dir"
    }], {
      "ignore": [
        ".gitkeep"
      ],
      "debug": "warning"
    })`

**Comment by jcardoz** [comment]
@nickenchev : The following configuration seemed to resolve the issue for me. This may help in your case as well:
`{
          "context": './src/assets/',
          "from": '**/*',
          "to": './assets/'
      },`

**Comment by evilebottnawi** [comment]
@nickenchev @jcardoz plugin works as expected by default `context` (`compiler.options.context` - example `/path/to/src`), `glob` with default `cwd` options (`compiler.options.context`) return `src/assets/file.txt`.
Output directory `/path/to/dist`, `to` interpreted as `/path/to/dist/assets/` + `src/assets/file.txt`. For resolve this issue see comment above. In short - use `context` option. Thank you!
