### ISSUE TITLE
[Question] How to add the file hash value？

### ISSUE THREAD

**Issue by xybin1990** [webpack-contrib/copy-webpack-plugin#143]
I want to copy the file after the hash value

```
"[name].[chunkhash:8].js"
```

**Comment by sebacruz** [comment]
You can use `[name].[hash].[ext]` on the `to` property of the `patterns` argument:

```
plugins: [
  new CopyWebpackPlugin([
    { 
      from: 'from/file.txt',
      to: 'to/[name].[hash].[ext]'
    }
  ]
]
```

**Comment by michael-ciniawsky** [comment]
@sebacruz 👍  Thx

Feel free to reopen if still regressions :)

**Comment by itssumitrai** [comment]
Hi, 
I had the same problem, the `hash` is the hash value for the file contents, but I need the `chunkhash` and not the `hash` value as stated in the original issue. The `file-loader` doesn't seem to support `chunkhash` it seems.
