### ISSUE TITLE
[Bug] Moving entire directory only works on second run?

### ISSUE THREAD

**Issue by Andrei-** [webpack-contrib/copy-webpack-plugin#144]
I have the following setup:

``` js
new CopyWebpackPlugin([
            {
                from: resolve(__dirname, 'src/images'),
                to: resolve(__dirname, 'dist/assets/images')
            },
            {
                from: resolve(__dirname, 'src/email-templates'),
                to: resolve(__dirname, 'dist/assets/email-templates')
            },
            {
                from: resolve(__dirname, 'src/data'),
                to: resolve(__dirname, 'dist/assets/data')
            },
            {
                flatten: true,
                from: './src/*.html',
                to: resolve(__dirname, 'dist/assets')
            },
            {
                from: resolve(__dirname, 'dist/assets'),
                to: resolve(__dirname, '../website/assets')
            }
        ])
```

My intention:

- first 4 commands are gathering all assets to a folder called dist/assets
- last command is supposed to take everything from dist/assets and copy to an external folder website/assets. So it depends upon the first 4 being finished.

However this does not work. Not when dist/assets has been cleared. It works when I run it the second time without clearing dist/assets.

So this makes me think the plugin is perhaps trying to execute all commands async?
How can I fix this?

**Comment by evilebottnawi** [comment]
@Andrei- why don't copy first 4 commands `website/assets` instead copy to intermediate directory?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/318
