### ISSUE TITLE
[Bug] webpack --watch --progress with copy-webpack-plugin keeps spinning

### ISSUE THREAD

**Issue by gusdaud** [webpack-contrib/copy-webpack-plugin#145]
Hi,

When I run `webpack --watch --progress` using copy-webpack-plugin it builds the bundle but keeps doing some kind of processing (it shows x% compiling, x% hasing, x% emitting in the console terminal in an eternal loop).

I'm adding the plugin to my webpack.config.js using this code
```js
config.plugins.push(new CopyWebpackPlugin([{
  from: path.resolve(__dirname, 'dist/*.*'),
  to: path.resolve(__dirname, '../angular/build/component-build/[name].[ext]'),
}]));
```

**Comment by michael-ciniawsky** [comment]
@gusdaud Does this problem still persists? If could you please provide more info about your setup and `webpack/copy-webpack-plugin` version in use ?

**Comment by rosea1** [comment]
I also have the same issue, for some reason when you run webpack with the --watch option, it starts watching the files BEFORE it has finished building. Therefore when you copy a file, presumably to a file with the same name (so it overwrites contents of the file), webpack sees that as a "change" then runs the build again where the copy command is happening again and it is getting stuck in a loop. That is what i understand is happening

**Comment by peter-brennan** [comment]
I'm getting this issue also, did you guys find a solution?

**Comment by rosea1** [comment]
@peter-brennan  I also opened another ticket for this, and someone did actually solve the problem, see https://github.com/webpack/webpack/issues/6241
It appears to be fixed now if you npm update to latest
