### ISSUE TITLE
[Feature] Provide default `context` option

### ISSUE THREAD

**Issue by cletusw** [webpack-contrib/copy-webpack-plugin#148]
Currently, `context` defaults to `compiler.options.context` from webpack. However, I'd like all my copy patterns to use `./src` as the default context, even though I can't change my webpack context to that for other reasons.

Could we add a fallback to the plugin options? The overall context fallback logic would be:

`context` property on pattern object -> `context` property in plugin options -> `context` property on webpack config

If this sounds okay, I can try to come up with a PR.

**Comment by michael-ciniawsky** [comment]
The pattern.context isn't sufficient enough for you I guess?

```js
{
   context: 'from/directory', // <= ?
   from: '**/*',
   to: '/absolute/path'
}
```

Feel free to open a PR if you want to tackle this of course 😛

**Comment by cletusw** [comment]
Right, all of my patterns are going to repeat the same context, so it'd be nice to just have it once (while allowing overrides, of course)

**Comment by cletusw** [comment]
@michael-ciniawsky Created #149 to add this option.

**Comment by michael-ciniawsky** [comment]
@cletusw Any idea on this one #58 :) ?

**Comment by cletusw** [comment]
@michael-ciniawsky Just added a comment. Not sure what the expected behavior is.
