### ISSUE TITLE
[Feature] support `{String}` patterns

### ISSUE THREAD

**Issue by cletusw** [webpack-contrib/copy-webpack-plugin#150]
Feature request: Could the patterns array support plain old strings, where
```javascript
patterns: [
  'myFile.txt'
]
```

is equivalent to
```javascript
patterns: [{
  from: 'myFile.txt'
}]
```

?

This would reduce boilerplate when many of the copy patterns are simple.

If this is okay, I can implement the PR.

**Comment by michael-ciniawsky** [comment]
Always feel free to send a PR as it is even easier to triage feature implementations that way :) There is no guarantee if it lands as it always requires sign-off from 2+ maintainers at minimum. The proposal seems reasonable enough through (from a first glance)

**Comment by cletusw** [comment]
@michael-ciniawsky Will do! Some projects have explicit rules against submitting PRs that haven't been raised as an issue first, so I just wanted to be sure. Thanks!
