### ISSUE TITLE
[Feature] Possibility to copy symbolic links

### ISSUE THREAD

**Issue by ausminternet** [webpack-contrib/copy-webpack-plugin#158]
Hey there,

I would like to have the possibility to copy symbolic links, which you can do on terminal with the `-L` option (`cp -L`). Is this already possible, or can it be implemented?

**Comment by evilebottnawi** [comment]
@ausminternet what do you mean? copy symbolic link or copy files/file content by symbolic link?

**Comment by ausminternet** [comment]
copy the symbolic link without resolving it.

**Comment by evilebottnawi** [comment]
Example of usage https://github.com/up9cloud/testcase-for-copy-webpack-plugin-issues-313

**Comment by alfredking1988** [comment]
Hi, I wonder if it is possible to add an option to switch to the old behaviour?
