### ISSUE TITLE
Proposal change badge section to use html tag

### ISSUE THREAD

**Issue by brutalcrozt** [webpack-contrib/copy-webpack-plugin#159]
Intent to fix the codecov badge, i found that the badge section isn't centered. Personally it break the harmony since the webpack logo is centered.
![image](https://user-images.githubusercontent.com/3001652/32156183-644e6b40-bd6e-11e7-974c-375f6c63ae4f.png)

I already do some work, but finding a [problem](https://stackoverflow.com/questions/47008620/how-to-use-reference-style-link-along-with-html-tag).
> The problem already posted on SO

Please let me know if you have alternative solutions, frankly change reference-style link to inline-style link is the only option i have in mind :confused: .

**Comment by michael-ciniawsky** [comment]
That's in sync with the org README boilerplate, it's acts like  `<head>` (metadata). They could be centered under the Plugin Name, but tat would require changes to all README's and even the first standards track isn't finished yet 😅  I'm closing this for now

**Comment by brutalcrozt** [comment]
@michael-ciniawsky where is the org README boilerplate?
> would require changes to all README's and even the first standards track isn't finished yet

can i have better explanation for that? i am not quite understand.
where i can chat with you? via email doesn't look handy, anyway thanks for the response :smile: .
