### ISSUE TITLE
[Bug] `after-emit` callbacks are called multiple times in watch mode

### ISSUE THREAD

**Issue by jmlopez-rod** [webpack-contrib/copy-webpack-plugin#16]
I noticed that when defining `after-emit`, 

``` js
compiler.plugin("after-emit", function(compilation, cb) {
```

it makes the emit run multiple times when webpack is in watch mode. To see this we can write a `console.log` statement in emit:

``` js
  compiler.plugin('emit', function(compilation, cb) {
    console.log("emit...");
```

After running `webpack -watch` we get

```
emit...
emit...
emit...
emit...
```

If we comment out the `after-emit` block then webpack only calls emit when we modify one of our project files. Now correct me if I'm wrong, but the after emit section is just to add the files that we are copying as dependencies, and so webpack is watching for changes in these files. This is fine I guess, but if we are only copying the bundled files somewhere else then watching over these files seems like a waste of time, especially if we know that they haven't changed.

Perhaps we could check if the file is being already tracked by webpack:

```
  var currentAssets = _.keys(compilation.assets);
  var inProduction = _.find(currentAssets, function(name) {
    return _.endsWith(absFileSrc, name);
  });
```

and only add the file to `fileDependencies` if `inProduction` is undefined:

```
if (!inProduction) {
  fileDependencies.push(absFileSrc);
}
```

The problem with be with the `contextDependencies` though.

**Comment by kevlened** [comment]
This seems related to #15

**Comment by evilebottnawi** [comment]
@jmlopez-rod don't reproducible, seems you have something who change files and fire rebuild in watch mode. Please update to latest version (`webpack`, `loader` and `plugins`) and try again. Feel free to reopen if you still have issue, also please create minimum reproducible test repo. Thank you!
