### ISSUE TITLE
[Test] Coverage

### ISSUE THREAD

**Issue by brutalcrozt** [webpack-contrib/copy-webpack-plugin#161]
As you can see the coverage badge are broken, giving the coverage unknown.
I got free a couple of hours, so i will work on it.

**Comment by brutalcrozt** [comment]
No coverage found, see [here](https://travis-ci.org/brutalcrozt/copy-webpack-plugin/jobs/296511293)

**Comment by michael-ciniawsky** [comment]
This is to be expected since the tests aren't migrated yet and therefore no coverage report is collected atm. It needs #146 applied and a tests refactor to work

**Comment by brutalcrozt** [comment]
@michael-ciniawsky  Thanks for the response :smile: , i really hope can chat with you. There is alternative instead of email? twitter, gitter, slack or something?

**Comment by evilebottnawi** [comment]
Fixed
