### ISSUE TITLE
Plugin does not delete files or rename files

### ISSUE THREAD

**Issue by HauntedSmores** [webpack-contrib/copy-webpack-plugin#167]
Is it posibble to have the plugin delete files in the `to` directory that have been deleted in the `from` directory? It would be really nice during development to not have to worry about the dist and src folders getting out of sync.

**Comment by michael-ciniawsky** [comment]
That's out of scope for this plugin imho. Use e.g the `clean-webpack-plugin` in tandem with `copy-webpack-plugin` instead please

**Comment by HauntedSmores** [comment]
@michael-ciniawsky Thanks for the suggestion. Totally get your position - unfortunately the `clean-webpack-plugin` doesnt work for deletions either, the build never triggers - looks like a core webpack thing to me.
