### ISSUE TITLE
Hot module reload w/o refreshing the page

### ISSUE THREAD

**Issue by jrmcdona** [webpack-contrib/copy-webpack-plugin#168]
Hello,
Plugin is working great.   I copy some LESS files to the Dist folder.  The watch feature is working well.

Has anyone solved the issue where you don't have to refresh the page to see the changes?   

Thanks

**Comment by jrmcdona** [comment]
Or maybe I just need to figure out how to get Less in the bundles to achieve this.   I need Less in the bundles as Less and not CSS  (because I have themes which update the Less variable when the user wants), which is which I have seen so far things are compiling Less into CSS.

**Comment by michael-ciniawsky** [comment]
How do you serve Less files to the client without transpiling them ? HMR won't work with this plugin. Use the `modifyVars`  option of `less-loader` or CSS Custom Properties directly (modern browsers only) so the variables can be accessed and changed via JS or a separate `theme-${name}.css` file containing only the custom props

**Comment by jrmcdona** [comment]
@michael-ciniawsky If you compile LESS to CSS via Webpack using less-loader and then try to use modifyVars.  It will not work, becasue at that point its just plain jane CSS.  I just went down that path.

Less is serving fine this:
    <link rel="stylesheet" type="text/less" href="~/dist/variables.less" />
      <link rel="stylesheet" type="text/less" href="~/dist/bootstrap-overrides.less" />
      <link rel="stylesheet" type="text/less" href="~/dist/primary.less" />

and modifyVars is now working after using your plugin to  just copy the Less over to dist without converting to CSS.

Will keep looking for other options but at least modifyVars is working now, thanks

**Comment by jrmcdona** [comment]
Actually, I was using modifyVars from Less.js, I didn't see modifyVars as a loader option on less-loader.  Will look more into that.
