### ISSUE TITLE
[Feature] copy files only on first run

### ISSUE THREAD

**Issue by httpeace** [webpack-contrib/copy-webpack-plugin#169]
is there any special config settings so the folders are only copied on the first build only? did I miss anything on the documentation

**Comment by michael-ciniawsky** [comment]
By first build you mean when running `webpack` multiple times (without watch mode) ? Files are watched for changes in watch mode, but not between multiple runs atm. Maybe an existence check could be added, but this needs triage first

**Comment by evilebottnawi** [comment]
webpack already do it on own side

**Comment by evilebottnawi** [comment]
It is bad idea we should always to emit files, otherwise build will not be persistent, what could potentially break other plugins (for example clean-webpack-plugin)

**Comment by hsdonkin** [comment]
Running into this issue currently:
- CopyPlugin copies SVG from `./src/svg/*.svg` to another dir like `./components/svg/*.js`
- Tailwind PostCSS plugin is watching `./components/*/**.js` for changes
- Tailwind triggers a build
- CopyPlugin copies SVG.....

**Comment by alexander-akait** [comment]
@hsdonkin exclude svg from watching on Tailwind side, because postcss plugin already watch dev dependecies for Tailwind and will run rebuild if svg was changed
