### ISSUE TITLE
4.4.2 completely broken : dist deleted !

### ISSUE THREAD

**Issue by cyrilletuzi** [webpack-contrib/copy-webpack-plugin#172]
`dist` folder is missing in 4.4.2 release, so it breaks every tools depending on this module !

@d3viant0ne

**Comment by ocombe** [comment]
I was gonna open an issue with this, please release a fix asap because it breaks @angular/cli :(

**Comment by stas-kh** [comment]
Guys, we need this fix asap, please

**Comment by khdevnet** [comment]
We have same problem, can you fix this?

**Comment by bubkoo** [comment]
Online waiting...

**Comment by ocombe** [comment]
In the mean time `npm install -D copy-webpack-plugin@4.2.1` will fix the problem

**Comment by oleksandrstarov** [comment]
Please fix this asap, it is killing the deadline

**Comment by sokra** [comment]
> Please fix this asap, it is killing the deadline

Chill down. It has been reported 5 minutes ago...

**Comment by evilebottnawi** [comment]
Don't flood please, we will work on this

**Comment by Golodnyi** [comment]
guys, version 4.2.2, not 4.4.2

**Comment by d3viant0ne** [comment]
I know what he meant, fixed in `4.2.3`

**Comment by d3viant0ne** [comment]
For all of you less the CLI group who has a legitimate gripe, you can simply pin a dependency if something like this happens and be less dramatic.

It's 04:00
It was broken for all of 9 minutes
If your deadline is being killed, there was a issue long before `v4.2.2`

Before you start spamming maintainers, bare in mind you can't even get a 10 minute turn around at a fast food restaurant. Be less spastic, you will live longer.

**Comment by ocombe** [comment]
And don't forget that pinning dependencies (manually, or with yarn) is the safest bet ;-)

**Comment by filipesilva** [comment]
@sokra @evilebottnawi @d3viant0ne thanks for the quick fix on this! 

Wasn't expecting so many people to be affected in such a short period of time but if this affected you please remember that **without using package-lock.json or yarn.lock you will will never ensure that your dependencies are the same between installs**.

Bugs and bad releases unfortunately happen but there is nothing library maintainers can do to to truly prevent this from propagating. Pinning dependencies is not enough. It is up to you, as a consumer, to use dependency locks.
