### ISSUE TITLE
Version 4.2.2 - No dist exported?

### ISSUE THREAD

**Issue by sgb-io** [webpack-contrib/copy-webpack-plugin#173]
Possibly a bad release? I can see that you published this very recently, but installing this module currently seems to not give us the `dist` folder and the module cannot be found when attempting to require it.

v4.2.1 seems to work correctly.

**Comment by evilebottnawi** [comment]
@sgb-io Already fixed in `4.2.3`, duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/172
