### ISSUE TITLE
[Feature] `writeWhenEmit` option

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/copy-webpack-plugin#175]
If set to `true` will emit to build folder and memory in combination with `webpack-dev-server`. Why? Some files should be written to disk not memory-fs (example i have `php` project with `apache` and coping `.htaccess` using this plugin and i need write `.htaccess` to disk no memory-fs).

ping @michael-ciniawsky @d3viant0ne

**Comment by michael-ciniawsky** [comment]
- Why do you need the `.htaccess` when running `webpack-dev-server` or is this just an example ?  - Since `copy-webpack-plugin` relies on `compiler.outputFileSystem` is there an option to set certain assets to `emit/write` or will this require additional  'fs' logic within `copy-webpack-plugin` itself ? 
- Will this be a pattern option or plugin option ?

**Comment by d3viant0ne** [comment]
> Why do you need the .htaccess when running webpack-dev-server or is this just an example ?

`.htaccess ` would be a production build only action for the most part.

**Comment by evilebottnawi** [comment]
@michael-ciniawsky
* I am use proxy option, on front i have nginx + apache, many php projects works using this stack
* `fs` logic better, this is just couple lines of code
* pattern option

@d3viant0ne disagree i have difference `php_flag` and `php_value` values for dev and production env.
Another example generate configuration for application, example `wp-config.php` and other configuration files which should be written on disk not memory.

**Comment by d3viant0ne** [comment]
I wasn't disagreeing with you not the concept for this feature, just saying that in most cases you don't need to write an `.htaccess` file for local development.

I personally write my configurations, `nginx` in my case as a part of my CI process as opposed to my bundling process but I certainly don't see any harm in adding it.

**Comment by evilebottnawi** [comment]
@d3viant0ne i do PR in near future, it is allow to remove many dirty hack in some projects in webpack config :+1:

**Comment by evilebottnawi** [comment]
Close in favor `write-file-webpack-plugin`
