### ISSUE TITLE
support inherit webpack options and make the copied files with hash and publicPath

### ISSUE THREAD

**Issue by jiangtao** [webpack-contrib/copy-webpack-plugin#180]
hi author! I found that `copy-webpack-plugin` can not sopport the cases below:

1. When copy the files, files can be copied and renamed by [name][hash][ext]
2. When copy the files, files can be appended by webpack options `publicPath`

The cases can help us to copy the files smartly in the team work.

**Comment by evilebottnawi** [comment]
@jiangtao what do you mean? we support `[name][hash][ext]` and respect outputPath `webpack`.

**Comment by jiangtao** [comment]
how to configure in the copy-webpack-plugin opts?

**Comment by michael-ciniawsky** [comment]
```{ from: src/*, to: dist/[name].[hash].[ext] }``` 

See the README for pattern options for more :)

**Comment by DmitryGonchar** [comment]
@michael-ciniawsky Is [path] supported?

`{ from: '../node_modules/jquery/dist/jquery.min.js', to: '[path][name].[ext]' }`, copies file to the root of "out" folder, without preserving path. At least for dev server
