### ISSUE TITLE
is-glob changed behaviour of '?'

### ISSUE THREAD

**Issue by pravi** [webpack-contrib/copy-webpack-plugin#189]
See https://github.com/micromatch/glob-base/pull/5

Should copy-webpack-plugin stick to is-glob 2.0 behaviour or should we update to latest?

**Comment by evilebottnawi** [comment]
@pravi can you provide more information what works unexpected or broken? We can migrate from micromatch to minimatch or other implementation if something broken or doesn't work.

**Comment by pravi** [comment]
@evilebottnawi I'm worried about possible conflict here. See https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/package-lock.json#L1951 which needs is-glob 2.0.1 where as you need https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/package.json#L22 those two will give two different results if a filename has '?'. We need to fix the conflict here by deciding if a single '?' is a glob or not.

**Comment by evilebottnawi** [comment]
@pravi yep, problem may happens, i think `glob-base` should update `is-glob`, we can't track dependencies of dependencies to ensure conflicts. But maybe we can migrate to more popular solution `https://www.npmjs.com/package/minimatch`, need investigate. In near future i will do this.

**Comment by evilebottnawi** [comment]
@pravi don't worry `glob-base` and `glob-parent` (which use `is-glob@2`) is used by `chokidar` and don't install when you use `copy-webpack-plugin`
