### ISSUE TITLE
Using glob throws error in enoent

### ISSUE THREAD

**Issue by axtn** [webpack-contrib/copy-webpack-plugin#192]
Hello
Either using glob, or trying to copy directories throws an error.
Using this:
```
new CopyWebpackPlugin([
            {
                from: path.join(__dirname, 'src/app/test'),
                to: 'test',
                force: true
            }
        ])
```

throws:

`ERROR in ENOENT: no such file or directory, stat 'C:\projects\MyProject\src\app\test\**\*'`

I get the same issues if I try to use `**/*` on `from: `. 

If i try to copy one file over, ittl work fine, for example: 
```
new CopyWebpackPlugin([
            {
                from: path.join(__dirname, 'src/app/test/subfolder/file.css'),
                to: 'test',
                force: true
            }
        ])
```

Any ideas?

**Comment by axtn** [comment]
Forgot to mention, If it makes a difference, I run this on a windows machine

**Comment by evilebottnawi** [comment]
@axtn can you create minimum reproducible test repo?

**Comment by axtn** [comment]
I'm back, after hours of suffering.
Running:
`npm install copy-webpack-plugin@4.3.0` (specifically stating the [latest version](https://www.npmjs.com/package/copy-webpack-plugin) available at the time) forced the package to update its' dependencies. Now it runs just fine.

Check out the attached image to see the before and after of running the version specific `npm install`.
![capture](https://user-images.githubusercontent.com/6938887/34277893-85b08d38-e65c-11e7-9553-91df6d646971.JPG)
