### ISSUE TITLE
Created and modified dates of copied files are changing

### ISSUE THREAD

**Issue by alekam** [webpack-contrib/copy-webpack-plugin#202]
This set up current date and time on each file that be copied! It's wrong, I think. This plugin does not change file content and must save its original date and time. Also this helpful for production builds - you can check files' time and copy only new files only for speed up deploy process.

Cheers!

**Comment by evilebottnawi** [comment]
@alekam don't related to `copy-webpack-plugin`, we use `compilation.assets` (https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/writeFile.js#L125), i.e. we don't write files to file system, it is do `webpack`, please create issue in `webpack` repo. Thanks!

**Comment by evilebottnawi** [comment]
@alekam also you can create plugin that save created and modified date of files.
