### ISSUE TITLE
Files emitted by the plugin don't change the compilation hash

### ISSUE THREAD

**Issue by rubenspgcavalcante** [webpack-contrib/copy-webpack-plugin#203]
Hello there,
I developed a **plugin for webpack** and it does some actions when the compilation hash changes. But some users noticed that the actions weren't triggered after changes on files under the CopyWebpackPlugin, even after webpack trigger the compilation. 
After some tests, I've noticed that any changes made on files tracked by the plugin emits a new compilation, but don't change the compilation hash. This way there's no certain way to know if the last compilation is different from the current one.

Thanks for the help!

**Comment by evilebottnawi** [comment]
@rubenspgcavalcante can you create minimum reproducible test repo?

**Comment by rubenspgcavalcante** [comment]
For instance:
```js
compiler.plugin("after-emit", (comp, done) =>
  console.log(comp.hash);
  done();
);
```
The console.log always will log the **same compilation hash when changing files tracked by the CopyWebpackPlugin**. This means that the plugin don't alter the compilation hash in the end.
The problem is I can't find in the docs how to track the files hashes individually, if is possible.

**Comment by evilebottnawi** [comment]
@rubenspgcavalcante why copy plugin should change `hash` of compilation, we just emit files, don't modify modules/chunks or another stuff. Can you describe use case?

**Comment by rubenspgcavalcante** [comment]
My plugin does hot reload of extensions, but in Chrome if you do to much auto-reload of the extension you're developing, it blocks it. So to not do auto-reloads without necessity (the compilation is the same as before) I always check the compilation hash and if it's equal, it simply does nothing.
The problem is when dealing with files emitted by the CWP, it triggers a new compilation, but with no changes on the hash (and my plugin assumes nothing has changed).

So, there's a way to check if there's changes when the CWP emits a changed file?

**Comment by evilebottnawi** [comment]
@rubenspgcavalcante we don't add any assets if they already in assets (https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/writeFile.js#L104). You can just get hash of `assets` to determinate something changes. Or use webpack `stats`, we use standard webpack api, other plugin(s) also can add/modify/delete files from `assets`.

**Comment by rubenspgcavalcante** [comment]
Ok @evilebottnawi , thanks for your help! I'll try it out! :)
