### ISSUE TITLE
Is it possible to use something like compiler.inputFileSystem over fs?

### ISSUE THREAD

**Issue by Meberem** [webpack-contrib/copy-webpack-plugin#204]
Would it be possible to pass the `compiler.inputFileSystem` or `compilation.inputFileSystem` or similar to the functions that need it as opposed to taking a hard dependency on the fs module?

It would make testing webpack with a memoryfs a bit easier

**Comment by evilebottnawi** [comment]
@Meberem look https://github.com/webpack/webpack/issues/1562#issuecomment-165506401, you can write simple script

**Comment by Meberem** [comment]
Thanks for the pointer, I have been using that method however and am encountering issues such as `[copy-webpack-plugin] WARNING - unable to locate '/mock/src/a.css' at '/mock/src/a.css'`

I have distilled my issue into the following script:
```
var path = require("path");
var webpack = require("webpack");
var MemoryFileSystem = require("memory-fs");
var CopyWebpackPlugin = require("copy-webpack-plugin");

var mockFs = new MemoryFileSystem();
mockFs.mkdirpSync("/mock");
mockFs.mkdirpSync("/mock/src");
mockFs.writeFileSync("/mock/src/a.css", "a_css");
mockFs.mkdirpSync("/mock/output");

const options = {
    context: "/mock/",
    entry: "/mock/src/entry.js",
    output: {
        path: "/mock/output/",
    },
    plugins: [
        new CopyWebpackPlugin([
            {
                from: "/mock/src/a.css",
                to: "/mock/output/a.css"
            }
        ])
    ]
};

var compiler = webpack(options);

compiler.inputFileSystem = mockFs;
compiler.resolvers.normal.fileSystem = compiler.inputFileSystem;
compiler.resolvers.context.fileSystem = compiler.inputFileSystem
compiler.outputFileSystem = mockFs;

compiler.run(function(err, stats) {
    const stat = mockFs.statSync("/mock/output/a.css"); // File doesn't exist as it was never copied
    console.log(stat);
});
```

From this it looks like the issue is occuring because `/src/writeFile.js` and `/src/preProcessPattern.js` uses `fs` over a webpack provided one. Although admittedly I am fairly clueless in this area, so any pointers would be appreciated.

**Comment by evilebottnawi** [comment]
@Meberem seems you are right, we should use `compiler.inputFileSystem` instead `fs` module. It try to send PR today.

**Comment by Meberem** [comment]
Amazing, thank you so much
