### ISSUE TITLE
how can i write file to disk from memory when use webpack-dev-server

### ISSUE THREAD

**Issue by yinshuxun** [webpack-contrib/copy-webpack-plugin#207]
Thanks for the great loader, however some files should be written to disk not memory-fs when i use webpack-dev-server,what's the right way to do it？

**Comment by evilebottnawi** [comment]
@yinshuxun please use `write-file-webpack-plugin`(https://github.com/gajus/write-file-webpack-plugin) plugin for this purpose. Example:
```js
new WriteFilePlugin({
    test: /stats.json$/
 })
```
Thanks for issue.

**Comment by yinshuxun** [comment]
@evilebottnawi i want write to another directory not the webpack output directory,which option can use

**Comment by evilebottnawi** [comment]
@yinshuxun just write own script to move files from `webpack` directory and run his after `webpack` build

**Comment by pixelass** [comment]
Sadly there are numerous issues in [gajus/write-file-webpack-plugin](https://github.com/gajus/write-file-webpack-plugin) reporting that files cannot be written. Several related issues have been reported and closed without resolution. This does not invite to opening new issues there. 

I would love to see this feature added here. by simply adding n option `alwaysWriteToDisk`
