### ISSUE TITLE
Ignore pattern for folders

### ISSUE THREAD

**Issue by gnihi** [webpack-contrib/copy-webpack-plugin#209]
I'm not quite sure if I am doing something wrong but it seems like there is a problem with ignoring a complete folder.

I've tried several ways but none of them seems to work:
```javascript
new CopyWebpackPlugin([
   { 
      from: path.resolve('./src/app/routes/**/*.html'), 
      to: 'partials/routes', 
      flatten: true, 
      ignore: [
         {dot: true, glob: 'reports/**/*.html'}
      ]}
])
```

```javascript
new CopyWebpackPlugin([
   { 
      from: path.resolve('./src/app/routes/**/*.html'), 
      to: 'partials/routes', 
      flatten: true, 
      ignore: ['reports/**/*.html']
   }
])
```
What am I missing?

**Comment by evilebottnawi** [comment]
@gnihi `ignore: ['directory/{**/*,*}']`, also try `ignore: ['directory']` ?

**Comment by gnihi** [comment]
Thanks for the quick answer! I assume you mean `ignore: ['directory/{**/*.*}']`.
Sadly both ways don't work eihter.

**Comment by evilebottnawi** [comment]
@gnihi seems you write invalid nested path, look at tests and examples https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/tests/index.js#L1254

**Comment by gnihi** [comment]
I've changed my folder structure, so this problem became obsolete.
But thank you very much for you quick help!

**Comment by tinyfly** [comment]
For what its worth, this problem still exists, If I set flatten:true then I can't ignore files based on "from" directory structure.
