### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by jbruni** [webpack-contrib/copy-webpack-plugin#211]
This is the error I get trying to use this plugin with Webpack 4 beta:

```
/home/jbruni/project/node_modules/copy-webpack-plugin/dist/index.js:151
                    compilation.contextDependencies.push(context);
                                                    ^

TypeError: compilation.contextDependencies.push is not a function
```

**Comment by evilebottnawi** [comment]
@jbruni thanks for issue, fix it in near future

**Comment by alberto2000** [comment]
Any news on webpack 4 support?

**Comment by evilebottnawi** [comment]
@alberto2000 we already support `webpack@4` just update you deps

**Comment by filippoitaliano** [comment]
I've the same problem, this plugin seems to NOT work with `webpack@4`. Is the plugin supposed to be used the same way as before?

**Comment by filippoitaliano** [comment]
Sorry, the plugin has some issues with `webpack-dev-server@3.1.1`, not with `webpack@4`.
