### ISSUE TITLE
Taking the order of patterns into account when copying multiple directories

### ISSUE THREAD

**Issue by aholtkamp** [webpack-contrib/copy-webpack-plugin#213]
This is not a bug report but more of a "am I missing a configuration option?" kind of issue.

We have several folders that contain assets which are copied using the copy-webpack-plugin to the same target folder. We don't make any assumptions about the contents of these folders but we want to make sure that if the same asset is found in multiple folders that the order in which the patterns are defined determines which file "wins".

Example:

Using this configuration:

new CopyWebpackPlugin([
  {
    from: "dir1",
    to: "target"
  },
  {
    from: "dir2",
    to: "target"
  },
  {
    from: "dir3",
    to: "target"
  }  
]);

and having the file "test.txt" in all three directories (dir1, dir2, dir3) with different content we want to make sure that the "target" directory always has the "test.txt" from "dir3".

This seems to be the case for about 90% of the executions, but sometimes another directory "wins".

When inspecting the code of the plugin, it seems to be implemented in a way, that every pattern is transformed into a Promise and all Promises are fired at once, so we cannot make any assumptions about the order these patterns are processed.

Am I missing a configuration option or can this not be achieved using the "copy-webpack-plugin"? Our workaround would be to use multiple instances each having a single pattern, but this seems to be overhead.

**Comment by evilebottnawi** [comment]
@aholtkamp can you describe use case?

**Comment by aholtkamp** [comment]
Our use case is that we have different packages with templates that are processed by our web server (not via webpack). Packages can override templates of other packages. The override order is determined by the dependency hierarchy. We are using the copy-webpack-plugin to copy the templates of the packages and need to take the precedence into account.

**Comment by evilebottnawi** [comment]
@aholtkamp right now copy is concurrence for decrease build time. Maybe copy plugin is not best solution for this?

**Comment by aholtkamp** [comment]
Thanks for the quick answer. Any suggestions for a more suitable plugin? Basically it is just copying, but with a fixed order the different copy tasks are performed.

**Comment by evilebottnawi** [comment]
@aholtkamp i think for this solution better use own plugin or use cli for copy using https://github.com/1337programming/webpack-shell-plugin or https://github.com/itgalaxy/execa-webpack-plugin

**Comment by aholtkamp** [comment]
Hm...Ok, thanks for the suggestions! I think we'll stick with the workaround of using multiple instances of the CopyWebpackPlugin as this also guarantees execution order. Didn't see a bad performance impact for our use case.

**Comment by evilebottnawi** [comment]
@aholtkamp I agree option is suitable solution. But is is very rare use case - add feature easy, maintenance is difficult, also it is increase complex. But if this issue collect many  :+1: and/or :heart: we will reopen issue and implement this feature. Thanks for issue.
