### ISSUE TITLE
4.4.0 & 4.4.1 releases cause error in enhanded-resolve

### ISSUE THREAD

**Issue by wlievens** [webpack-contrib/copy-webpack-plugin#224]
4.4.0 & 4.4.1 releases cause the following error somewhere in the enhanded-resolve libary, when I execute an `ng build`.

```
callbacks[i](err, result);
TypeError: callbacks[i] is not a function
    at Storage.finished (node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:40:15)
    at node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:77:9
    at node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
```

With 4.3.1, this error does not occur. Downgrading in `packages.json` is a functioning workaround.

**Comment by evilebottnawi** [comment]
@wlievens please clean npm cache (`npm cache clear --force`) and install deps again. Thanks!

**Comment by wlievens** [comment]
Thanks, works fine!
