### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by bfred-it** [webpack-contrib/copy-webpack-plugin#225]
I'm using with `copy-webpack-plugin 4.4.1` with `webpack 4.0.0-beta.0` and I get this warning (although it seems to work since #211)

**Comment by michael-ciniawsky** [comment]
This is handled by the compat layer in `webpack` imho. A `option/flag` to disable the warnings would be awesome, but this should also happen in webapck/webpack instead

**Comment by evilebottnawi** [comment]
@michael-ciniawsky `--ignore-deprecation` for webpack will be good

**Comment by michael-ciniawsky** [comment]
Yep, something like that or a sledgehammers `--silent [...options]` mode, since `webpack` can be quite noisy in general sometimes (e.g loader warnings for each file) :)

**Comment by julmot** [comment]
Webpack 4 is now available.

**Comment by michael-ciniawsky** [comment]
Someone can send PR which feature detects `webpack >= v4.0.0` via 

```js
const cb = (...args) => {
}

...

if (compiler.hooks) {
  const plugin = { name: 'CopyPlugin' }
 
  compiler.hooks.someHook.tap(plugin, cb)
} else {
  compiler.plugin('some-hook', cb)
}
```

**Comment by laozhu** [comment]
Webpack 4 supported?

**Comment by evilebottnawi** [comment]
Let's do it in next patch. WIP

**Comment by evilebottnawi** [comment]
Done https://github.com/webpack-contrib/copy-webpack-plugin/pull/234

**Comment by michael-ciniawsky** [comment]
Released in [`v4.4.3`](https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v4.4.3) 🎉

**Comment by puppeteer701vungle** [comment]
I am getting this issue with version 4.6.0 and webpack 4.27.0.

**Comment by mqliutie** [comment]
```
const config = require('./webpack.config');
const plugin = { name: 'ThisIsTest' }
const compiler = webpack(config);
compiler.hooks.failed.tap(plugin, function (stats) {
    console.log('failed')
})
compiler.hooks.compile.tap(plugin, function (stats) {
    console.log('compile')
})
```
There is no console
