### ISSUE TITLE
Watching single files broken on Windows since 4.4.0 because of wrong path separator

### ISSUE THREAD

**Issue by frigus02** [webpack-contrib/copy-webpack-plugin#226]
Since version 4.4.0 watching of single files (`from` is no glob and points to file) is broken on Windows. I tracked it down to [this change](https://github.com/webpack-contrib/copy-webpack-plugin/compare/v4.3.1...v4.4.0#diff-a796a48a9ecbc15f8f48dc347832123eR90). It changes the file path on Windows like this:

```js
// pattern before: { absoluteFrom: 'C:\\code\\notes\\src\\sw.js' }
pattern.absoluteFrom = escape(pattern.absoluteFrom);
// pattern after: { absoluteFrom: 'C:/code\\notes\\src\\sw.js' }
```

The path after the change is registered as a file dependency in webpack. But since it's wrong, webpack does not notice any changes to the file.

**Comment by evilebottnawi** [comment]
@frigus02 can you create minimum reproducible test repo?

**Comment by frigus02** [comment]
Sure, here you go: https://github.com/frigus02/test-copy-webpack-plugin-path-separator

To reproduce, clone on Windows and do:

```
yarn install
yarn start
```

Then change the file `copy.txt`. Webpack will not notice any changes. Try the same on Linux and it works as expected.

**Comment by vsDizzy** [comment]
Changed `from` to glob as a workaround.

**Comment by evilebottnawi** [comment]
@frigus02 Thanks for issue. Confirm. WIP

**Comment by evilebottnawi** [comment]
@frigus02 can you test branch https://github.com/webpack-contrib/copy-webpack-plugin/pull/230?

**Comment by frigus02** [comment]
Thanks @evilebottnawi. I tested the PR and can confirm that it solves the issue on Windows.
