### ISSUE TITLE
[Feature] Only copy file when origin is newer than target on first run

### ISSUE THREAD

**Issue by pamtbaau** [webpack-contrib/copy-webpack-plugin#229]
Is there a way to only copy files when the `from` is newer than the `to`?

**Comment by evilebottnawi** [comment]
@pamtbaau Thanks for issue, duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/169 ?

**Comment by pamtbaau** [comment]
@evilebottnawi Don't think this is a duplicate although they are close...

On each new fresh start of webpack (no watch), files are copied and the origin overwrites the target. I would like changes in the target to be preserved when target is newer then origin. In any case (fresh start of webpack, or a --watch run) I only want the origin to be copied when it is newer than target or target does not exist.

**Comment by evilebottnawi** [comment]
@pamtbaau 
> On each new fresh start of webpack (no watch), files are copied and the origin overwrites the target. I would like changes in the target to be preserved when target is newer then origin.

Not related to copy plugins, it should be done in `webpack` as persistent cache, we just use api webpack https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/writeFile.js#L124, in theory webpack can have cached file and check need output file or not.

And yep duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/169, we just don't close issue just for other people, but we can't do nothing here, But if you have good knowledge you can send PR in `webpack` and solve this PR

**Comment by evilebottnawi** [comment]
@pamtbaau only `webpack` have cached fs and contain original mtime, we can do this inside plugin, but it is overload and decrease perf

**Comment by pamtbaau** [comment]
@evilebottnawi I was under the impression that simply comparing mtime of target and origin would be enough to fix the issue. As said, I don't know the ins and outs of webpack... 

Thanks for your time.

**Comment by evilebottnawi** [comment]
@pamtbaau let's left this open for other people, maybe somebody will find simple and good solution

**Comment by evilebottnawi** [comment]
let's close this in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/169
