### ISSUE TITLE
Won't copy files when there are square brackets [ ] in the path

### ISSUE THREAD

**Issue by flawiddsouza** [webpack-contrib/copy-webpack-plugin#231]
A tiny repo to reproduce the issue:
https://github.com/flawiddsouza/Reproduce-bracket-bug-in-copy-webpack-plugin

Go to each folder & run:
npm install
npm start

The folder without brackets will copy the file "from" to "to" but the one with brackets will not.

**Comment by evilebottnawi** [comment]
@flawiddsouza Can you upgrade to latest version (`npm cache clear --force & npm install`)

**Comment by flawiddsouza** [comment]
Updated. Still broken. The files aren't copied if the path contains square brackets.

**Comment by evilebottnawi** [comment]
@flawiddsouza don't reproduce, what `os` you use?

**Comment by flawiddsouza** [comment]
Windows 10 Version 1709

**Comment by goldenram** [comment]
this happens for me when using regex captures:

`            new CopyWebpackPlugin([
                { from: '../../../src/**/docs/*.md',
                    to: 'docs/[1][name].[ext]', toType: 'template',
                    test: /([^/]+)\/([a-z,0-9]*)\/(\/?$).md/,
                }
            ], {debug: 'debug'}),
`

I am expecting to get files outputted as "dirName-fileName.md" however I am getting instead [1]-fileName.md".

**Comment by marcoqu** [comment]
I have the same issue with regular brackets in the path. I.e. `D:/User/Dropbox (My Company)/project/**/*`

Could it be related to [this issue](https://github.com/sindresorhus/globby/issues/81) in Globby?
See also [this very similar issue](https://github.com/paulmillr/chokidar/issues/300) with globbing and windows folders in Chokidar. They ended up adding a "disable globbing" option.

**Comment by marcoqu** [comment]
Sorry. In my case this has nothing to do with the globbing.
The issue is with path escaping in [escape.js](https://github.com/webpack-contrib/copy-webpack-plugin/blob/6205f516f7dd027a93737bf533a3be36d57602d9/src/utils/escape.js#L11) which escapes characters (the parentheses) that are part actual parts of the path. 
If I remove the parentheses pattern from the regular expression, everything works fine.

**Comment by loveky** [comment]
@goldenram If you are on Windows system. You should use `\` as path separator in your test regexp.

if you want it works on both Windows and Mac/Linux. You can leverage `path.sep`.  So you can try

```js
const path = require('path');
// then
test: new RegExp(`([^/]+)\\${path.sep}([a-z,0-9]*)\\${path.sep}(\\/?$).md`)
```
