### ISSUE TITLE
Hash wrong

### ISSUE THREAD

**Issue by peteringram0** [webpack-contrib/copy-webpack-plugin#237]
when using the [hash] option this seems to generate a unique hash rather then the hash that the rest of webpack uses. Is there a way of getting it to use the same hash as the rest of webpack?

**Comment by evilebottnawi** [comment]
It is expected, because `hash` is hash of file, not webpack build, we can't get `webpack` hash

**Comment by evilebottnawi** [comment]
@peteringram0 all plugins use this logic, anyway feel free to send a PR
