### ISSUE TITLE
How can I use a template to copy files and keep the directory structure

### ISSUE THREAD

**Issue by lewayjack** [webpack-contrib/copy-webpack-plugin#240]
I would like to know how to use a template to copy files and keep the file directory structure, thanks.
### The desired result

├───directory
│   ├───directoryA
│   │   └───a.js
│   │       └───b.js
│   ├───c.js

to

├───directory
│   ├───directoryA
│   │   └───a.hash.js
│   │       └───b.hash.js
│   ├───c.hash.js

### now after use toType:template i got
├───directory
│  └───a.hash.js
│  └───b.hash.js
│   └───c.hash.js

**Comment by evilebottnawi** [comment]
@lewayjack don't use `toType:template`, just use `glob` and set `fromArgs` needed `root` directory

**Comment by lewayjack** [comment]
@evilebottnawi Sorry I may not express myself clearly.
i'd like to: 
1. Copy files from directory A to directory B
2. Add hash value to file names
3. Keep origin folder structure
I do not quite understand how _fromArgs_ adds hash value to the file name
here is my code
```
      new CopyWebpackPlugin([
        {
          from: path.resolve(__dirname, '../app/web/assets/lib'),
          to: 'lib/[name].[hash].[ext]',
          toType: 'template'
        }
      ])
```
now all files are in the lib folder, not their own subdirectory

**Comment by evilebottnawi** [comment]
@lewayjack maybe related https://github.com/webpack-contrib/copy-webpack-plugin/issues/112 ?

**Comment by ioannisNoukakis** [comment]
@lewayjack try lib/[path][name].[hash].[ext]

**Comment by lewayjack** [comment]
@ioannisNoukakis that works,THX
