### ISSUE TITLE
webpack watch mode with CopyWebpackPlugin causes infinite loop

### ISSUE THREAD

**Issue by 1rosehip** [webpack-contrib/copy-webpack-plugin#247]
Hello,
In webpack, CopyWebpackPlugin causes infinite loop when webpack is in watch mode. I tried to add watchOptions.ignored option but it doesn't seem to work. My webpack config is following:

    const config = {

        entry: {
            'res': './src/index.js'
        },
        output: {
            filename: '[name].min.js',
            path: path.resolve(__dirname, 'dist')
        },
        mode: 'production',
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: /(node_modules|bower_components)/,
                    use: {
                        loader: 'babel-loader',
                        options: {
                            presets: ['es2015']
                        }
                    }
                }
            ]
        },

        plugins: [
            new webpack.DefinePlugin({
                'process.env.NODE_ENV': JSON.stringify('production') 
            }),

            new CopyWebpackPlugin([
                { from: 'dist', to: path.resolve(__dirname, 'docs/js') }
            ], {})
        ],

        watchOptions: {
            ignored: path.resolve(__dirname, 'docs/js')
        }
    };

    module.exports = config;

Any help would be appreciated.

**Comment by evilebottnawi** [comment]
@1rosehip can you create minimum reproducible test repo?

**Comment by ianwalter** [comment]
@1rosehip How did you resolve this?

**Comment by ianwalter** [comment]
@evilebottnawi Unfortunately that is out of our control since we use the `bundle-tracker-plugin`. I will explain in more detail on a PR I'm planning to submit today.

**Comment by baconck** [comment]
I was able to solve this with: 
```
  watchOptions: {
    aggregateTimeout: 3000
  }
```
