### ISSUE TITLE
copy-webpack-plugin causes constant compilation when watch is running

### ISSUE THREAD

**Issue by Vitukr** [webpack-contrib/copy-webpack-plugin#250]
I use  webpack --watch in development proccess and need to copy output files to another folder. After including copy-webpack-plugin in configuration file it causes constant compilation, even when I do nothing with any file in project. I see that some css filesconstantly being updated without any my actions. When I delete copy-webpack-plugin from configuration, nothing is updated without my actions and watch works fine.
I need to solve this issue because I need to copy output files also to another folder.

**Comment by evilebottnawi** [comment]
@Vitukr sorry for delay, i.e. because we use `glob`,  we can't know what it added to you file system or not, it is require us run `glob` on every watch build.
