### ISSUE TITLE
Not copy new file in watch mode

### ISSUE THREAD

**Issue by k8w** [webpack-contrib/copy-webpack-plugin#252]
I use 
```
new CopyWebpackPlugin([
    'res/**/*.*'
])
```
and
```
webpack -w --mode=development
```

When watching, if I create a new file (like `res/test.txt`), it would not copy to the output path.
I must restart webpack.

**Comment by k8w** [comment]
@evilebottnawi Here~
https://github.com/k8w/copy-webpack-plugin-issue-252

**Comment by mserajnik** [comment]
Any update on this?

I can confirm the issue (using `webpack@4.8.1` and `copy-webpack-plugin@4.5.1`). It also doesn't work when using [webpack-dev-server](https://webpack.js.org/configuration/dev-server/) instead of watch mode.

**Comment by evilebottnawi** [comment]
When webpack in watch mode, he use `memory-fs` to increase perf and you can't see files in file system when you in watch mode, it is expected. I tomorrow update readme about this. Solution: 
1. https://github.com/webpack/webpack-dev-middleware#writetodisk
2. write-file-webpack-plugin

**Comment by x-yuri** [comment]
@evilebottnawi I've run into it with `webpack-dev-server`. I believe it has to do with it not adding dependencies when `from` is a [glob][1], as opposed to [dirs][2], and [files][3].

[1]: https://github.com/webpack-contrib/copy-webpack-plugin/blob/v4.5.2/src/preProcessPattern.js#L77
[2]: https://github.com/webpack-contrib/copy-webpack-plugin/blob/v4.5.2/src/preProcessPattern.js#L83
[3]: https://github.com/webpack-contrib/copy-webpack-plugin/blob/v4.5.2/src/preProcessPattern.js#L96

The workaround is to, e.g., replace `'assets/**/*'` with `{from: 'assets', to: 'assets'}`.

**Comment by evilebottnawi** [comment]
@x-yuri please create minimum reproducible test repo

**Comment by x-yuri** [comment]
@evilebottnawi Doesn't the one from the [earlier post][1] work for you? It says:

[1]: https://github.com/webpack-contrib/copy-webpack-plugin/issues/252#issuecomment-381013709

> If I add a 3.txt into res, it would not trigger webpack recompile.(watch mode)
