### ISSUE TITLE
loglevel option

### ISSUE THREAD

**Issue by SassNinja** [webpack-contrib/copy-webpack-plugin#257]
I'm deleting my dist folder before every webpack build and use the copy-webpack-plugin to copy all images afterwards.
Since it's quite a lot images I'm also getting many logs in the terminal what is really annoying.

I haven't found an option to disable that.
Would be ok to add a new option for it? (e.g. `loglevel: 'silent'`)

**Comment by evilebottnawi** [comment]
@SassNinja https://github.com/webpack-contrib/copy-webpack-plugin#debug

**Comment by SassNinja** [comment]
@evilebottnawi I'm afraid I don't understand that section or it's not working correctly.

How does the table work?

In the example code it's `{ debug: 'info' }` but in the table 'info', 'debug' and 'warning' are the values. How can they be the key name?
Would have to be `{ info: false, debug: false, warning: false }`.

However it doesn't work for me at all.
No matter what option I define I still see all emitted images in the terminal!
Here's my plugin instance

```javascript
new CopyWebpackPlugin([
    {
        context: 'assets/src/img/',
        from: '**/*',
        to: path.resolve(__dirname, 'assets/dist/img/'),
        ignore: ['*.psd'],
        info: false,
        debug: false,
        warning: false
    }
])
```

**Comment by evilebottnawi** [comment]
@SassNinja please send screenshot what you mean, i don't understand you

**Comment by SassNinja** [comment]
@evilebottnawi here's a screenshot

![webpack-copy-screen](https://user-images.githubusercontent.com/19912475/40408885-59237df4-5e69-11e8-8d82-0f1bf2d9cd7f.jpg)

May seem ridiculous with the three example images but in my project I've got abt 300 images and it's really annoying to see them all the time in the terminal.
An option to hide this output would be great.

**Comment by evilebottnawi** [comment]
@SassNinja please read docs before post issue, it is not related to `copy-webpack-plugin`, in your screenshot stats after building, docs https://webpack.js.org/configuration/stats/.
`stats: { assets: false }`

**Comment by SassNinja** [comment]
Thank you, that's exactly what I needed!

I'll check the docs next time twice before posting 😇
