### ISSUE TITLE
copy-webpack-plugin not executing

### ISSUE THREAD

**Issue by abhishekagg19** [webpack-contrib/copy-webpack-plugin#271]
In my webpack.config.js, I am using custom plugin which is working fine.
      new AEMClientlibWebpackPlugin(require('./clientlib.config.prod.js'))

If I add copy-webpack-plugin after above plugin, then copy operation is not working. if I remove the AEMClientlibWebpackPlugin, the copy operation work.

Could you help in resolving CopyWebpackPlugin execution issue?

Reference: https://www.npmjs.com/package/aem-clientlib-webpack-plugin

**Comment by evilebottnawi** [comment]
@abhishekagg19 please create issue in `AEMClientlibWebpackPlugin`, we use standard webpack api
