### ISSUE TITLE
Copy images when adding a new file

### ISSUE THREAD

**Issue by msacchetti** [webpack-contrib/copy-webpack-plugin#272]
When i add a file to an images folder when using webpack watch, i get a message in the terminal "[Browsersync ]file event [change]: path/image.png" but the file does not get processed/copied to the public directory.

```javascript
/**
   * Common plugins which should run on every build.
   *
   * @type {Array}
   */
  plugins: [
    new webpack.LoaderOptionsPlugin({ minimize: !isdev }),
    new ExtractTextPlugin(config.outputs.css),
    new CleanPlugin(config.paths.public, { root: config.paths.root }),
    new CopyPlugin([{
      context: config.paths.images,
      from: {
        glob: `${config.paths.images}/**/*`,
        flatten: true,
        dot: false
      },
      to: config.outputs.image.filename,
    }]),
  ]
}
```

This is what runs
```javascript
    "scripts": {
        "development": "cross-env NODE_ENV=development webpack --progress --hide-modules --config build/webpack.config.js",
        "watch": "npm run development -- --watch && webpack-dev-server --progress --colors"
    },
```

Is there a way to do this? Thanks

**Comment by evilebottnawi** [comment]
@msacchetti not related to `copy-webpack-plugin`, when you use `watch` webpack use memoryFS (keep all in memory and write new assets also in memory) and don't write files to disk, use https://github.com/gajus/write-file-webpack-plugin when some files should be written on disk.
