### ISSUE TITLE
No recompile / reloading  when  dev server use

### ISSUE THREAD

**Issue by isergey** [webpack-contrib/copy-webpack-plugin#276]
When CopyWebpackPlugin is enabled, dev server stops recompiling. Help please!

**Comment by evilebottnawi** [comment]
@isergey What? Without configuration/reproducible test repo i can't help

**Comment by isergey** [comment]
This is test repo https://github.com/isergey/cwp-test

> node -v
v10.6.0
> npm -v
6.2.0

> npm i
> npm start
And try to chage src/index.ts

Thank you!

**Comment by isergey** [comment]
Oh my godness. I put this option to webpack config and recompiling was started...
watchOptions: {
  poll: true
}

**Comment by evilebottnawi** [comment]
@isergey do you build locally? Also provide your os information

**Comment by isergey** [comment]
I increased max_user_watches from 8192 to 524288 and it worked

**Comment by evilebottnawi** [comment]
@isergey Can you send a PR to readme about this?

**Comment by isergey** [comment]
I think it is more about webpack watching problem.
