### ISSUE TITLE
The plugin should throw an error, if "from" is empty string

### ISSUE THREAD

**Issue by Deliaz** [webpack-contrib/copy-webpack-plugin#278]
Hey guys. 
I spent hours trying to find a reason of weird behavior in my project, but it seems that `copy-webpack-plugin` takes the content of latest-processed file in case if **from** is an empty string, and put it inside the "to:" file. 
I think in such case the plugin should throw an error or show warning at least. 
As I checked in the plugin source, it is related to the wrong path resolving. 

Versions: 
* Webpack: 4.16.2
* copy-webpack-plugin: 4.5.2

Here is the example: 
**webpack.config.js**
```
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const config = {
	entry: './index.js',

	plugins: [
		new CopyWebpackPlugin([
			{
				from: '',
				to: './test.json'
			}
		]),
	]
};

module.exports = config;
```

**index.js**
```
console.log('Content from index.js');
```

Webpack run result: 
```
$ ./node_modules/.bin/webpack --mode=development
Hash: 73063a824e1b7c5d19e1
Version: webpack 4.16.2
Time: 1781ms
Built at: 2018-07-26 17:34:11
      Asset      Size  Chunks             Chunk Names
    main.js  3.78 KiB    main  [emitted]  main
./test.json  37 bytes          [emitted]  
Entrypoint main = main.js
[./index.js] 37 bytes {main} [built]
```

After the build content of **test.json** will be: 
```
console.log('Content from index.js');
```

**Comment by evilebottnawi** [comment]
@Deliaz Thanks for issue
