### ISSUE TITLE
Execute the file copying on a compilation hook

### ISSUE THREAD

**Issue by Hamada14** [webpack-contrib/copy-webpack-plugin#282]
I wanted to ask whether there exist a blocker to actually copying the files using `compiler.hooks.compilation` instead of `compiler.hooks.emit`.

### Reasoning behind the suggestion
1. Files, which contains a hash in their file names, can be listed in a manifest and inlined in one of the source file in this process.
2. Trying to inline a file using a plugin similar to [html-webpack-inline-source-plugin](https://github.com/DustinJackson/html-webpack-inline-source-plugin) would require that the file be placed in the compilation hook or earlier.

**Comment by evilebottnawi** [comment]
@Hamada14 Historical reason, we can change this in future major release, but we should discussion about this to avoid breaks some cases

**Comment by evilebottnawi** [comment]
We should use `additionalAssets` hook for copying

**Comment by evilebottnawi** [comment]
When wepback@5 was released we should migrate on this hook

**Comment by evilebottnawi** [comment]
Done in master, now we use `compilation.additionalAssets` hook
