### ISSUE TITLE
Copy before rest of build process?

### ISSUE THREAD

**Issue by martixy** [webpack-contrib/copy-webpack-plugin#286]
I have a build dependency which needs to be copied over before the project can be built.

Currently the build fails, as it seems the plugin is running AFTER the rest of the build process.

Is there a setting, or something that would make the copy happen before the build?

My use case is a (not sure how well known in js-land) pattern of having a `config.json.dist`, which contains default values and having your build process create / merge new config options to `config.js`, which itself is gitignored.

Edit: Issue seems similar to this: https://github.com/webpack-contrib/copy-webpack-plugin/issues/195
But I'm not sure of exactly identical. Though the solution he offered will probably help.
Though it is kind of ironic that I have to use the copy plugin to process some data and not be able to do it to actually copy a file.

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/195

**Comment by martixy** [comment]
Achieved this on my end with event hooks (like in 195).

But I still find it delightfully ironic that something named **Copy**WebpackPlugin doesn't actually **Copy** things. Like... what went wrong there?

**Comment by evilebottnawi** [comment]
@martixy What do you mean?

**Comment by marcelo2605** [comment]
@martixy could you share your solution?

**Comment by martixy** [comment]
@marcelo2605 My solution goes like this:

```js
new EventHooksPlugin({
    compile: () => {
        console.log('Copying config.');
        if (!fs.existsSync(path.resolve(__dirname, 'config/config.json'))) {
            fs.copyFileSync(
                path.resolve(__dirname, 'config/config.json.dist'),
                path.resolve(__dirname, 'config/config.json')
            )
        } else {
            console.log('config.json exists, skipping copy.');
        }
    }
}),
```

@evilebottnawi What I mean is that I have to use the above approach instead of this:
```js
{
    from: path.resolve(__dirname, 'config/config.json.dist'),
    to: path.resolve(__dirname, 'config/config.json'),
    force: false
}
```
because not only does the build process fail if it depends on the `to` file, but even if it did not fail, the to-file is overwritten if it exists, even though `force` is set to false. So yes, the irony is still going strong...
