### ISSUE TITLE
Doesn't preserve original name in assets-manifest in case of using template with placeholders

### ISSUE THREAD

**Issue by budarin** [webpack-contrib/copy-webpack-plugin#288]
I have to copy file with hash in dist folder
```js
{ from: './src/common/myfile.txt', to: '[hash].[ext]' },
```
after bundling in `assets-manifest.json` we have:
```js
"83e7b321450bbcdc5013d2822838febc.txt": "/83e7b321450bbcdc5013d2822838febc.txt",
```
instead of
```js
"myfile.txt": "/83e7b321450bbcdc5013d2822838febc.txt",
```

**Comment by evilebottnawi** [comment]
@budarin duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/104, also please provide what plugin you use in this link, thanks for issue
