### ISSUE TITLE
Add support [contenthash] for copied files

### ISSUE THREAD

**Issue by donskov** [webpack-contrib/copy-webpack-plugin#291]
Hi guys!

Is there an option to add `[contenthash]` formatting for copied files?
I want to use:
```js
[
  new CopyWebpackPlugin([
    {
      from: 'src/',
      to: 'dest/[name].[contenthash:8].[ext]',
    },
  ]),
]
```
Webpack example: https://webpack.js.org/guides/caching/#output-filenames

Thanks!

**Comment by evilebottnawi** [comment]
@donskov we use `loader-utils` to interpolate filename, here issue about `[contenthash]` https://github.com/webpack/loader-utils/issues/112, feel free to send a PR :+1:

**Comment by donskov** [comment]
@evilebottnawi Thank you!
