### ISSUE TITLE
How can I copy files from a directory without it creating the whole source structure?

### ISSUE THREAD

**Issue by charliedavison** [webpack-contrib/copy-webpack-plugin#293]
I'm trying to use CopyWebpackPlugin to copy some files out of my node_modules folder and into my build folder.

   
 ```
new CopyWebpackPlugin([
      { from: 'node_modules/accounting/**', to: 'vendor/npm/' },
      { from: 'node_modules/angular/**', to: 'vendor/npm/' },
```

I would expect this to output to my build folder ```/build/vendor/npm/accounting``` and ```build/vendor/npm/angular``` respectively, but instead a ```node_modules``` folder is created - the files are actually outputted to ```build/vendor/npm/node_modules/accounting```.

How can I prevent the node_modules folder being created and get my expected output?

**Comment by EdBoucher** [comment]
If you check out the branch referenced in this PR you can add a `transformPath` function to get the files into the right directory: https://github.com/webpack-contrib/copy-webpack-plugin/pull/284

**Comment by bjbrewster** [comment]
For anyone else coming here from Google, `transformPath` is not in latest Webpack CopyWebpackPlugin. You would instead use the `context` arg like this:

```
      { context: 'node_modules/', from: 'accounting/**/*', to: 'vendor/npm/' },
```
