### ISSUE TITLE
Constant recompile when copying a file from the root of directory. 

### ISSUE THREAD

**Issue by ThrowsException** [webpack-contrib/copy-webpack-plugin#297]
I updated to 4.5.3 and when I run my webpack dev server it just keeps recompiling. Installing 4.5.2 makes the issue go away. What info can I provide to help track down the issue?

**Comment by ThrowsException** [comment]
I think I'm running into the issue described here https://github.com/webpack-contrib/copy-webpack-plugin/pull/296

**Comment by ThrowsException** [comment]
Can confirm. Im running into the issue described with #296. I have a file in the root of my directory that I copy to a dist folder which then puts my entire project under watch and constantly recompiles.

**Comment by Jmenache** [comment]
I'm having the same issue when upgrading to 4.5.3
It most likely comes from the commit 5fa69db, the modification in `src/processPattern.js` line 33 to 38.

I also confirm what @ThrowsException found.
When I stop trying to copy files from the root of my directory (still copying others from other sources) it works as expected.

**Comment by ThrowsException** [comment]
@evilebottnawi I checked this morning on my project and it looks like its working.

**Comment by ThrowsException** [comment]
@evilebottnawi https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v4.5.4 resolves the issue. Thanks.
