### ISSUE TITLE
transformPath not working

### ISSUE THREAD

**Issue by crazyx13th** [webpack-contrib/copy-webpack-plugin#305]
Hey there,

I want to  modify the filenames when i copy my files. 'transform' is working, but 'transformPath' not

![grafik](https://user-images.githubusercontent.com/8912561/47737590-8bd1d580-dc71-11e8-8434-e06900457bd3.png)
I see the logs at compiling!

![grafik](https://user-images.githubusercontent.com/8912561/47737708-c6d40900-dc71-11e8-94a8-13669433ad75.png)
NO logs... (I tried a lot of combinations...)

and... small copy&paste mistake at docs:
![grafik](https://user-images.githubusercontent.com/8912561/47737791-ff73e280-dc71-11e8-8ffb-baa7a1c5dc32.png)

thanks!

Greetings
crazyx13th

**Comment by evilebottnawi** [comment]
Because it has not yet been published

**Comment by crazyx13th** [comment]
mhh, ok. thx

my current workaround
![grafik](https://user-images.githubusercontent.com/8912561/47739886-b5413000-dc76-11e8-93af-49247ad7ca32.png)

**Comment by awps** [comment]
> Because it has not yet been published

It's more than 2 years and still not working? Why it has been removed? 
In version 5 it was working but in version 7 not.
