### ISSUE TITLE
_iteratorError

### ISSUE THREAD

**Issue by NiceOkay** [webpack-contrib/copy-webpack-plugin#306]
Hello, i use copy-webpack-plugin into my custom plugin. 
When i use new CopyWebpackPlugin(options).apply(compiler), i get _iteratorError;

<img width="1164" alt="screen shot 2018-11-10 at 7 44 07 pm" src="https://user-images.githubusercontent.com/44927185/48303867-3921d480-e521-11e8-9ab9-d5be6dbc96a7.png">

**Comment by evilebottnawi** [comment]
@NiceOkay can you create minimum reproducible test repo?

**Comment by NiceOkay** [comment]
use webpack 4
`
const { AsyncParallelHook } = require('tapable');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = (config) => {
  class TaskStyleLibs {

    constructor() {
      this.TASK = config.TASK_STYLE_LIBS;
      this.options = [];
    }

     // get pattern for copy
    getFiles() {
        this.options.push(...);
    }

    apply(compiler) {
            if (compiler.hooks[this.TASK.HOOK]) throw new Error('Already in use');
            compiler.hooks[this.TASK.HOOK] = new AsyncParallelHook(['compilation']);
            compiler.hooks[this.TASK.HOOK].tapPromise(this.TASK.NAME, (compilation) => {
                return new Promise((resolve) => {

                    this.getFiles();

                    if (this.options.length > 0) {
                         new CopyWebpackPlugin(this.options).apply(compiler);
                    }
                    resolve();

                });
            });
    }
  }
};
`

**Comment by evilebottnawi** [comment]
Expected, don't run plugin inside plugin, it is impossible

**Comment by NiceOkay** [comment]
Ты из России?

**Comment by NiceOkay** [comment]
Ok. Why this is work, else don't run plugin inside plugin???

`
    apply(compiler) {
        if (compiler.hooks[this.TASK.HOOK]) throw new Error('Already in use');
        compiler.hooks[this.TASK.HOOK] = new AsyncParallelHook(['compilation']);
        compiler.hooks[this.TASK.HOOK].tapPromise(this.TASK.NAME, (compilation) => {
            return new Promise((resolve) => {

                this.getFiles();

                if (this.options.length > 0) {
                     new MyCustomPlugin(this.options).apply(compiler);
                }
                resolve();

            });
        });
  }
`

MyCustomPlugin code:
`
    class MyCustomPlugin {

      constructor(options) {
          this.options = options;
      }

      apply(compiler) {
          compiler.hooks.afterEmit.tapAsync('MyCustomPlugin', (compilation, cb) => {
            console.log(compilation.fileDependencies);
            cb();
          });
      }

    }
`

**Comment by evilebottnawi** [comment]
Due webpack architecture, if you think what it should be supported, better create issue in wepback, we can't do here
