### ISSUE TITLE
Doesn't copy files after a compilation error

### ISSUE THREAD

**Issue by wcastand** [webpack-contrib/copy-webpack-plugin#307]
I'm using nextjs as a base and extending the webpack config with this : 
```javascript
const { join, resolve } = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin')
const WatchExternalFilesPlugin = require('webpack-watch-files-plugin').default

const { transform } = require('./utils')

const config = require('./config')
const internalNodeModulesRegExp = /src(?!\/(?!.*js))/
const stories_dir = resolve(config.stories_dir)

module.exports = {
  webpack: (webpackConfig, { dev, defaultLoaders }) => {
    defaultLoaders.babel.options.plugins = ['babel-plugin-macros']
    webpackConfig.module.rules.push({
      test: /\.+(js|jsx)$/,
      use: defaultLoaders.babel,
      include: [internalNodeModulesRegExp],
    })
    webpackConfig.module.rules.forEach(mod => {
      mod.include.push(config.webpack.include)
    })
    webpackConfig.plugins.push(
      new CopyWebpackPlugin([{ from: stories_dir, to: resolve('./.bonsai/pages/'), transform }]),
      new WatchExternalFilesPlugin({ files: [join(stories_dir, '**/*')] }),
    )

    return webpackConfig
  },
}

```

Everything is working except when i get a error at compile time, after the compile error, the files are not copied anymore and webpack doesn't recompile.

The watch plugin seems to still works since i have an update in my terminal timestamp but the copy doesn't work so the error is never resolved.

Only the file copied are blocking the recompile time, when i make an error on a non copied files, the recompile is working properly and rerender the app correctly.

the transform function is update the path in the copied files to take into account the new directory (for example) : 

```javascript
// from 
import MyComponent from '../c/comp'
// to
import MyComponent from '../../c/comp'
```

**Comment by wcastand** [comment]
https://github.com/wcastand/error-copy

It doesn't work for me in this repo. 
Like explained in README.md

if you change the `src/hello.js`it will update correctly until you make an error (like not closing html tags)

**Comment by wcastand** [comment]
You liked my post but didn't take the label out, did we still miss something in the issue ?

Best,
wcastand

**Comment by evilebottnawi** [comment]
@wcastand sorry, don't have time on all issue, feel free to investigate why it is happens and left feedback

**Comment by wcastand** [comment]
Oh no problem, i was mostly asking to be sure i didn't miss anything. Of course, we all have life and we all take the time when we have it, no problem with that. sorry if it passed for impatience,

**Comment by wcastand** [comment]
So i fork the repo and try to use the local version on the reproducible repo and it works fine.
Is there any difference between the npm version and the master branch on github ?

**Comment by evilebottnawi** [comment]
@wcastand no difference between npm and master version, maybe problem in other plugins

**Comment by evilebottnawi** [comment]
@wcastand something wrong in `next` repo, i reproduce problem with you example, but can't reproduce without `next` so problem i think in `next`, also i have problem with hangs compilation without `CopyWebpackPlugin`

**Comment by evilebottnawi** [comment]
@wcastand can't reproducible, maybe you use old version `copy-webpack-plugin`?

**Comment by wcastand** [comment]
It was a while ago so maybe it's working now. I stop this project a while ago, lot of issues about it i couldn't fix lol

I think we can close unless someone else got this problem too
