### ISSUE TITLE
isGlob return false for windows path with backslashes

### ISSUE THREAD

**Issue by VdustR** [webpack-contrib/copy-webpack-plugin#317]
As the case we have `pattern.from = 'C:\my-repo\{manifest,manifest}.json'` in windows and `pattern.from = '/my-repo/{manifest,manifest}.json'` in linux. 

https://github.com/webpack-contrib/copy-webpack-plugin/blob/adf10462cf04b75a8ad59a42ceacf3b033850a8a/src/preProcessPattern.js#L67

It returned `true` in linux but returned `false` in windows because of https://github.com/micromatch/is-glob/issues/10.

Tried:
```node
> require('is-glob')('C:\\{foo,bar}.js')
false
> require('is-glob')('/{foo,bar}.js')
true
```

I also tried `is-glob@2.0.1` and got `true` in both cases.

Any idea to make it works in Windows? Thanks!

https://github.com/egoist/poi/issues/533

**Comment by evilebottnawi** [comment]
@VdustR let's wait answer from `is-glob`, don't  think what we can fixed it on our side

**Comment by evilebottnawi** [comment]
Won't fix https://github.com/micromatch/is-glob/issues/9, feel free to send a PR with workaround

**Comment by evilebottnawi** [comment]
Of somebody can find workaround PR welcome
