### ISSUE TITLE
[Feature] Add order option

### ISSUE THREAD

**Issue by Scharnvirk** [webpack-contrib/copy-webpack-plugin#318]
Hello,

In a project I am developing, I have an issue with copying files with the same name from multiple sources.

Configuration of copy webpack plugin is as follows:
```
new CopyWebpackPlugin([
            { from: 'node_modules/engine/static', test: /\.(css|html|png)$/, force: true },
            { from: 'node_modules/subengine/static', test: /\.(css|html|png)$/, force: true },
            { from: './static', test: /\.(css|html|png)$/, force: true },
        ]),
```

The project has two dependencies, let's call them `engine` and `subengine`. They are both bundled within node_modules.

Each of these has its own graphical assets. In case the file with an exact same name and path is in more than one repo, then one from "project" is more important than one from `subengine`, and one from `subengine` is more important than file from `engine`. 

Let's say each of these contains an `abc.png` file in its own `static` folder. The intended result is to have `abc.png` come from projects's own `./static` folder, but it instead, the one from `subengine` is used.

HOWEVER.... which is where the fun begins...

If I do this:
```
new CopyWebpackPlugin([
            { from: 'node_modules/engine/static', test: /\.(css|html|png)$/, force: true },
            { from: 'node_modules/subengine/static', test: /\.(css|html|png)$/, force: true },
            { from: './static', test: /\.(css|html|png)$/, force: true },
        ], {debug: 'debug'}),
```

...then the order is correct, and `abc.png` is taken from project's `static` folder.

This might be random behavior and just a coincidence, but it really seems having debug on fixes the issue every time. 

I am using:
`"webpack": "~4.17.2",` (I would like not to update further for now because then the build breaks elsewhere)
`"copy-webpack-plugin": "^4.6.0",`

Build on Windows 10, Node 8.4.0

**Comment by evilebottnawi** [comment]
> HOWEVER.... which is where the fun begins...

Just luck

**Comment by Scharnvirk** [comment]
Thanks. 

It really seems consistent. We have automated tests and builds and it passes every time since I added the debug flag.

Is there any way to make this work "as intended" however? What other solution could I use if copy webpack plugin does not have ordering functionality?

**Comment by evilebottnawi** [comment]
> Is there any way to make this work "as intended" however?

It is already work as intended.

> Is there any way to make this work "as intended" however? What other solution could I use if copy webpack plugin does not have ordering functionality?

Implement this. 
Package what can help with this https://github.com/sindresorhus/p-queue.
We need add `order` property on each `item` (by default undefined) then order their based on `order` value (lower value is has high priority) and run queue.
