### ISSUE TITLE
Treat [hash] and [contenthash] correctly

### ISSUE THREAD

**Issue by rudionrails** [webpack-contrib/copy-webpack-plugin#349]
* Operating System: OSX
* Node Version: 11.3
* NPM Version: 6.7.0
* webpack Version: 4+
* copy-webpack-plugin Version: 5.0.0

### Feature Proposal

I would like to treat `[hash]` and `[contenthash]` correctly in the file/directory string. This is related to [this](https://github.com/webpack-contrib/copy-webpack-plugin/issues/237) issue, but [other](https://github.com/webpack-contrib/mini-css-extract-plugin) [packages](https://github.com/jantimon/html-webpack-plugin) have already implemented this accordingly. PR will follow shortly - looking forward to feedback.

### Feature Use Case

Keeps handling consecutive builds separated. Mostly used to move files into a common sub-directory:

```
d41d8c/main.js
d41d8c/index.html
ax798f/main.js
ax798f/index.html
```

**Comment by evilebottnawi** [comment]
@rudionrails What do you mean Treat [hash] and [contenthash] correctly? `contenthash` is `hash` of content and it is already works as expected, `hash` is deprecated and will be removed in next version in `webpack` and in plugin, it is for backward compatibility

**Comment by evilebottnawi** [comment]
Also solution here https://github.com/rudionrails/copy-webpack-plugin/commit/ef2b2df6bf09b9f20fdfc1f7585cc4c4aceca21e is invalid and broken long term cache in some cases

**Comment by evilebottnawi** [comment]
Just information for generate hash/contenthash respect `loaderUtils.interpolateName`

**Comment by rudionrails** [comment]
@evilebottnawi thanks for the swift response. Where can I find that [hash] will be deprecated in webpack? I did not find this.

**Comment by rudionrails** [comment]
To my knowledge, this has just been added in v4-alpha https://webpack.js.org/configuration/output/#outputhashfunction

**Comment by rudionrails** [comment]
Also, loader-utils cannot handle it, as it has no access to webpack `compilation`, hence it is added inside this repo. I made a comment in the code about this.

**Comment by evilebottnawi** [comment]
@rudionrails we should fix it in `loader-utils` not here, no public information about `[hash]` right now, but many docs already use `[contenthash]`. Relevant issue https://github.com/webpack/webpack/issues/8535, we should implement support `hash*` options in `loader-utils`, no need hack here, feel free to send a PR to `loader-utils`, it should be easy

**Comment by evilebottnawi** [comment]
Here place for feature https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L96

**Comment by rudionrails** [comment]
I was already working through the loader-utils package - I wanted to initially add it there also. You have any idea how I can get webpack's compilation options into this? Currently, loader-utils does not have this information and is somewhat agnostic to webpack

**Comment by rudionrails** [comment]
Also, it would mean adding webpack as dependency into loader-utils in order to use `webpack.util.createHash`, etc

**Comment by evilebottnawi** [comment]
@rudionrails 

> I was already working through the loader-utils package - I wanted to initially add it there also. You have any idea how I can get webpack's compilation options into this? Currently, loader-utils does not have this information and is somewhat agnostic to webpack

How we should solve this:

- Pass `hash*` options like `interpolateName(context, name, { hashDigest: compilation.hashDigest,  hashDigestLength: compilation.hashDigestLength })`.
- looks `webpack.util.createHash` exists and use their otherwise use built-in hasher for backward compatibility (respect `hash*` options)

**Comment by rudionrails** [comment]
Makes sense, I'll look into it. Nonetheless, this potentially breaks backwards compatibility for all packages depending loader-utils. From your above answer, I take it that you are fine with it?

**Comment by evilebottnawi** [comment]
@rudionrails we already need release `2` version, so it is normal

**Comment by evilebottnawi** [comment]
Feel free to send a PR

**Comment by rudionrails** [comment]
👍

**Comment by evilebottnawi** [comment]
Let's keep open as upstream

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/574
