### ISSUE TITLE
instanceof doesn't work as expected

### ISSUE THREAD

**Issue by HaNdTriX** [webpack-contrib/copy-webpack-plugin#357]
* Operating System: macOS Mojave (10.14.3)
* Node Version: v8.11.4
* NPM Version: 5.6.0
* webpack Version: ^4.12.0
* copy-webpack-plugin Version: 5.0.1

### Expected Behavior

A new instance of CopyPlugin should be an instance of CopyPlugin.

### Actual Behavior

A new instance of CopyPlugin is not an instance of CopyPlugin.

### Code

```js
const CopyPlugin = require('copy-webpack-plugin')
(new CopyPlugin()) instanceof CopyPlugin
```

### How Do We Reproduce?

1. Create a empty test directory
2. Run `npm i copy-webpack-plugin``
3. Run `node`
4. Execute the code above

### Motivation

Many webpack based Frameworks allow the user to customize a webpack config via a reducer pattern (e.g.: [next.js](https://github.com/zeit/next.js/#customizing-webpack-config))

Users can filter though the `webpack.plugins` and add, remove or reconfigure plugins before the actual webpack `compile` step.
Therefore it is important that it is possible to detect instances of this plugin. 

**Example:** `next.config.js`

```js
const CopyPlugin = require('copy-webpack-plugin')
module.exports = {
  webpack (config, options) {
    // Remove Copy logic
    config.plugins = config.plugins.filter(plugin => !(plugin instanceof CopyPlugin))
    return config
  }
}
```

[docs](https://github.com/zeit/next.js/#customizing-webpack-config)

Currently there is no way to do that with this plugin since an instance of it is just a plain object with an `apply` method. I bet babel transforms this code in a wrong way.

**Comment by evilebottnawi** [comment]
We use standard plugin pattern for webpack, where is documentation what it should be work as you written above?

**Comment by evilebottnawi** [comment]
Any way it is works as expected:
```
const CopyPlugin = require('copy-webpack-plugin')

console.log((new CopyPlugin()) instanceof CopyPlugin); // return true
```

Looks you use old version of plugin (`v4` or below)

**Comment by HaNdTriX** [comment]
Sorry for the inconvenience. I was loading an old version from a linked package.
Thanks for looking into it ❤️ !
