### ISSUE TITLE
Windows: Copied files are not watched properly

### ISSUE THREAD

**Issue by fefrei** [webpack-contrib/copy-webpack-plugin#358]
* Operating System: Windows 10, 64 Bit
* Node Version: `v10.15.3`
* NPM Version: `6.7.0`
* webpack Version: `4.29.6`
* copy-webpack-plugin Version: `5.0.1`

### Expected Behavior

When running `webpack-dev-server` and updating a file copied by the `copy-webpack-plugin`, a rebuild should be triggered.

### Actual Behavior

Nothing happens.

### Code

Here's a minimal sample project: [webpack-copy-plugin-mwe.zip](https://github.com/webpack-contrib/copy-webpack-plugin/files/2983422/webpack-copy-plugin-mwe.zip)

### How Do We Reproduce?

Unzip the project provided above. Be on Windows. Run `npm ci`. Run `npm run serve`. Edit `index.html`. No rebuild is triggered.

### Additional Notes

This problem is specific to Windows, and to `copy-webpack-plugin` version 5. Running `webpack` within the Linux subsystem, or downgrading to version `4.6.0`, fixes the issue.
Moreover, the problem is specific to this plugin – editing `app.js` in my example does trigger a rebuild.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/347

**Comment by evilebottnawi** [comment]
Do you use `windows 8`?

**Comment by evilebottnawi** [comment]
Thanks for repository, reproduce
