### ISSUE TITLE
Allow to set the output directory

### ISSUE THREAD

**Issue by jrbarnard** [webpack-contrib/copy-webpack-plugin#367]
### Feature Proposal

Add an option for specifying the output you want the copy to take place in.
This could either be a full path, or relative to the output directory. Maybe useful to have exclude / include too?

E.g:
```
new CopyWebpackPlugin([
    {
        from: 'somedirectory',
        to: 'anotherdirectory',
        output: 'output-one'
    },
    {
        from: 'testdirectory',
        output: {
            exclude: [...],
            include: [...]
        }
    }
]);
```

### Feature Use Case

When you have multiple entries & outputs the copy webpack plugin copies to all, I want conditional copies dependent on the entry, if there is another way to achieve this without changing the copy webpack plugin code please let me know.

**Comment by evilebottnawi** [comment]
Use `ignore` option

**Comment by evilebottnawi** [comment]
Also plugins doesn't depend on count of entry

**Comment by jrbarnard** [comment]
Doesnt the ignore option ignore files to copy as opposed to directories to output too?

I've got multiple entries defined in webpack which are outputting to multiple different output files.

These correspond to different lambda functions.

One of the lambda functions requires a local binary of chromium however the others do not, I want to copy the binary from my node_modules directory into the relevant output directory for that lambda function but not the others (as it is pretty large).

Does that give more context for the use case?

**Comment by evilebottnawi** [comment]
@jrbarnard Please provide example on files and requested feature, example:

Files

```
/path/to/file
/path/to/other/file
```

And describe here what you want copy and where you want copy. 

It is really hard to understand what you want to do.

> I've got multiple entries defined in webpack which are outputting to multiple different output files.

Plugin doesn't work with entries

**Comment by jrbarnard** [comment]
A simplified directory structure is:

Generated from webpack config (ts-loader,babel-loader)
/.webpack/functionOne/index.js
/.webpack/functionTwo/index.js

Source
/src/functionOne/index.ts
/src/functionTwo/index.ts
/node_modules/chromium/bin/binaryfile

I am trying to get
/node_modules/chromium/bin/binaryfile
to copy to
/.webpack/functionTwo/bin/binaryfile
But not to the other output directory.

At the moment I can't specify which to ignore/include so I get it copying to both:
/.webpack/functionOne/bin/binaryfile
/.webpack/functionTwo/bin/binaryfile

I had a quick dig into copy webpack plugin and when it runs it does receive contextual info we can use, I was thinking we can use that to do some exclusion/inclusion rules. I'm happy to do the dev for it.

**Comment by evilebottnawi** [comment]
Why don't use:

With `output: .webpack`.

```
{
        from: 'node_modules/chromium/bin/binaryfile',
        to: 'functionTwo/bin/binaryfile'
}
```
?

**Comment by jrbarnard** [comment]
Hi @evilebottnawi 

I tried that before however it's a relative path and so you just get a nested path.
The same occurs with transformPath.

Thanks,
James

**Comment by evilebottnawi** [comment]
@jrbarnard relative? Don't user absolute paths, it is supported but very dangerous. I still can't understand what you mean. Why answer about not working.

**Comment by jrbarnard** [comment]
I was referring to relative paths.
They don't work in the way you suggested. It just nests them within all output directories

**Comment by evilebottnawi** [comment]
> They don't work in the way you suggested. It just nests them within all output directories

Please provide minimum reproducible test repo, looks you just have invalid configuration or do not understand how this should work

**Comment by jrbarnard** [comment]
Hi @evilebottnawi 
I've just had a chance to put together a test repo now I'm out of work, I think there was some module conflict as I'm using serverless webpack which does some additional bundling and seems to get in the way of the 'to' option on copy webpack plugin.
I've created a separate repo without serverless to recreate the issue and it's doable with the 'to' option. 

Sorry for wasting you time!
