### ISSUE TITLE
cacheDir parameter?

### ISSUE THREAD

**Issue by trkaplan** [webpack-contrib/copy-webpack-plugin#370]
I use cache feature.
I had to change the cache directory other than the default one; `/node_modules/.cache`
There is a check in the source code for `globalRef.cacheDir` but I am not sure how to enable this?

I tried to add `cacheDir` param to webpack config but It didnt't work.

For now I solved my problem by modifying `postProcessPattern`.

Is it possible to use a custom cache directory path without modifying the source code?

* Operating System: Windows 
* Node Version: v11.11.0
* NPM Version: 6.7.0
* webpack Version: 3.10.0
* copy-webpack-plugin Version: 4.3.1

**Comment by evilebottnawi** [comment]
We need option for this, feel free to send a PR
