### ISSUE TITLE
Don't copy new static files if dev-server already running

### ISSUE THREAD

**Issue by Badalik** [webpack-contrib/copy-webpack-plugin#377]
Is it possible to watch changes in static files? For example i'm copy new files to folder for static files, but compilation not running, and new static files don't fall to dist, need to restart.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by Badalik** [comment]
@evilebottnawi  I did not understand you. Which template?
