### ISSUE TITLE
Version 5.0.0 doesn't stop running when using webpack watch

### ISSUE THREAD

**Issue by itaynoama** [webpack-contrib/copy-webpack-plugin#379]
* Operating System: MacOS Mojave 10.14.4
* Node Version: v11.6.0
* NPM Version: 6.9.0
* webpack Version: 4.29.6
* copy-webpack-plugin Version: 5.0.0

### Expected Behavior

After running the command 'npm run build:watch' it generated the files and when the copy plugin finished, it need to wait to any change that i will do and after that generate the files again.

### Actual Behavior

After running the command 'npm run build:watch' it generated the files and when the copy plugin finished, it runs again without making any change.
 
### My solution

Downgrade to version 4.5.2 will solve the problem.

**Comment by evilebottnawi** [comment]
I don't know what your `npm run build:watch` is doing, so i can't help

**Comment by evilebottnawi** [comment]
Also please use latest version of plugin - `5.0.3`
