### ISSUE TITLE
Could not find a matching event to end plugins error at scss compiling

### ISSUE THREAD

**Issue by KirillYoYo** [webpack-contrib/copy-webpack-plugin#403]
have a error in console: "Could not find a matching event to end plugins Object/Compiler/afterEmit { id: 3463 }" then i try change "z-index" property in scss file...
Like this issue:
https://github.com/webpack-contrib/copy-webpack-plugin/issues/243

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Maybe you use old webpack version
