### ISSUE TITLE
copy files and dump its content into one file

### ISSUE THREAD

**Issue by kakarlus** [webpack-contrib/copy-webpack-plugin#404]
Hello Everyone,

is it possible to copy all my svgs and transform it's content (string manipulations) and dump all of it in a file like below?

i've tried but it's only copying one file.

```
new CopyPlugin([
            {
                from: './source/assets/img/svgs/*.svg',
                to: './svg.css',
                toType: 'file',
                transform(content, path) {
                    return encodeURI(content);
                }
            }
        ])
```

thanks in advance,
Carlos

**Comment by evilebottnawi** [comment]
Do you mean merge all in one file (https://github.com/webpack-contrib/copy-webpack-plugin/issues/154)? You can already transform file content using `transform` option

**Comment by kakarlus** [comment]
that's exactly what i tried with the above code, but the resulting content of my file only has 1 svg in it, instead of having all the svgs from the folder

**Comment by evilebottnawi** [comment]
No right now, but you can send a PR, mark as duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/154
