### ISSUE TITLE
`from` does not respect provided globe pattern

### ISSUE THREAD

**Issue by dNitro** [webpack-contrib/copy-webpack-plugin#408]
- Operating System: Mac OS X
- Node Version: 12.12.0
- NPM Version: 6.12.1
- webpack Version: 4.41.2
- copy-webpack-plugin Version: 5.0.4

`from` does not respect provided globe pattern and also copies the wrapper folder.

### Expected Behavior
With provided `webpack.config.js` and the following plugin config:
```js
{
  from: 'public/**/*',
  to: 'build'
}
```
the following final structure is expected:
```
.
├── favicon.ico
├── index.html
├── main.js
└── site.webmanifest
```
### Actual Behavior
but the output structure is:
```
.
├── build
│   └── public
│       ├── favicon.ico
│       ├── index.html
│       └── site.webmanifest
└── main.js
```
even removing `to: 'build'` will produce:
```
.
├── main.js
└── public
    ├── favicon.ico
    ├── index.html
    └── site.webmanifest
```
which yet contains the `public` folder while what's needed to be copied is it's content and not the folder itself! at least: `public/**/*` means that.

Currently, I've produced the expected result combining `from` with `context`:
```js
{
  from: '**/*',
  context: 'public'
}
```
but Is it a bug or expected behaviour of the plugin itself ?!!!

### Code

```js
// webpack.config.js
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    publicPath: '/'
  },
  plugins: [
    new CopyWebpackPlugin([
      {
        from: 'public/**/*',
        to: 'build'
      }
    ])
  ]
};
```
### How Do We Reproduce?
https://github.com/dNitro/copy-webpack-plugin-glob-issue

**Comment by sshmyg** [comment]
Solution:
- skip `to` params in config at all
- add `flatten: true`

Eg
```
new CopyPlugin([
        {
          from: 'public/**/*',
          flatten: true,
        },
      ]),
```

Add this comment, because isn't obvious how to copy files without wrapper.
