### ISSUE TITLE
Copy files with hashed name?

### ISSUE THREAD

**Issue by javierguzman** [webpack-contrib/copy-webpack-plugin#411]
Hello all,

I think it would be a nice feature to have the ability to hash the filenames of the copied files. Currently when I build with Webpack I copy my locales json files ( translations) into the dist folder.

These will be cached in user´s browsers and if I update them, users will not notice as they are cached.

Please, let me know your thoughts about this.

Thank you and regards.

**Comment by evilebottnawi** [comment]
You can do it using `to: '[path].[hash].[ext]'`, maybe we should improve docs about it, feel free to send a PR

**Comment by javierguzman** [comment]
Thanks @evilebottnawi !

Actually I am confused now. I remember searching for "hash" word in the documentation and I did not find anything, that is why I raised the suggestion. However, now I have taken another look and indeed it is pretty clear. Maybe I had the "Match Case" option checked in the search or something and that is why I could not find it.

Sorry for my mistake! I close this.

**Comment by evilebottnawi** [comment]
Let's open, i want to improve docs to avoid such situations in future
