### ISSUE TITLE
serialize-javascript dependency: regular expressions Cross-Site Scripting (XSS) vulnerability

### ISSUE THREAD

**Issue by jodydeanrogan** [webpack-contrib/copy-webpack-plugin#422]
Would it be possible to upgrade serialize-javascript dependency to version 2.1.1 or later? https://github.com/advisories/GHSA-h9rv-jmmf-4pgx

Many thanks

**Comment by pgs-gmartowski** [comment]
Looks like serialize-javascript version is updated in master branch but in v5.0.5 tag seems to still be at version: 
`"serialize-javascript": "^2.1.0",`

https://github.com/webpack-contrib/copy-webpack-plugin/blob/v5.0.5/package.json

**Comment by evilebottnawi** [comment]
Release will be in near future, WIP

**Comment by evilebottnawi** [comment]
Fixed in master
