### ISSUE TITLE
Passing empty array is no longer possible

### ISSUE THREAD

**Issue by smashercosmo** [webpack-contrib/copy-webpack-plugin#424]
The latest release introduced breaking change (options validation). Passing an empty array is no longer possible. So it broke cases like

```
new CopyWebpackPlugin(condition ? ['./something'] : [])
```
example: https://github.com/styleguidist/react-styleguidist/blob/master/src/scripts/make-webpack-config.ts#L100

### Expected Behavior

I honestly don't know if it's a valid case to support :)

**Comment by evilebottnawi** [comment]
Change condition `[condition ? new CopWebpackPlugin() : false].filter(Boolean)`, it is expected empty array is not supported

**Comment by smashercosmo** [comment]
Yeah, I know, that you can write it this way :) But before passing an empty array didn't trigger an error. So, technically, it's a breaking change.

**Comment by evilebottnawi** [comment]
Let's fix it :+1:

**Comment by boutell** [comment]
Watching this as it broke a number of projects, pinning temporarily to 5.0.x

**Comment by evilebottnawi** [comment]
In next release it will be returned and you can't use empty array

**Comment by vitalets** [comment]
> and you can't use empty array

Why?
You can write this check **once** inside a plugin instead of everyone of us will write it everywhere:
```js
[ patterns.length ? new CopWebpackPlugin({ patterns }) : false ].filter(Boolean)
```
