### ISSUE TITLE
Asset size is wrong when using transform option in webpack-stats.json

### ISSUE THREAD

**Issue by vidal7** [webpack-contrib/copy-webpack-plugin#430]
- Operating System: Windows 10
- Node Version: 12.14
- NPM Version: 6.13.4
- webpack Version: 4.41.2
- copy-webpack-plugin Version: 5.1.1

### Expected Behavior

When using --json flag to generate a webpack-stats.json file with webpack and using transform option, assets size must be right. 

### Actual Behavior

Size of asset is wrong when using transform option.

### Code

In webpack.config.js
```js
new CopyWebpackPlugin([
            {
                from: resolve('asset.css'),
                to: resolve('dist')
            },
            {
                from: resolve('asset.css'),
                to: resolve('dist/asset.css.gz'),
                transform: (content) => zlib.gzipSync(content)
            }
            ])
```
In webpack-stats.json size of asset.css.gz is the same as the untransformed asset asset.css. It must be lower since it's a gzip version of the asset.
```json
{
"assets": [
{
      "name": "asset.css",
      "size": 23027,
      "chunks": [],
      "chunkNames": [],
      "info": {},
      "emitted": true
    },
    {
      "name": "asset.css.gz",
      "size": 23027,
      "chunks": [],
      "chunkNames": [],
      "info": {},
      "emitted": true
    }
]
}
```

### How Do We Reproduce?
Use a transform option before emitting an asset and check the size of the transformed asset in the webpack-stats.json file in the assets key.

**Comment by evilebottnawi** [comment]
I think it is bug in webpack, i will look at this in near future

**Comment by cap-Bernardito** [comment]
Will be fixed in the next release
