### ISSUE TITLE
Add an option to fail the build if a file is missing

### ISSUE THREAD

**Issue by levz0r** [webpack-contrib/copy-webpack-plugin#431]
- Operating System: macOS 10.15.1
- Node Version: 10.16.3
- NPM Version: 6.13.1
- webpack Version: 3.3.9
- copy-webpack-plugin Version: 5.1.1

### Feature Proposal

When specifying a concrete file in `from` param and the file is not found, only a warning is generated.
Add a parameter such as `mandatory: true` which is false by default. When set to true and the file is not found - make the build fail.

### Feature Use Case
In `webpack.config.js` we have the following config:

```
  plugins: [
    new CleanWebpackPlugin(),
    new CopyPlugin([
      { from: "../services/templates", to: "templates" },
      {
        from: "../services/salesforce_auth.dev.json",
        flatten: true,
        to: output_dir
      },
      {
        from: "../services/salesforce_auth.prod.json",
        flatten: true,
        to: output_dir
      }
    ]),
    new webpack.NoEmitOnErrorsPlugin()
  ]
```
Both files are in `.gitignore`for obvious reasons. A new developer who didn't have the files, used webpack-cli to bundle the package, and didn't notice the warning message in the console. As a result, one of our services failed to communicate with salesforce and caused data loss. 
https://github.com/webpack-contrib/copy-webpack-plugin/issues/31 suggested to use `NoErrorsPlugin`, but it has no effect on the build.

**Comment by evilebottnawi** [comment]
Yes, let's do it, PR welcome
