### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, open

### ISSUE THREAD

**Issue by stevemarksd** [webpack-contrib/copy-webpack-plugin#434]
Same as https://github.com/webpack-contrib/copy-webpack-plugin/issues/52

```
new CopyPlugin([
        {from: resolveApp(`./public/anv.com`), to: buildFolder},
      ])
```

Error:

```
[Error: EISDIR: illegal operation on a directory, open 'XXXXX'] {
  errno: -4068,
  code: 'EISDIR',
  syscall: 'open',
  path: 'XXXXX'
}

```

XXXXX exists in my path

- Operating System:
- Node Version:
- NPM Version:
- webpack Version:
- copy-webpack-plugin Version:

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by stevemarksd** [comment]
Had to put an end slash on the path `/` and then `, toType: 'dir'`

**Comment by ericmhalvorsen** [comment]
For others, I was able to fix this by adding the ./ to the beginning of the path... `./src/dist` instead of `src/dist`
