### ISSUE TITLE
Copy files with the archive attribute only

### ISSUE THREAD

**Issue by gewisser** [webpack-contrib/copy-webpack-plugin#440]
- Operating System: Windows
- Node Version: v12.16.0
- NPM Version: 6.11.3
- webpack Version: 4.42.0
- copy-webpack-plugin Version: 5.1.1

### Feature Proposal

In my project there is a folder that should be completely copied to the target directory. Files in this folder are changed not so often and not all. There are about **10,000** files in this folder. The fun begins when I want to upload the project to the production server and start building the project in production mode. copy-webpack-plugin always copies all **10,000 files**, although there may be, for example, **two modified** ones. We need to enter the mode "Copy only with the **archive attribute**" and at this moment **remove this attribute from the file**. With any modification of the file, at least the Windows operating system will **automatically** set this attribute to **true** again  and **copy-webpack-plugin** will next copy this file and **remove** the "**archive**" attribute

### Feature Use Case

We can not in **real time recognize a file change** by the presence of the **archive attribute** and use this property for offline tracking of changed files to copy them to the target directory.

**Comment by evilebottnawi** [comment]
> archive attribute

**Comment by gewisser** [comment]
Or yes, maybe it’s to implement some `filter` function, where I can check the file attribute of the “**archive**” file that copy-webpack-plugin wants to copy and do not let it do if this flag is on the file, otherwise let it copy and remove this attribute, eg

```javascript
const winattr = require('winattr'); // npm install winattr

module.exports = {
    plugins: [
        new CopyPlugin([
            {
                from: 'vendor', to: 'vendor',
                filter(filePath) {
                    winattr.get(filePath, (err, attrs) => {
                        if (err !== null)
                            return true;

                        if (attrs.archive) {
                            winattr.set(filePath, {archive: false}, err => {
                                return err === null; // give copy file if err === null
                            });
                        } else
                            return false; // do not give copy file
                    });
                },
            },
        ]),
    ],
};
```

**Comment by evilebottnawi** [comment]
Yes, feel free to send a PR

**Comment by gewisser** [comment]
Thank you so much!
