### ISSUE TITLE
dependancy 'minimist' has security flaw reported by GH

### ISSUE THREAD

**Issue by mikesimmonds** [webpack-contrib/copy-webpack-plugin#443]
- Operating System: OSX
- Node Version:  12.11.1
- NPM Version: 6.11.3
- webpack Version:
- copy-webpack-plugin Version: 5.1.1

### What is the error?

Github is warning of security error in the minimist package <1.2.3
see: https://github.com/advisories/GHSA-vh95-rmgr-6w4m

```
├─┬ copy-webpack-plugin@5.1.1
│ ├─┬ cacache@12.0.4
│ │ └─┬ mkdirp@0.5.1
│ │   └── minimist@0.0.8
│ └─┬ loader-utils@1.2.3
│   └─┬ json5@1.0.1
│     └── minimist@1.2.0
```

**Comment by evilebottnawi** [comment]
Please update lock file

**Comment by mikesimmonds** [comment]
Sorry to sound dumb, but do you mean my local package.lock or the one in the repo (and create PR)?

**Comment by evilebottnawi** [comment]
> my local package.lock

**Comment by mikesimmonds** [comment]
Many thanks
