### ISSUE TITLE
Can't flatten output and have ignore blobs based on directories at the same time.

### ISSUE THREAD

**Issue by tinyfly** [webpack-contrib/copy-webpack-plugin#449]
- Operating System: MacOS 10.15.4
- Node Version: 10.17.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 5.1.1

### Expected Behavior

I'd like to set `flatten: true` and ignore files based on the `from` directory structure (i.e. `brand/**/*.*`).

### Actual Behavior

The ignore glob isn't matched and all files are flattened into the output folder. If I set `ignore` to false then my files are matched and excluded.

### Code

```js
new CopyPlugin([{
      from: './marketing',
      to: 'img/',
      ignore: ['brand/**/*.*'],
      flatten: true
    }]);
```
### How Do We Reproduce?

Create a `marketing` directory in your src with various files, add a `brand` directory with a few files and output to a `img` directory in your output folder. Notice that the files inside the brand directory are output also.

Here are a couple related issues that were closed due to various reasons:
https://github.com/webpack-contrib/copy-webpack-plugin/pull/134
https://github.com/webpack-contrib/copy-webpack-plugin/issues/209

**Comment by cap-Bernardito** [comment]
Fixed in master, release will be soon
