### ISSUE TITLE
Infer toType from `from` stat

### ISSUE THREAD

**Issue by Zirak** [webpack-contrib/copy-webpack-plugin#464]
- Operating System: linux
- Node Version: 14.2
- NPM Version: 6.14
- webpack Version: 4.39
- copy-webpack-plugin Version: 5.0.4

Apologies for the awkward title.

### Expected Behavior / Situation

When copying a file, no matter its name, the output will be a file.

### Actual Behavior / Situation

If you have a file without an extension, a directory is created with said file inside it. For example:

```js
new CopyPlugin({
    from: '.env',
    to: '.env',
});
```

```sh
$ file .env
.env: ASCII text
$ file build/.env
build/.env: directory
$ file build/.env/.env
build/.env/.env: ASCII text
```

The `toType` documentation, at the time of writing, says:

Name | Type | Default | Description
-- | -- | -- | --
'file' | {String} | undefined | If `to` has extension or `from` is file

And, indeed, `from` is a file.

### Modification Proposal

While the `toType` can be explicitly specified, the default behaviour should (I believe) be as documented: Detecting the `toType` based on the result of calling `stat` on `from`. Of course, the user would still be able to override by explicitly specifying a `toType`.

Reading through the source, the change doesn't seem to be too wild and I'm more than willing to PR it. Do you think this is a behaviour which should be changed at this point in time?

Thanks.

**Comment by Zirak** [comment]
As is mostly the case I've experienced instant regret after submitting this. While the default behaviour in _this_ case is confusing, I agree that the _general_ case is plausible. Changing my example only slightly:

```js
new CopyPlugin({
    from: '.env',
    to: 'subdir',
});
```

Creating `subdir/.env` does seem like a plausible result users may expect.

**Comment by cap-Bernardito** [comment]
Thanks for your contact. There really are inaccuracies in the documentation. I will correct them.

Your problem can be solved as follows:

```js
new CopyPlugin({
    from: '.env',
    to: '.env',
    toType: 'file'
});
```
Regarding the default behavior ...
If done as you suggest (`When copying a file, no matter its name, the output will be a file.`, `Detecting the toType based on the result of calling stat on from`)

Then we get the following:

```js
new CopyPlugin({
    from: 'file.txt',
    to: 'directory', // `directory` will be file
});
```
Which is also not obvious behavior

**Comment by Zirak** [comment]
Hey hey,

You are very much right that my proposed alternative is also non obvious, and has the significant drawback of being different than the current behaviour.

My mistake was, in my head, comparing `CopyPlugin` to `cp`. In both of our cases, `cp` does The Right Thing, but `cp` knows something that `CopyPlugin` does not: It knows whether the `to` is a directory because it already exists.

Sorry for wasting your time, it was a bad case of needing to write it out to see my error.
