### ISSUE TITLE
Fails copying by pattern containing '@' symbol

### ISSUE THREAD

**Issue by dmarcautan** [webpack-contrib/copy-webpack-plugin#479]
- Operating System: Windows 10
- Node Version: 12.13.0
- NPM Version: 6.12.1
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 6.0.0

### Actual Behavior
I get following error in console:
ERROR in unable to locate '**\*' at 'D:\Source\Elements\Source\Elements\node_modules\@felgaete\base64image\**\*'

### Code

```js
{
	from: "**/*",
	to: "ckeditor/plugins/base64image",
	context: "node_modules/@felgaete/base64image/",
}
```

### How Do We Reproduce?

All patterns succeed except the one above

**Comment by WillRadi** [comment]
Same issue with '@'

I'm using:
* Operating System: CentOS 8
* Webpack Version: 4.43.0
* Copy-webpack-plugin Version: 6.0.0
* Fontawesome: 5.13.0

Get this error when run `webpacker:compile`:

 unable to locate 'node_modules/@fortawesome/fontawesome-free' at '/vagrant/node_modules/@fortawesome/fontawesome-free/**/*'

**My code:**

`patterns: [{ from: 'node_modules/@fortawesome/fontawesome-free', to: 'raw-fontawesome-free' }]`

**Comment by cap-Bernardito** [comment]
Thanks for the feedback. Today we will fix this problem.

**Comment by Diablohu** [comment]
Something I have noticed

This pattern `{ from: 'D:\\Projects\\@koot\\_next\\test\\projects\\standard\\public' }` will be transformed into Glob `D:/Projects/\\@koot/_next/test/projects/standard/public/**/*`

And when I directly provide a pattern with a glob `{ from: 'D:/Projects/@koot/_next/test/projects/standard/public/**/*' }`, everything is fine.

The only difference between the 2 globs is the 2 slashes before `@`

I'm using:
- OS: Windows 10 1909
- Webpack 4.43

**Comment by pedrofurtado** [comment]
@evilebottnawi @cap-Bernardito looking forward to a release with this fix asap 🎉 thanks guys for your fast feedback! 🤝

**Comment by evilebottnawi** [comment]
:star: ETA today
