### ISSUE TITLE
WARNING in Conflict: Multiple assets emit different content to the same filename

### ISSUE THREAD

**Issue by doberkofler** [webpack-contrib/copy-webpack-plugin#482]
- Operating System: macOS
- Node Version: 14.1.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 6.0.0

### Expected Behavior

no warnings

### Actual Behavior

After having upgraded to version 6.0.0, I'm getting a new warning `WARNING in Conflict: Multiple assets emit different content to the same filename` for multiple files I'm copying.
If I switch back to version 5.1.1 no warnings are shown.
I assume that the warnings is in fact correct, as some of the resources that I copy might have already been copied to the target directory with a webpack loader, but the warning is annoying and it would be great, if t could by default be disabled again.
Maybe my build process can be improved, by only copying the assets that are not yet available but I don't see a way on how to do this in the CopyWebpackPlugin.

**Comment by cap-Bernardito** [comment]
I can`t reproduce this case. Please provide a minimally reproducible repository with a problem

**Comment by doberkofler** [comment]
I was unable to extract a test case from my production environment, but it seems as if the problem was resolved by your latest update. Thank you!
