### ISSUE TITLE
globOptions.ignore option doesn't work

### ISSUE THREAD

**Issue by jacksman** [webpack-contrib/copy-webpack-plugin#493]
- Operating System: MacOS v10.15.4 
- Node Version: 13.7.0
- NPM Version: 6.14.4
- webpack Version: webpack@4.43.0, webpack-cli@3.3.11
- copy-webpack-plugin Version: 6.0.1

### Expected Behavior

Setting globOptions.ignore should ignore matching files.

### Actual Behavior

Also matching files are copied.

### Code

```js
// webpack.config.js
const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

module.exports = {
    entry: {
        script: path.join(__dirname, 'src/index.ts')
    },
    output: {
        path: path.join(__dirname, 'debug'),
        filename: '[name].js'
    },
    module: {
        rules: [{ 
                test: /\.ts$/,
                use: [ { loader: 'ts-loader', options: { transpileOnly: true } }],
                exclude: /node_modules/
            }]
    },
    plugins: [
        new ForkTsCheckerWebpackPlugin(),
        new CopyWebpackPlugin({
            patterns: [{ from: 'src', globOptions: { ignore: [ '*.ts' ] } }]
        })
    ]
}
```

### How Do We Reproduce?

Setup a simple directory structure:
```
src
- test.txt
- test.css
- index.ts
tsconfig.json
webpack.config.js
```
Use provided webpack.config.js

**Comment by cap-Bernardito** [comment]
You can use `src/*.ts`, or `**/*.ts`, or `**.ts`

https://github.com/mrmlnc/fast-glob#basic-syntax

```js
module.exports = {
    plugins: [
        new CopyWebpackPlugin({
            patterns: [{ from: 'src', globOptions: { ignore: [ '**.ts' ] } }]
        })
    ]
}
```

**Comment by evilebottnawi** [comment]
Yep, it is `fast-glob` behavior, so we mark updating `globby` (latest version uses `fast-glob`) as a breaking change. I will update docs to avoid problems in the future

**Comment by alumni** [comment]
I'm posting this here since it's most likely related.

After upgrading to v6, I moved the `ignore` option into `globOptions`, but it has no effect, all files are copied.
Moreover, the cache doesn't work (regardless if it's set to `true` or to a path). Any ideas of could be wrong?

```js
new CopyWebpackPlugin({
    patterns: [{
        from: 'node_modules/@highcharts/map-collection/**/*.geo.json',
        to: 'maps/',
        toType: 'dir',
        globOptions: {
            ignore: [
                'node_modules/@highcharts/map-collection/countries/us/custom/*congress*', // skip US Congress maps
                'node_modules/@highcharts/map-collection/historical/**', // skip historical maps
            ],
        },
        cacheTransform: 'node_modules/.cache/copy-webpack-plugin',
    }]
})
```

**Comment by evilebottnawi** [comment]
You don't need `cacheTransform`

**Comment by alumni** [comment]
> You don't need `cacheTransform`

You're right, I don't need to cache it in this case, I just noticed that it didn't create the cache folder.

However, the `ignore` option doesn't work.

It does work with `fast-glob` though:
```js
fg = require('fast-glob');
fg.sync('node_modules/@highcharts/map-collection/**/*.geo.json', {
  ignore: [
    'node_modules/@highcharts/map-collection/countries/us/custom/*congress*.geo.json',
    'node_modules/@highcharts/map-collection/historical/**/*.geo.json'
  ]}
);
```

**Comment by evilebottnawi** [comment]
```
'**/node_modules/@highcharts/map-collection/countries/us/custom/*congress*.geo.json', // skip US Congress maps
                '**/node_modules/@highcharts/map-collection/historical/**/*.geo.json', // skip historical maps
```

**Comment by alumni** [comment]
That works! Thanks!

Why does it work? Is the glob supposed to match an absolute path? Or are the paths relative to another directory instead of `cwd()`?

**Comment by evilebottnawi** [comment]
> Or are the paths relative to another directory instead of cwd()?

Yes, by default `context` is `compiler.context`, not `process.cwd()`
