### ISSUE TITLE
copy-webpack-plugin "ignore" option not working with dot files after update

### ISSUE THREAD

**Issue by AndasDev** [webpack-contrib/copy-webpack-plugin#498]
- Operating System:
- Node Version: 12.7.0
- NPM Version: 6.10.0
- webpack Version: 4.43.0
- copy-webpack-plugin Version: ^6.0.1

### Expected Behavior

Copy webpack plugin should be able to ignore dotfile .gitkeep.

### Actual Behavior

In the previous major version of copy-webpack-plugin it was possible to ignore the .gitkeep file on build. Now it is being totally ignored.

### Code

```js
new CopyWebpack({
            patterns: [
                {
                    from: paths.images(),
                    to: paths.output.images(),
                    globOptions: {
                        dot: true,
                        ignore: ['.gitkeep']
                    }
                }
            ]
        }),
```

**Comment by evilebottnawi** [comment]
`**/.gitkeep'`

**Comment by AndasDev** [comment]
> `'**/.gitkeep'` https://github.com/webpack-contrib/copy-webpack-plugin#ignoring-files

After adding this line which I have tried before your post returns:

unable to locate '/Users/nino/Documents/Projecten/Friends For Brands/WordPress-Starter-V4.0.0/src/fonts' at '/Users/nino/Documents/Projecten/Friends For Brands/WordPress-Starter-V4.0.0/src/fonts/**/*'

This folder exists in /src/fonts/ but is unable to locate it.

**Comment by evilebottnawi** [comment]
It means you have invalid path(s) in `from`

**Comment by AndasDev** [comment]
> It means you have invalid path(s) in `from`

Can you clarify why it dit work in the latest version 5? I used this for months without issues.

**Comment by evilebottnawi** [comment]
@AndasDev because we update `globby` and `globby` uses `fast-glob` instead `node-glob`, it is in README for `6` version

**Comment by evilebottnawi** [comment]
If you provide reproducible test repo I can investigate, in theory it can be bug on `fast-glob` side, but i think it is problem in the configuration, that is why we ask you to provide reproducible steps, but you just remove from the issue template, and that’s why the issue was closed

**Comment by AndasDev** [comment]
@evilebottnawi any news?

**Comment by evilebottnawi** [comment]
It is expected, you run try to copy `./src/fonts/` directory, directory contains only one item `.gitignore` and you ignore it, so `globby` return `[]` empty list, we throw an error on this (previously it was warning), you can disable this behavior adding `noErrorOnMissing: true`

**Comment by AndasDev** [comment]
> It is expected, you run try to copy `./src/fonts/` directory, directory contains only one item `.gitignore` and you ignore it, so `globby` return `[]` empty list, we throw an error on this (previously it was warning), you can disable this behavior adding `noErrorOnMissing: true`

Thanks for checking it out. So, where should the noErrorOnMissing check go?

**Comment by evilebottnawi** [comment]
Here docs https://github.com/webpack-contrib/copy-webpack-plugin#noerroronmissing

**Comment by AndasDev** [comment]
> Here docs https://github.com/webpack-contrib/copy-webpack-plugin#noerroronmissing

After adding that rule the .gitkeep is still being copied but when i add the **/ it will display the same previous error.

```
        new CopyWebpack({
            patterns: [
                {
                    from: paths.fonts(),
                    to: paths.output.fonts(),
                    globOptions: {
                        dot: true,
                        noErrorOnMissing: true,
                        ignore: ['.gitkeep']
                    }
                }
            ]
        }),

        new CopyWebpack({
            patterns: [
                {
                    from: paths.images(),
                    to: paths.output.images(),
                    globOptions: {
                        dot: true,
                        noErrorOnMissing: true,
                        ignore: ['.gitkeep']
                    }
                }
            ]
        }),
```

**Comment by AndasDev** [comment]
> ```
> new CopyWebpack({
>             patterns: [
>                 {
>                     from: paths.fonts(),
>                     to: paths.output.fonts(),
>                     noErrorOnMissing: true,
>                     globOptions: {
>                         dot: true,
>                         ignore: ['**/.gitkeep']
>                     }
>                 }
>             ]
>         }),
> ```

What a boss! Thank you very much man.

**Comment by alan-agius4** [comment]
The resolution for this doesn't seem correct. 
Ignoring `['**/.gitkeep'] is not the same as ['.gitkeep']`, the former will ignore all files named `.gitkeep` irrespective were they are located in the directory tree, while the latter will only ignore the root path.

This bug is actually caused by this package, because it uses absolute paths in globs https://github.com/webpack-contrib/copy-webpack-plugin/blob/6d51a69994a14cc7f351f359b331ac4bc7f5f41c/src/utils/createPatternGlob.js#L30-L33

https://github.com/webpack-contrib/copy-webpack-plugin/blob/6d51a69994a14cc7f351f359b331ac4bc7f5f41c/src/utils/createPatternGlob.js#L69-L74

This break negative patterns when they don't contain `**`.

As a temporary workaround one can do the below;

```js
new CopyWebpack({
  patterns: [
    {
      from: paths.fonts(),
      to: paths.output.fonts(),
      noErrorOnMissing: true,
      globOptions: {
        dot: true,
        ignore: ['.gitkeep'].map(i => path.posix.join(paths.fonts(), i)),
      }
    }
  ]
}),
```

That being said, the correct fix for this would be to remove absolutePaths from the glob pattern.

**Comment by evilebottnawi** [comment]
@alan-agius4 Not quite right, but if you want to talk about it feel free to open an issue in `fast-glob` repo, because the `globOptions` option for `fast-glob`, we have no logic for `ignore`

**Comment by evilebottnawi** [comment]
@alan-agius4 `paths.fonts` is absolute path, right?

**Comment by alan-agius4** [comment]
@evilebottnawi, yes

**Comment by evilebottnawi** [comment]
@alan-agius4 feel free to open a new issue

**Comment by alan-agius4** [comment]
@evilebottnawi, yes. I’ll open a new issue later today/tomorrow.
