### ISSUE TITLE
Files are missing after a recompile / since v6

### ISSUE THREAD

**Issue by martinoppitz** [webpack-contrib/copy-webpack-plugin#501]
- Operating System: Win10
- Node Version: 12.13.1
- NPM Version: 6.14.5
- webpack Version: 4.42.0
- copy-webpack-plugin Version: 6.0.1

### Expected Behavior

Develop the app in serve mode. Change files and webpack recompile the app and refresh the webpage in the browser. All files are available in the virtual webhost storage.

FYI: I will not copy files a the disk. The static files will be copied and the bundled files too. But since v6 it does not work anymore.

### Actual Behavior

Develop the app in serve mode. Change files and webpack recompile the app and refresh the webpage in the browser. The files are compiled missed, everything else are available.

### Code

See: https://github.com/martinoppitz/leanup/blob/master/cli/core/webpack.config.js
```js
new CopyWebpackPlugin({
  patterns: [
    {
      from: path.resolve(process.cwd(), 'public'),
    },
  ],
}),
```

### How Do We Reproduce?

- clone: https://github.com/martinoppitz/[TODO]
- npm install
- npm start
- the app is visible
- make changes in the app
- the app is not visible

**Comment by evilebottnawi** [comment]
- webpack-pwa-manifest do not have compatibility with new `html-webpack-plugin`
https://github.com/arthurbergmz/webpack-pwa-manifest/blob/master/src/generators/tapable.js#L4
- `html-webpack-plugin` doesn't work correctly with webpack-copy-plugin

Open issues in `html-webpack-plugin` and `webpack-pwa-manifest`, can't be fixed on our side

**Comment by evilebottnawi** [comment]
@martinoppitz `html-webpack-plugin` plugin has bad support with many webpack feature, in the past I suggested moving it to officially supported plugins (webpack-contrib), but the creator declined it, therefore we cannot provide first-class support with `html-webpack-plugin`

**Comment by evilebottnawi** [comment]
Disable `cache` for `html-webpack-plugin`, it is broken and never works fine

**Comment by martinoppitz** [comment]
In my minimal example I checked that.

Thats right. 

I am proofing why the webworkers sometimes missing. But I cant reproduce it, by my self. :no_good:

**Comment by evilebottnawi** [comment]
You can try to open a new issue in `html-webpack-plugin`, maybe other developers have the same problem and provide reproducible test repo
