### ISSUE TITLE
Cannot upgrade from 5.0.3 to 6.0.2, new config not working

### ISSUE THREAD

**Issue by Mobrockers** [webpack-contrib/copy-webpack-plugin#506]
Heya, I'm trying to update the copy-webpack-plugin to v6 but for some reason the new-style config does not take. The error is 'should not have fewer than 1 item' but I definitely added a pattern to the array. Source is here: stryker-mutator/azure-devops-mutationreport-publisher#47 there is a build attached to the pr. Direct link to config is here: https://github.com/stryker-mutator/azure-devops-mutationreport-publisher/pull/47/files#diff-bb92aaed147443060bab0d2a409b62da can anyone tell me what's wrong about my config? I copy-pasted this from the docs

- Operating System: Windows latest, Ubuntu latest
- Node Version: v10.11.0 / v12.x
- NPM Version: 6.4.1
- webpack Version: ^4.22.0
- copy-webpack-plugin Version: ^6.0.2

### Expected Behavior

Using new v6 style config does not produce error

### Actual Behavior

New v6 style config results in error:

```
Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] misses the property 'patterns'. Should be:
   [non-empty string | object { from, to?, context?, globOptions?, toType?, force?, flatten?, transform?, cacheTransform?, transformPath?, noErrorOnMissing? }, ...] (should not have fewer than 1 item)
ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
    at validate (/home/vsts/work/1/s/extension/PublishMutationReport/node_modules/copy-webpack-plugin/node_modules/schema-utils/dist/validate.js:96:11)
    at new CopyPlugin (/home/vsts/work/1/s/extension/PublishMutationReport/node_modules/copy-webpack-plugin/dist/index.js:24:30)
    at Object.<anonymous> (/home/vsts/work/1/s/extension/PublishMutationReport/webpack.config.js:27:13)
    at Module._compile (/home/vsts/work/1/s/extension/PublishMutationReport/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/home/vsts/work/1/s/extension/PublishMutationReport/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```

### Code

```js
plugins: [
    new CopyWebpackPlugin({
      patterns: [
        { from: '**/*.html', context: "static" },
      ],
    }),
  ]
```

### How Do We Reproduce?

From the root of branch from https://github.com/stryker-mutator/azure-devops-mutationreport-publisher/tree/dependabot/npm_and_yarn/copy-webpack-plugin-6.0.2/

Run `npm install`
Run `npx lerna bootstrap`
Run `npx lerna run compile` 

Or 

From https://github.com/stryker-mutator/azure-devops-mutationreport-publisher/tree/dependabot/npm_and_yarn/copy-webpack-plugin-6.0.2/extension/DisplayBuildResultReport

Run `npm install`
Run `npm run compile`

**Comment by evilebottnawi** [comment]
Problem here https://github.com/stryker-mutator/azure-devops-mutationreport-publisher/blob/dependabot/npm_and_yarn/copy-webpack-plugin-6.0.2/extension/PublishMutationReport/webpack.config.js#L27, be careful when updating dependencies in mono repos

**Comment by Mobrockers** [comment]
> Problem here https://github.com/stryker-mutator/azure-devops-mutationreport-publisher/blob/dependabot/npm_and_yarn/copy-webpack-plugin-6.0.2/extension/PublishMutationReport/webpack.config.js#L27 (old syntax, you need update code to new option syntax), be careful when updating dependencies in mono repos 

🤦‍♂️ Thank you so much, sorry for the unnecessary issue.
