### ISSUE TITLE
Fix the use of serialize-javascript <3.1.0 in Copy-Webpack-Plugin 5

### ISSUE THREAD

**Issue by snowball58** [webpack-contrib/copy-webpack-plugin#509]
- Operating System: Windows 10
- Node Version: 14.4.0
- NPM Version: 6.14.5
- webpack Version: 4.42.1
- copy-webpack-plugin Version: 5.1.1

### Feature Proposal
I am currently trying to eliminate the use of Serialize-Javascript@2.1.2 in a project. Part of this would require upgrading Copy-Webpack-Plugin to v6 from 5.1.1. It'd be better to not have to make a major version jump just for eliminating a vulnerability's sake. Could a new version of version of Copy-Webpack-Plugin v5 be put out that uses Serialize-Javascript 3.1.0?
### Feature Use Case
Projects which don't require the changes made in Copy-Webpack-Plugin v6, but do desire elimination of vulnerable dependencies.

**Comment by evilebottnawi** [comment]
No, please update CopyWebpackPlugin to latest version

**Comment by evilebottnawi** [comment]
There are many big fixes for v6, so prefer to update version to latest, migration is very easy
