### ISSUE TITLE
"Unexpected token {" with imported plugin

### ISSUE THREAD

**Issue by Rall3n** [webpack-contrib/copy-webpack-plugin#510]
- Operating System: WSL2 Ubuntu 20
- Node Version: 8.10.0
- NPM Version: 6.4.1
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 6.0.3

### Expected Behavior

When running `npx webpack` Webpack should build the bundles without errors.

### Actual Behavior

Webpack outputs `Unexpected token {` while having `copy-webpack-plugin` imported.
Had been tested on Windows before and there it works without issues.
It also works with the previous version (`6.0.2`).

### Code

```js
// webpack.config.js
const CopyPlugin = require('copy-webpack-plugin');
const path = require('path');

module.exports = {
    entry: './index.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
   }
};
```

### How Do We Reproduce?

* Create an empty project on a Ubuntu system
* Install:
  * `webpack` + `webpack-cli`
  * `copy-webpack-plugin`
* Create webpack config with above content
* Create at least an `index.js` in project root
* Run `npx webpack`
* See output mentioned above

**Comment by evilebottnawi** [comment]
We don't support `8.10.0` node, please look at https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/package.json#L16
