### ISSUE TITLE
Using copy-web-pack 6.0.3 causing issue in jenkins and causing the build to fail

### ISSUE THREAD

**Issue by ChetanaJavali** [webpack-contrib/copy-webpack-plugin#512]
Upgraded the copy-web-pack  to '6.0.3' version  and the following changes are being made in webpack.prod.js

const CopyPlugin = require('copy-webpack-plugin')

  **plugins: [
    new CopyPlugin({ patterns: [{ from: 'package.json' }] })
]**

In the local, while executing npm run build, there is no issue  and while the build is progressing in jenkins it is failing and throwing an error :

node_modules/copy-webpack-plugin/node_modules/p-limit/index.js:30
	} catch {}
 SyntaxError: Unexpected token {

Help for this issue is very much appreciated

Thanks!!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You use old version of node

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/copy-webpack-plugin/issues/511
