### ISSUE TITLE
the bug of p-limit

### ISSUE THREAD

**Issue by referencedebug** [webpack-contrib/copy-webpack-plugin#513]
![image](https://user-images.githubusercontent.com/47730461/87268145-4106f880-c4fc-11ea-8b9b-ac6ca88cc022.png)
when i start to compile the webpack, the copy-webpack-plugin report the error. I looked at the source code, I found a try-catch syntax error

![image](https://user-images.githubusercontent.com/47730461/87268404-dacea580-c4fc-11ea-873f-011db0c61743.png)

**Comment by evilebottnawi** [comment]
Update node version, do not ignore warning from npm

**Comment by CalculonPrime** [comment]
Seems silly to force someone to upgrade to a new version of node, which might not be available within their default Linux repos, just so that developer can avoid typing "(e)" before the catch clause.  I would never force an upgrade for such a trivial reason.

**Comment by evilebottnawi** [comment]
node@6 is not supported and contains a lot of security bugs, do not use this, it is not safe
