### ISSUE TITLE
Copied files not being minimized by webpack/terser

### ISSUE THREAD

**Issue by ZDTaylor** [webpack-contrib/copy-webpack-plugin#515]
- Operating System: Windows 10 x64
- Node Version: 12.18.2
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 6.0.3

### Expected Behavior

Files copied via copy-webpack-plugin are minimized by the webpack minimizer in general, or at least terser-webpack-plugin in this case.

### Actual Behavior

Files copied via copy-webpack-plugin are not minimzed at all.

### Code

https://github.com/ZDTaylor/WebpackCopyPluginIssues

### How Do We Reproduce?

Run `npm run build` in the linked repo and view dist/copied.js. It should be minified.

**Comment by evilebottnawi** [comment]
Thanks for the issue, I will look at this in near future

**Comment by evilebottnawi** [comment]
Works fine with `webpack@5`, but not with webpack@4, but on the `terser-webpack-plugin` side, WIP

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/copy-webpack-plugin/issues/515

**Comment by evilebottnawi** [comment]
Let's close this here, because there are no bugs on `copy-webpack-plugin` side

**Comment by ZDTaylor** [comment]
@evilebottnawi Using 3.0.7 of terser-webpack-plugin works! Thanks for the quick fix. One follow up question: Will terser-webpack-plugin generate sourcemaps if none exist, or just transform sourcemaps from earlier steps? I was expecting/hoping the assets from copy-webpack-plugin would have sourcemaps after being run through terser-webpack-plugin, but they do not.
