### ISSUE TITLE
6.0.3 breaks compatibility with Node.js 8 (due to updated p-limit package)

### ISSUE THREAD

**Issue by stefandesu** [webpack-contrib/copy-webpack-plugin#516]
- Operating System: macOS 10.14.6
- Node Version: 8.17.0
- NPM Version: 6.13.4
- webpack Version: 4.43.0
- copy-webpack-plugin Version: 6.0.3

### Expected Behavior

A patch update does not make breaking changes.

### Actual Behavior

6.0.3 updates `p-limit` from 2.3.0 to 3.0.1 which has ["Require Node.js 10" as a breaking change](https://github.com/sindresorhus/p-limit/releases/tag/v3.0.0).

**Comment by evilebottnawi** [comment]
We don't support node@8, please look at https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/package.json#L16, please read CHANGELOG, please do not ignore npm warnings

**Comment by stefandesu** [comment]
Sorry! 🙏 I haven't noticed because 6.0.2 seems to work fine with v8, at least according to our CI build on Travis. I don't personally use v8, so I didn't see the warning.
