### ISSUE TITLE
6.x runs Webpack optimization step on copied files (when no transform requested)

### ISSUE THREAD

**Issue by SimmeNilsson** [webpack-contrib/copy-webpack-plugin#526]
- Operating System: Windows 10
- Node Version: v14.8.0
- NPM Version: yarn 1.22.4
- webpack Version: 4.44.1
- copy-webpack-plugin Version: 6.1.0
- terser-webpack-plugin: tested with 3.1.0 and 4.1.0 (webpack pulls in ^1.4.3 also)

### Expected Behavior

File copied with no transform option should be copied as is.

### Actual Behavior

File is minified by webpack.

### Observations

This does not happen with copy-webpack-plugin 5.x.
This does not happen if only running with terser-webpack-plugin 1.4.5 (pulled in as dep to webpack).

### Code

```js
const TerserPlugin = require("terser-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");

module.exports = function () {
    return {
        entry: {
            "main": "./main.js"
        },
        mode: "production",
        optimization: {
            minimizer: [
                new TerserPlugin({
                    terserOptions: {
                        ecma: 6
                    }
                })
            ]
        },
        plugins: [
            new CopyWebpackPlugin({
                patterns: [
                    { from: "./filetocopy.js", to: "./" }
                ]
            })
        ]
    };
};
```

Content of file to copy
```js
isBrowser = !!(typeof window !== 'undefined' && typeof navigator !== 'undefined' && window.document);

mixin({
    isBrowser: isBrowser
});
```

Resulting file
```js
isBrowser=!("undefined"==typeof window||"undefined"==typeof navigator||!window.document),mixin({isBrowser});
```

### How Do We Reproduce?

https://github.com/SimmeNilsson/CopyWebpackPluginTransform
Build it and compare filetocopy.js original vs copied file in dist folder.

**Comment by evilebottnawi** [comment]
It is expected, https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.0.0

> migrate on compilation.additionalAssets hook

Maybe some misleading, if you need to disable `TerserPlugin` for some files, please use `test`/`include`/`exclude` options

**Comment by SimmeNilsson** [comment]
Ah, okay. Thank you for clarifying!
I read the release notes prior to posting but I lacked the knowledge of webpack internals to understand the implications of that line.
