### ISSUE TITLE
Allow adding metadata to info

### ISSUE THREAD

**Issue by madflow** [webpack-contrib/copy-webpack-plugin#538]
- Operating System: Arch Linux
- Node Version: 14
- NPM Version:
- webpack Version: 5
- copy-webpack-plugin Version: latest

### Feature Proposal

Allow the plugin user, to add metadata to the `info` field, so it can be used when generating manifest files from the "Stats Object".

### Feature Use Case

I am using a `manifest.json` in a backend application, to map assets to paths.

I have a CSS file: `src/assets/css/one.css` which I copy to the dist folder.

When I do:

```JS
{
  from: './src/assets/css/one.css',
  to: 'assets/css/[name].[ext]'
},
```

then I get in `stats.toJson`

```JSON
{
  "name": "assets/css/one.css",
  "info": {
    "copied": true
  }
}
```
in the stats. This output is predictable for me. The backend app could know the original path and find the mapped asset.

But when I use a content hash:

``` to: 'assets/css([name].[contenthash].[ext]'```

The output name is not easily predictable 

`"name": "assets/css/one.c464fd6cf99b5e1eccdf82428e4db7a8.css",`

What I would need is to be able to tell the copy plugin, to attach a predictable name.

```JSON
{
  "name": "assets/css/one.c464fd6cf99b5e1eccdf82428e4db7a8.css",
  "info": {
    "copied": true,
    "name": "assets/css/one.css",
    "someMoreInfo": "important"
  }
}
```

**Comment by evilebottnawi** [comment]
@madflow what is use case?

**Comment by madflow** [comment]
@evilebottnawi

I am using a `manifest.json` file together with: https://symfony.com/doc/current/components/asset.html#json-file-manifest

> JSON File Manifest

>A popular strategy to manage asset versioning, which is used by tools such as Webpack, is to generate a JSON file mapping all >source file names to their corresponding output file: 

I use `webpack-manifest-plugin` for creating the manifest.json. I also tried all other plugins for manifests assets etc.

The entry chunks/vendor chunks all have the original filename/chunkname mapped to the outputed file - but not the copied ones. Like so:

```
{
  "entry1.js": "entry1.f6fb80ef51ad066ef7cd.bundle.js",
  "entry2.js": "entry2.5c15f4615d5c7b12041d.bundle.js",
  "entry3.js": "entry3.ecb4857f8cc08c692d5f.bundle.js",
  "assets/one.c464fd6cf99b5e1eccdf82428e4db7a8.css": "assets/one.c464fd6cf99b5e1eccdf82428e4db7a8.css"
}
```

When using Symfony - I can access the entry chunks by their original name:

```
echo $package->getUrl('entry1.js');
```

In order to be able to get the url of  the copied assets in Symfony - I need a predictable name. Since non of the existing "Manifest" plugins can deliver that  - I want use:

* https://webpack.js.org/api/node/#statstojsonoptions
* and some custom code to output an assets manifest with predictable names for copied assets.

In order to to that with this plugin in use - I thought of ammending the `info` object with additional data - like the original path.

**Comment by evilebottnawi** [comment]
Assets info is internal structure and will no be public, if you need to have original path in assets info feel free to send a PR, no need to option(s) for this

**Comment by evilebottnawi** [comment]
WIP

**Comment by andreasschiestl** [comment]
I think this change should be reverted, because it is a breaking change in some cases. For example we use the `copy-webpack-plugin` with the `transform` option where we convert some of the files and change also the file name/extensions. With this change we now have the original filename in the manifest.json.

What you have requested can be done with the `map` option of the `webpack-manifest-plugin` if you are using an older version or `removeKeyHash` in case of a newer version. So you are fixing something that doesn't need to be fixed.
