### ISSUE TITLE
Add parameter to specify hook on which to trigger migration

### ISSUE THREAD

**Issue by lu40** [webpack-contrib/copy-webpack-plugin#546]
- Operating System: Debian 10
- Node Version: 12.19.0
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- copy-webpack-plugin Version: 6.2.1

### Feature Proposal
Add a parameter (e.g. `options.migrationHook`) to specify any other compilation hook than `compilation.additionalAssets` to trigger the migration on.

Line where the hook is used:
https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L609

### Feature Use Case
As reported in https://github.com/webpack-contrib/copy-webpack-plugin/issues/526 the behavior of this plugin changed in v6 and can cause errors because of the following optimization steps. If there are multiple optimization plugins used (in my case `TerserPlugin` and `OptimizeCSSAssetsPlugin`) and no optimization whatsoever of the copied files is desired, specifying another hook would be a handy solution. E.g. using the [`afterOptimizeAssets`](https://webpack.js.org/api/compilation-hooks/#afteroptimizeassets) hook for the described situation.

I can open a PR, but first I wanted to hear your opinions if this is wanted like proposed.

**Comment by evilebottnawi** [comment]
No, we don't want to adding this options, you need to migrate on https://github.com/webpack-contrib/css-minimizer-webpack-plugin

From https://github.com/NMFR/optimize-css-assets-webpack-plugin:

```
A Webpack plugin to optimize \ minimize CSS assets.

warning For webpack v5 or above please use css-minimizer-webpack-plugin instead.
```

**Comment by evilebottnawi** [comment]
You should use `test`/`include`/`exclude` for filtering, there are only two rights hooks for assets manipulation - `additionalAssets` (webpack@4 and webpack@5, but deprecated and we keeping it for compatibility) and `processAssets` (webpack@5 and future releases)

**Comment by lu40** [comment]
Ok! Thanks for the info and clarification :+1:
