### ISSUE TITLE
DotenvPlugin support for copied files

### ISSUE THREAD

**Issue by tamirvs** [webpack-contrib/copy-webpack-plugin#550]
- Operating System: Ubuntu
- Node Version: 12.14.1
- NPM Version: 6.14.8
- webpack Version: 5.2.0
- copy-webpack-plugin Version: 5.0.1

### Expected Behavior
When using [DotenvPlugin](https://github.com/mrsteele/dotenv-webpack), process.env.[NAME] should be replaced with .env variables in the copied files.

### Actual Behavior
I get an error:

> process is not defined

When used in other files (that are not being copied by CopyPlugin) it works fine.

### Code

```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyPlugin = require('copy-webpack-plugin');
const Dotenv = require('dotenv-webpack');

module.exports = {
  ...
  plugins: [
    new HtmlWebpackPlugin({
      hash: true,
      template: './src/index.html',
      filename: './index.html'
    }),
    new Dotenv(),
    new CopyPlugin({
      patterns: [
        {
          from: './src/embed.js',
          to: './'
        }
      ]
    })
  ],
};

```

```js
// embed.js
console.log(process.env.SOME_VAR);
```

### How Do We Reproduce?
With the code above

**Comment by evilebottnawi** [comment]
> When using DotenvPlugin, process.env.[NAME] should be replaced with .env variables in the copied files.

No, we just copy files, no magic, you can use the `transform` option to do, anyway you can open an issue `Dotenv` and request this feature
