### ISSUE TITLE
When watching, CopyPlugin emits all unchanged files and emits file contents from outdated snapshots

### ISSUE THREAD

**Issue by felixhao28** [webpack-contrib/copy-webpack-plugin#553]
- Operating System: Windows 10
- Node Version: v15.0.1
- NPM Version: 7.0.3
- webpack Version: 5.4.0
- copy-webpack-plugin Version: 6.3.0

### Expected Behavior

CopyPlugin should only write modified files and write up-to-date file contents.

### Actual Behavior

Actaully, there are two some-what related issues here.

[Issue 1] When a file changes, CopyPlugin attempts to write all files because it failed to find it in "assets".

<details><summary>details</summary>
<p>

I am changing a file from "static" folder and it is not loaded through a loader.

After debugging for a while, I finally pinned down the root cause to this line:

https://github.com/webpack-contrib/copy-webpack-plugin/blob/fa5aa1bf647ff95e04fa89cdbb52297d859989a5/src/index.js#L709

```js
const existingAsset = compilation.getAsset(filename);
```

This always returns `null` for my "static/index.html", because somehow only source files (or more precisely, files matching rules and loaded through a loader) are considered assets (`compliation.assets`). Since `existingAssets` cannot be found, CopyPlugin will then treat it as a new file and emitting the source on this line https://github.com/webpack-contrib/copy-webpack-plugin/blob/fa5aa1bf647ff95e04fa89cdbb52297d859989a5/src/index.js#L749.

```js
compilation.emitAsset(filename, source, info);
```

</p>
</details>

[Issue 2] The file actually got changed did not update properly. This always happens if I change the file quickly after the previous change.

This is a new issue since `6.3.0` after `CopyPlugin.createSnapshot` is a thing.

<details><summary>details</summary>
<p>

I pinned the root cause to this line:

https://github.com/webpack-contrib/copy-webpack-plugin/blob/fa5aa1bf647ff95e04fa89cdbb52297d859989a5/src/index.js#L438

```js
snapshot = await CopyPlugin.createSnapshot(
    compilation,
    startTime,
    sourceFilename
);
```

In this call, `sourceFilename` is `"static/index.html"` but in Webpack's [CachedInputFileSystem](https://github.com/webpack/enhanced-resolve/blob/master/lib/CachedInputFileSystem.js), all paths should be OS-dependent absolute path like `"D:\projects\copy-webpack-plugin-bugrepro\static\index.html"`. This causes [`CachedInputFileSystem._storeResult`](https://github.com/webpack/enhanced-resolve/blob/d6807b553dc7e3157746b57a82cb238cd5e58cee/lib/CachedInputFileSystem.js#L189) to use a different key than the key used in [`CachedInputFileSystem.purge`](https://github.com/webpack/enhanced-resolve/blob/master/lib/CachedInputFileSystem.js#L240), which lets to files' modified time cache not purged before CopyPlugin tries to read it.

As a result,

https://github.com/webpack/enhanced-resolve/blob/d6807b553dc7e3157746b57a82cb238cd5e58cee/lib/CachedInputFileSystem.js#L172

```js
let cacheEntry = this._data.get(path);
```

which is called from

https://github.com/webpack-contrib/copy-webpack-plugin/blob/fa5aa1bf647ff95e04fa89cdbb52297d859989a5/src/index.js#L367

```js
cacheEntry = await cache.getPromise(
    `${sourceFilename}|${index}`,
    null
);
```

gets previously stored cache instead of null.

</p>
</details>

### Code

```js
module.exports = {
    ...
    plugins: [
        new CopyPlugin({
            patterns: [{
                from: 'static',
                to: path.resolve('dist', 'static')
            }}]
        })
    ]
}
```

### How Do We Reproduce?

Clone this https://github.com/felixhao28/copy-webpack-plugin-bugrepro

Then `npm install`.

[Issue 1]

First `npm run watch`, and then make some changes to `dist\static\index.html` and save. Then make some changes to `static\test.html` and save. Watch the changes to `dist\static\index.html` gets reverted, indicating `dist\static\index.html` is written.

[Issue 2]

First `npm run watch`, and then make some changes to `static\index.html` and save. Now `dist\static\index.html` should be the same as `static\index.html`.

Then change `static\index.html` again and save. Now `dist\static\index.html` does not update accordingly.

**Comment by felixhao28** [comment]
Actually, since Issue 2 exists, Issue 1 can only be reproduced with a previous version like `"copy-webpack-plugin": "^6.2.1"`. But the issue is definitely here on "6.3.0".

**Comment by felixhao28** [comment]
Issue 2:

![553_1](https://user-images.githubusercontent.com/2417391/98932039-c71e6480-2519-11eb-8d0c-456dae62d636.gif)

Issue 1:

![553_2](https://user-images.githubusercontent.com/2417391/98932861-dd78f000-251a-11eb-9695-49ad36718c78.gif)

**Comment by evilebottnawi** [comment]
Please never describe problems like this. Try to avoid links on code, it just makes everything unreadable and spammy, just describe actual result + excepted + reproducible test repo, This will not only make it easier for me to find the error and fix it, but also save your time and help other developers to find the same problem.

**Comment by evilebottnawi** [comment]
> [Issue 1]

> First npm run watch, and then make some changes to dist\static\index.html and save. Then make some changes to static\test.html and save. Watch the changes to dist\static\index.html gets reverted, indicating dist\static\index.html is written.

You should not change nothing in dist, it will be always overridden, this is how webpack works, the same happens for any files

**Comment by evilebottnawi** [comment]
Why? Because we should always emit assets, otherwise clean-webpack-plugin/persistent cache/plugins change output after copy-webpack-plugin will not work, also we want to implement auto cleanup dist directory (by option(s)) and it will not work too

**Comment by evilebottnawi** [comment]
> [Issue 2]

> First npm run watch, and then make some changes to static\index.html and save. Now dist\static\index.html should be the same as static\index.html.

> Then change static\index.html again and save. Now dist\static\index.html does not update accordingly.

Yep, it is bug, WIP

**Comment by evilebottnawi** [comment]
Please try https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.3.1

**Comment by felixhao28** [comment]
> You **should not** change nothing in dist

I just want to demonstrate that the files in dist are written again, despite that their sources are not changed.

> Why? Because we should always emit assets,

The first reason is performance. In my case, I need to deploy a web application to the client-side, and therefore need to copy a lot of static files like images and html/css/js, which are rarely changed.

The second reason is webpack hot-reloading (hot module replacement). On Windows, if a file is opened, it will be locked by the OS until it is closed. So with CopyPlugin overwriting all files again and crash if the target file is locked(#548), it kind of defeats the purpose of hot-reloading. This forces me to stop debugging first before making any change to the source.

**Comment by evilebottnawi** [comment]
@felixhao28 Does problem solved by v6.3.1?

**Comment by felixhao28** [comment]
I switched to [sync-directory](https://www.npmjs.com/package/sync-directory) since issue 1 (overwriting every file and crashing hot-reloading server) is a deal-breaker for me.

**Comment by evilebottnawi** [comment]
@felixhao28 Do you try `6.3.1`? when we write the same assets, webpack avoid overwriting

**Comment by felixhao28** [comment]
Just tried `6.3.1` and both issues did not occur to me. Looks good.
