### ISSUE TITLE
ERROR in Conflict: Multiple assets emit different content to the same filename index.html

### ISSUE THREAD

**Issue by 1247748612** [webpack-contrib/copy-webpack-plugin#554]
The bug caused by html-webpack-plugin@next and copy-webpack-plugin@6.3.0.
For details, please see this issue https://github.com/jantimon/html-webpack-plugin/issues/1527#issuecomment-726051008

- Operating System: Windows10
- Node Version: v12.18.2
- NPM Version: v6.11.3
- webpack Version: v5.3.0
- copy-webpack-plugin Version: v6.3.0

### Expected Behavior

normal

### Actual Behavior

ERROR in Conflict: Multiple assets emit different content to the same filename index.html

### How Do We Reproduce?

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-forked-m1sb4?file=/webpack.config.js

**Comment by evilebottnawi** [comment]
Please open an issue in html-webpack-plugin

**Comment by evilebottnawi** [comment]
And you should not emit the same assets with same paths

**Comment by evilebottnawi** [comment]
```
globOptions: {
            ignore: [
              // Ignore all `txt` files
              "**/*index.html"
            ]
          }
```
