### ISSUE TITLE
Watched files are not updated

### ISSUE THREAD

**Issue by naturalfreak** [webpack-contrib/copy-webpack-plugin#557]
os - Ubuntu 20.04
fork-ts-checker-webpack-plugin - 6.0.2
typescript - 4.0.5
webpack - 5.4.0

Using webpack in watch mode with combination with ForkTsCheckerWebpackPlugin and CopyPlugin,
watched files by CopyPlugin are not recompiled after change.
[Here small part of project files](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/files/5545187/forkplugin.zip), 
to run project:
npm install
npm run start:dev - to start webpack in watch mode
if you change file languages/lang.json, managed by CopyPlugin, file is not recompile.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
Anyway please try https://github.com/webpack-contrib/copy-webpack-plugin/releases/tag/v6.3.2

**Comment by naturalfreak** [comment]
it's okay now

**Comment by evilebottnawi** [comment]
But you will still ahve some problems with watching due https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/540, if you add new file to directory, it will not rerun compilation
