### ISSUE TITLE
build  TypeError: compilation.fileDependencies.push is not a function

### ISSUE THREAD

**Issue by lllomh** [webpack-contrib/copy-webpack-plugin#559]
hello  
There is an error in this version, which will be reported when build. I found that it is necessary to delete this line to execute build

**Comment by lllomh** [comment]
4.0.1

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by lllomh** [comment]
OK, I'll submit a pull requests give you
