### ISSUE TITLE
Error: optimize is not defined

### ISSUE THREAD

**Issue by UglyHobbitFeet** [webpack-contrib/copy-webpack-plugin#560]
- Operating System: Centos7
- Node Version: 14.5.1
- NPM Version: 6.14.8
- webpack Version: ?
- copy-webpack-plugin Version: 6.3.2

### Expected Behavior

Comments get stripped from external javascript file(s)

I followed the tutorial here: https://webpack.js.org/plugins/copy-webpack-plugin/#transform

### Actual Behavior

I get 'Error: optimize is not defined' in the console after an npm run build
I added a console log to the transform method to help validate that the correct files being passed in.  This helps validate that CopyPlugin is correctly installed and the transform method is being correctly accessed and passed the correct things.

### Code

```
const CopyPlugin = require("copy-webpack-plugin");
module.exports = {
  configureWebpack: {
    plugins: [
      new CopyPlugin({
        patterns: [
          {
            from: "public/foo/*.js",
            to: "dist/",
            transform(content, absoluteFrom) {
              console.log('transform from', content, absoluteFrom);
              return Promise.resolve(optimize(content));
            },
          },
        ],
    }),
  ],  
},

```

### How Do We Reproduce?

``` npm run build ```

**Comment by evilebottnawi** [comment]
Because you need `optimize` function, please read how JS working

**Comment by evilebottnawi** [comment]
It is just function with the `optimize` name, there is no logic for this

**Comment by evilebottnawi** [comment]
You need to implement itself it, if you want to strip comments, you need to use `terser-webpack-plugin`

**Comment by UglyHobbitFeet** [comment]
Got it. I didn't see it in italics or anything special in the docs saying we need to fill it in with something else, and thought it was an actual method.
