### ISSUE TITLE
Upgrading from v6.1.1 to 6.2.0 (or any version above 6.2.0) introduces TypeError: callbacks[i] is not a function error

### ISSUE THREAD

**Issue by luke-denton-aligent** [webpack-contrib/copy-webpack-plugin#568]
- Operating System: Centos 7
- Node Version: 12.16.1
- NPM Version: 6.14.1
- webpack Version: 
- copy-webpack-plugin Version: 6.2.0

### Expected Behavior

Files copied without any error being displayed

### Actual Behavior

When using v6.2.0, 
```
92% additional asset processing copy-webpack-plugin/home/luke.denton/sites/PWA/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55
			callbacks[i](err, result);
			            ^

TypeError: callbacks[i] is not a function
    at Storage.finished (/home/luke.denton/sites/PWA/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/luke.denton/sites/PWA/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/luke.denton/sites/PWA/node_modules/enhanced-resolve/lib/NodeJsInputFileSystem.js:12:4
    at go$readdir$cb (/home/luke.denton/sites/PWA/node_modules/graceful-fs/graceful-fs.js:187:14)
    at FSReqCallback.oncomplete (fs.js:154:23)
```

### Code

```js
// webpack.config.js
const staticAssetsCopyPlugin = require('./webpack.staticAssetsCopy');

// ...

clientConfig.plugins.push(staticAssetsCopyPlugin);
```

```js
// webpack.staticAssetsCopy.js
const CopyPlugin = require('copy-webpack-plugin');

module.exports = new CopyPlugin({
    patterns: [{ from: 'static', to: '' }]
});
```

### How Do We Reproduce?

Please see https://github.com/luke-denton-aligent/copy-webpack-plugin-error-repro

There are 2 branches, `v6.1.1` and `v6.2.0`. The only difference between the two branches is the version of `copy-webpack-plugin`.

Check out `v6.2.0`, install dependencies, then run `yarn watch`. The error should appear.

Check out `v6.1.1`, remove node_modules, install dependencies, then run `yarn watch`. The application will build successfully.

### Related

I have found [another issue](https://github.com/webpack-contrib/copy-webpack-plugin/issues/217) that reports this exact error, but that was way back for version 4.4, so I think something has regressed for it to be a problem again.

### Extra

I've had a look at the code difference between copy-webpack-plugin 6.1.1. and 6.2.0, and I can't immediately see what might be causing the issue: https://github.com/webpack-contrib/copy-webpack-plugin/compare/webpack-contrib:v6.1.1...v6.2.0#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556

**Comment by alexander-akait** [comment]
Do you try latest version?

**Comment by alexander-akait** [comment]
Can't reproduce due `TypeError [ERR_INVALID_URL]: Invalid URL: graphql`

**Comment by alexander-akait** [comment]
Try to update `webpack` to latest 4 branch

**Comment by alexander-akait** [comment]
webpack@4 I think problem here https://github.com/webpack-contrib/copy-webpack-plugin/commit/6f2f455b9411ac69ef6aa3b953474f1d7fa23808#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R124, we use built-in webpack fs, so webpack@5 cache fs calls, but for webpack@4 fs doesn't have `lstat` and `lstatSync`, maybe something patch webpack fs

**Comment by alexander-akait** [comment]
Reproduced, WIP

**Comment by alexander-akait** [comment]
Found the problem and the solution, let's fix it

**Comment by alexander-akait** [comment]
Fixed, release will be soon

**Comment by alexander-akait** [comment]
under `6.4.1`

**Comment by luke-denton-aligent** [comment]
@alexander-akait Thank you! I've just tested the latest version in my repro repo and it works perfectly!

Also, apologies for the repro instructions, I did forget about the hidden `.env` file that isn't committed. For completeness sake, we need the following in a `.env` file as well:

```
MAGENTO_BACKEND_URL=https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/
CHECKOUT_BRAINTREE_TOKEN=
```

Thanks again
