### ISSUE TITLE
Version 6 and above copies files generated with compression-webpack-plugin

### ISSUE THREAD

**Issue by hzaben81** [webpack-contrib/copy-webpack-plugin#569]
- Operating System: macOS Catalina 10.15.6
- Node Version: 14.15.0
- NPM Version: 6.14.8
- webpack Version: 5.10.3
- copy-webpack-plugin Version: 6.x, 7.x

### Expected Behavior
According to the README this plugin `is not designed to copy files generated from the build process; rather, it is to copy files that already exist in the source tree, as part of the build process.`.

Therefore I would expect that the plugin should not copy files generated by `compression-webpack-plugin`.

### Actual Behavior
When combining `v6` or `v7` of this plugin with `compression-webpack-plugin`, the compressed file is also copied over. 

This was not the behaviour in prior to `v6`.

### Code
https://github.com/hzaben81/copy-compress-plugin/blob/main/webpack.config.js

### How Do We Reproduce?

I've created a github repo to show the behavior: https://github.com/hzaben81/copy-compress-plugin

It has `v7.0.0` added to `package.json`. Run the script `npm run build`. That will generate a `dist` folder that includes a `gzip` version of the copied file `data.json` set in the plugin.

If you change to `v5.1.2` in `package.json`, run `npm install` and then update the [webpack config file](https://github.com/hzaben81/copy-compress-plugin/blob/main/webpack.config.js) so it's using the correct usage of the plugin, and then run `npm run build` you'll see that it's not copying over the gzipped file.

**Comment by alexander-akait** [comment]
> According to the README this plugin is not designed to copy files generated from the build process; rather, it is to copy files that already exist in the source tree, as part of the build process..

> Therefore I would expect that the plugin should not copy files generated by compression-webpack-plugin.

There is no copying assets from assembly bundling. We just copied asset and then other plugin generate `gz`. Yhis is how it should work.

Yep, it is feature, two solutions if you don't want compressed asset:
- use `exclude` for `compression-webpack-plugin`
- say compression plugin to ignore this

```js
new CopyWebpackPlugin({
      patterns: [
        {
          from: './data.json',
          // Terser skip this file for minimization
          info: { compressed: true },
        },
      ]
    })
```

Example for terser plugin in readme https://github.com/webpack-contrib/copy-webpack-plugin#info

**Comment by thw0rted** [comment]
The `info` field is not currently documented [over at js.org](https://webpack.js.org/plugins/copy-webpack-plugin/).  Where does `compressed: true` come from?  The front page of this repo says `minimized: true`, but I can't find anything about either of those in [the terser plugin docs](https://webpack.js.org/plugins/terser-webpack-plugin/).

**Comment by alexander-akait** [comment]
@thw0rted you can send a PR, we adding example for terser, because it is most popular usage

**Comment by thw0rted** [comment]
I'd be happy to write it up if I understood what's actually going on.  I don't understand enough about Webpack internals to understand what `info` is doing.  Assets that enter the pipeline via copy-plugin somehow incorporate whatever is in `info` into their metadata (?) and so when they get to Terser plugin, it sees that they're already `minimized` and thus ignores them.  Is that right?  Is there a good primer somewhere that I could read that explains all of this?

**Comment by alexander-akait** [comment]
> Assets that enter the pipeline via copy-plugin somehow incorporate whatever is in info into their metadata (?) and so when they get to Terser plugin, it sees that they're already minimized and thus ignores them.

Yes.

Most of plugins (all official do it always) which something do with assets adding key to assets info, for example `terser` added `minimized` for minified JS files, `css-minimizer-webpack-plugin` added `minimized` for CSS files (same for html, json and image minimizer), compression-webpack-plugin added `compressed` to files which was compressed, so if asset have flag (for example, plugin filter it https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L206)
