### ISSUE TITLE
Provide option to copy only unchanged files in watch mode

### ISSUE THREAD

**Issue by aniket7824** [webpack-contrib/copy-webpack-plugin#572]
- Operating System: Windows 10
- Node Version: 12.4.0
- NPM Version: 6.13.0
- webpack Version: 4.44.1
- copy-webpack-plugin Version: 6.0.3

### Feature Proposal
While copy-webpack-plugin is performing in watch mode, it should only copy if the source file has changed. Currently, every time there the build is triggered, the files are getting copied.

### Feature Use Case
It will enable watch mode to only update the files whenever required.

**Comment by alexander-akait** [comment]
Please migrate on webpack@5 and update copy-webpack-plugin to the latest version, no need options, it is already works in this way
