### ISSUE TITLE
[ext] template string should include leading dot as webpack does

### ISSUE THREAD

**Issue by coreyworrell** [webpack-contrib/copy-webpack-plugin#574]
- Operating System: Ubuntu
- Node Version: 14.2.0
- NPM Version: 6.14.7
- webpack Version: 5.11.1
- copy-webpack-plugin Version: 7.0.0

### Expected Behavior

The `[ext]` template string would be replaced with the file extension _including_ the leading `.` (dot) as [webpack itself does](https://webpack.js.org/configuration/output/#template-strings)

### Actual Behavior

The `.` (dot) is not included. In my case, I use a function to generate filenames, and I can't use the same function for webpack's `output.filename` option as I can for copy-webpack-plugin `patterns[].to`. This leads to files like `examplesvg` instead of `example.svg`.

### Code

```js
// webpack.config.js
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
    output: {
        filename: '[name].js',
        assetModuleFilename: '[name][ext][query]',
    },
    plugins: [
        new CopyWebpackPlugin({
            patterns: [
                {
                    from: './assets/images',
                    to: '[name][ext]',
                },
            ],
        }),
    ],
}
```

**Comment by coreyworrell** [comment]
This may actually be a bug with the new `output.assetModuleFilename` option. It seems to behave differently than the `output.filename` option.

**Comment by alexander-akait** [comment]
Yes, but it will be big breaking change, only for the next major release

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/copy-webpack-plugin/pull/589
