### ISSUE TITLE
TypeError: compilation.getCache is not a function

### ISSUE THREAD

**Issue by Iffyyy** [webpack-contrib/copy-webpack-plugin#575]
i install this plugin with npm in my vue project,and configured in vue.config.js.when i start the project,it told me that 'TypeError: compilation.getCache is not a function' at 'copy-webpack-plugin\dist\index.js:459:33'

**Comment by killtheliterate** [comment]
@Iffyyy I hit this after a fresh install `npm i copy-webpack-plugin` — that'll install v7 of the plugin, which requires webpack 5. I'm not using webpack 5, and resolved by `npm i copy-webpack-plugin@6`.

**Comment by sarink** [comment]
Something stating "v6 of this plugin works with webpack v4" really needs to be added to the README.

**Comment by alexander-akait** [comment]
Please do not ignore messages from package manager you need webpack@5 for latest version

**Comment by AzrizHaziq** [comment]
Hi, i'm using `copy-webpack-plugin@6.4.1` and `webpack@5.16.0` works charmingly. 
For `copy-webpack-plugin@7.0.0` and `webpack@5.16.0` still got error `compilation.getCache`.

**Comment by alexander-akait** [comment]
@AzrizHaziq it means you still on `webpack@4`, run `npm ls webpack`

**Comment by AzrizHaziq** [comment]
@alexander-akait 

```
├─┬ copy-webpack-plugin@6.4.1
│ └── webpack@5.16.0 deduped
├─┬ size-plugin@2.0.1
│ └── webpack@5.16.0 deduped
├─┬ terser-webpack-plugin@5.1.1
│ └── webpack@5.16.0 deduped
├─┬ webpack-cli@3.3.12
│ └─┬ webpack@4.46.0
│   └─┬ terser-webpack-plugin@1.4.5
│     └── webpack@4.46.0 deduped
├── webpack@5.16.0
└─┬ xo@0.32.1
  └─┬ eslint-import-resolver-webpack@0.12.2
    └── webpack@5.16.0 deduped
    ```

**Comment by alexander-akait** [comment]
update `webpack-cli` to the 4 version

**Comment by AzrizHaziq** [comment]
I think i mess up a little bit. I'm currently using `lerna`, and strangely it was using `webpack@4.*`.
Please ignore my previous comment 😄 .

Thanks @alexander-akait.

**Comment by denis-sokolov** [comment]
I experience this with newest versions of everything: copy-webpack-plugin@9.0.0, webpack@5.39.0, webpack-cli@4.7.2.

**Comment by omarceloribeiro** [comment]
> @Iffyyy I hit this after a fresh install `npm i copy-webpack-plugin` — that'll install v7 of the plugin, which requires webpack 5. I'm not using webpack 5, and resolved by `npm i copy-webpack-plugin@6`.

that worked for my [issue ](https://github.com/omarceloribeiro/spfxblazorwebpart/issues/6)with spfx projetct! thank so much!!
