### ISSUE TITLE
[Bug] Cannot copy *.js files in production mode without running them through a minimizer

### ISSUE THREAD

**Issue by ddx32** [webpack-contrib/copy-webpack-plugin#576]
Hi, thanks for the work done over the years on this plugin. We started getting build issues upon upgrading to webpack 5 and copy-webpack-plugin 7.0.0 which seem to emerge from an unexpected side-effect in webpack.

- Operating System: macOS 11.1
- Node Version: 14.15.1
- NPM Version: 6.14.11
- webpack Version: 5.16.0
- copy-webpack-plugin Version: 7.0.0

### Expected Behavior

Files matching the copyWebpackPlugin patterns are copied over to their destinations without modification or analysis.

### Actual Behavior

If a file has a `.js` suffix and webpack is set to production mode, the file is passed through a minimizer (Terser by default) which parses the file. If the syntax is invalid, Terser throws an error and fails the build. It is the destination filename that triggers this behavior.

### Code

[Here is a repo](https://github.com/ddx32/copyWebpackPluginTerserError) with a minimal example to reproduce this bug.

Upon running `npx webpack` in the project directory, the build fails with:

```
ERROR in assets/invalidScript.js from Terser
Unexpected token: name (is) [assets/invalidScript.js:1,5]
```

### How Do We Reproduce?

* Clone the aforementioned repo
* run `npx webpack`

I understand this is an edge case, but it's vital in our workflow. Any guidance on this issue is much appreciated.

Cheers

**Comment by alexander-akait** [comment]
Two ways:
- Adding `TerserPlugin` to your config and use `test`/`include`/`exclude`
- https://github.com/webpack-contrib/copy-webpack-plugin#info (it has example for terser)

**Comment by alexander-akait** [comment]
And it is not bug, expected, because all assets should be processed, otherwise images or other assets will not compressed and it is described by many developers as bug

**Comment by ddx32** [comment]
@alexander-akait thank you! I was sure I went through as many docs as I could find, but this slipped my attention. I now agree this is expected behavior, closing the issue ;)

**Comment by alexander-akait** [comment]
@ddx32 maybe we can duplicate it to `Examples`, feel free to send a PR

**Comment by ddx32** [comment]
@alexander-akait thanks, I'll see what I can do.

**Comment by creage** [comment]
@alexander-akait I'm having the same issue with my sources I copy, and I found this issue. Just to let you (and others) know - the `info: { minimized: true }` **does not** make Terser to skip my files, but the `info: (file) => ({ minimized: true })` does.

I'm very sorry for spamming here, but I thought it would be nice to keep issues at one place.
