### ISSUE TITLE
webpack build failed when copy 6 videos with a total size of about 1G

### ISSUE THREAD

**Issue by YanYuanFE** [webpack-contrib/copy-webpack-plugin#579]
- Operating System: windows 10
- Node Version: 12
- NPM Version: 
- webpack Version: 4
- copy-webpack-plugin Version: 5.1.1

### Expected Behavior
 build success 

### Actual Behavior

copyPlugin 95%
 failed
Array buffer allocation failed

### Code

```js
// webpack.config.js
// If your code blocks are over 20 lines, please paste a link to a gist
// (https://gist.github.com).
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by alexander-akait** [comment]
You need to increase the memory of the Node.js https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
