### ISSUE TITLE
Doesn't support [fullhash]

### ISSUE THREAD

**Issue by strarsis** [webpack-contrib/copy-webpack-plugin#582]
- Operating System:
- Node Version: `v14.15.4`
- NPM Version: `7.5.3`
- webpack Version: `5.21.2`
- copy-webpack-plugin Version: `7.0.0`

### Expected Behavior
` [fullhash]` sould be interpolated as with `[hash]`.
`[hash]` has been deprecated by webpack 5 in favor of `[fullhash]`.

### Actual Behavior
`[fullhash]` is not interpolated and kept as placeholder in the file name.

### How Do We Reproduce?
`webpack.config.js`:
```js
// ...
    new CopyPlugin({
      patterns: [
        {
          from: './src',
          to: '[path][name]_[fullhash].[ext]',
        },
      ],
    }),
//...
````

**Comment by alexander-akait** [comment]
copy-webpack-plugin doesn't support `[fullhash]`, please look at docs, use `contenthash`, it is limitation, we need some improvements in webpack and we are working on it, we will fix it in the next major release, let's close in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/574, `[ext]` is broken too

**Comment by strarsis** [comment]
@alexander-akait: Thanks! So I will use `[contenthash]` instead of `[fullhash]` which is not deprecated.
What should be used instead of `[ext]`? Or can it be used when it doesn't cause issues?

**Comment by alexander-akait** [comment]
> Or can it be used when it doesn't cause issues?

`[ext]` can be used, here bug, we ask to write `.` (dot) for `[ext]`, but we will write changelog when it was changed in the next major release

**Comment by strarsis** [comment]
@alexander-akait: Ah, so the need to explicitly prepend a file extension dot (`.`) is the actual issue.

**Comment by alexander-akait** [comment]
Yep, we will fix it
