### ISSUE TITLE
Path from glob not correctly used in manifest

### ISSUE THREAD

**Issue by strarsis** [webpack-contrib/copy-webpack-plugin#583]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
The from-path of a glob isn't correctly prepended in the manifest. 
Example:
```js
// [...]
    new CopyPlugin({
      patterns: [
        {
          from: 'images/**/*',
          noErrorOnMissing: true,
          to: '[path][name]_[contenthash].[ext]',
        },
      ],
    }),
// [...]
````
The files in `images/` are copied into the target directory in their own `images/` subdirectory.
However, the resulting manifest file lists these files without the `images/` subdirectory.
`./assets/images/svg/test.svg` → `./dist/images/svg/test.svg` - That is OK.
`manifest.json`:
```json
"svg/test.svg": "images/svg/test_8d1cd1127fdd86a4657c56ecvnfe16ca.svg",
````
`dist/images/` is missing from the path in the manifest.

### Your Proposal for Changes
What options have to be added to ensure the manifest is correctly in sync with the copied files.

**Comment by alexander-akait** [comment]
You need to open an issue in `manifest-webpack-plugin`, there is nothing fix on `copy-webpack-plugin`

**Comment by alexander-akait** [comment]
We just emit original path and transformed path to relative to `context`, maybe you need some options for manifest plugin

**Comment by strarsis** [comment]
@alexander-akait: OK, I created a new issue in that repository.
