### ISSUE TITLE
Types of parameters "compiler" and "compiler" are incompatible

### ISSUE THREAD

**Issue by SamuelTrew** [webpack-contrib/copy-webpack-plugin#599]
- Operating System: Ubuntu 20.04
- Node Version: 12.15.0
- NPM Version: 6.14.8
- webpack Version: 5.28.0
- copy-webpack-plugin Version: 8.1.0

### Expected Behavior

It should just run normally and copy the files

### Actual Behavior

Gives an error of `Types of property 'apply' are incompatible`, `Types of parameters 'compiler' and 'compiler' are incompatible` and that `Property '_pluginCompat' is missing in type {webpack/types}.Compiler but required in type {@types/copy-webpack-plugin/node_modules/@types/webpack/index}.Compiler`.

### Code

```js
new CopyPlugin({
         patterns: [{ from: path.resolve(__dirname, "public", "_redirects"), to: "dist" }],
}),
```

### How Do We Reproduce?

Just use the copy plugin as provided with the latest webpack, webpack types and copy versions

Thanks!

**Comment by alexander-akait** [comment]
We don't have types here right now, we will improve this in future, please open an issue in https://github.com/DefinitelyTyped/DefinitelyTyped
