### ISSUE TITLE
Shouldn't we use PROCESS_ASSETS_STAGE_ADDITIONAL instead of PROCESS_ASSETS_STAGE_ADDITIONS?

### ISSUE THREAD

**Issue by slavafomin** [webpack-contrib/copy-webpack-plugin#600]
I was looking into the code of this plugin and found some discrepancy here:
https://github.com/webpack-contrib/copy-webpack-plugin/blob/dde71f01417b9291c7029a3876e043d76beb9e8d/src/index.js#L615-L619

The plugin uses the `PROCESS_ASSETS_STAGE_ADDITIONS` stage when tapping into the `processAssets` hook. However, this stage is described as the following [in the docs](https://webpack.js.org/api/compilation-hooks/#processassets):

> `PROCESS_ASSETS_STAGE_ADDITIONS` - Add additional sections to the existing assets e.g. banner or initialization code.

Considering that the plugin `copies individual files or entire directories` and not `adds additional sections to the existing assets` shouldn't we use the `PROCESS_ASSETS_STAGE_ADDITIONAL` stage? It looks more appropriate for this use case:

> `PROCESS_ASSETS_STAGE_ADDITIONAL` - Add additional assets to the compilation.

**Comment by alexander-akait** [comment]
Yep, you are right, we need switch on `PROCESS_ASSETS_STAGE_ADDITIONAL`

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack-contrib/copy-webpack-plugin/pull/601
