### ISSUE TITLE
globOptions.ignore error

### ISSUE THREAD

**Issue by shenyue** [webpack-contrib/copy-webpack-plugin#603]
`from: "public",            
                    globOptions: {
                        ignore: [
                            "**/.DS_Store", // ok
                            "**/index.html", // ok
                            "**/index2.html", // ok
                            "**/abc.txt", // error
                        ],
                    }
`

ERROR in unable to locate '/Users/bailong/Desktop/p_web/webpack/02/public/**/*' glob

webpack 5.32.0 compiled with 1 error in 1274 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 02@1.0.0 build: `webpack --config wk.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 02@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bailong/.npm/_logs/2021-04-16T06_20_57_879Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle 02@1.0.0~prebuild: 02@1.0.0
6 info lifecycle 02@1.0.0~build: 02@1.0.0
7 verbose lifecycle 02@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle 02@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/bailong/Desktop/p_web/webpack/02/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/sbin
9 verbose lifecycle 02@1.0.0~build: CWD: /Users/bailong/Desktop/p_web/webpack/02
10 silly lifecycle 02@1.0.0~build: Args: [ '-c', 'webpack --config wk.config.js' ]
11 silly lifecycle 02@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle 02@1.0.0~build: Failed to exec build script
13 verbose stack Error: 02@1.0.0 build: `webpack --config wk.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid 02@1.0.0
15 verbose cwd /Users/bailong/Desktop/p_web/webpack/02
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.15.4
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error 02@1.0.0 build: `webpack --config wk.config.js`
22 error Exit status 1
23 error Failed at the 02@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Respect time of other developers.

> ERROR in unable to locate '/Users/bailong/Desktop/p_web/webpack/02/public/**/*' glob

You don't have `/Users/bailong/Desktop/p_web/webpack/02/public` directory
