### ISSUE TITLE
Module not found: Error: Can't resolve './src'

### ISSUE THREAD

**Issue by web-programmer-here** [webpack-contrib/copy-webpack-plugin#608]
- Node Version: 12.21
- NPM Version: 6.14
- webpack Version: 5
- copy-webpack-plugin Version: latest

### Expected Behavior

Need to copy images from src file to dist file

### Actual Behavior

When trying to copy the entire asset folder (which contains images and svg icons), I get an error

```
ERROR in main
Module not found: Error: Can't resolve './src'
Field 'browser' doesn't contain a valid alias configuration
```

### Code

```js
const CopyPlugin = require("copy-webpack-plugin");
.....
const images = {
  plugins: [
    new CopyPlugin({
      patterns: [
        { 
          from: 'src/admin/assets/*',
          to: 'dist/admin/assets/*'
        },
      ],
    }),
  ]
};

module.exports = [
  mainConfig, images
];
```

Am I doing something wrong here that I can't copy the entire folder from `src` to `dist`? My `webpack.config.js` is in the src folder.

**Comment by web-programmer-here** [comment]
My folder structure is like this

```
Main-Folder
--dist
--src
   webpack.config.js
   --admin
       -- assets
            icon.svg
            photo.jpg
```

**Comment by alexander-akait** [comment]
Not related to copy-webpack-plugin, sorry

You have broken library with `browser` field, you ignore `How Do We Reproduce?` so I can't show how to fix it, you can fill out `How Do We Reproduce?` section and I will help
