### ISSUE TITLE
Security vulnerability in dependency glob-parent

### ISSUE THREAD

**Issue by hellmelt** [webpack-contrib/copy-webpack-plugin#611]
- Operating System: MacOS Big Sur
- Node Version: 14.17.0
- NPM Version: 6.14.13
- yarn version: 1.22.10
- webpack Version: 5.38.1
- copy-webpack-plugin Version: 9.0.0

### Expected Behavior

yarn audit reports no security vulnerabilities

### Actual Behavior

yarn audit reports a modera security risk in glob-parent
https://www.npmjs.com/advisories/1751

copy-webpack-plugin > globby > fast-glob > glob-parent
image-webpack-loader > imagemin > globby > fast-glob > glob-parent

### How Do We Reproduce?
Use copy-webpack-plugin 9.0.0 in a project.
Run yarn audit or npm audit.

**Comment by alexander-akait** [comment]
Sorry we can't fix it here, please open an issue in `fast-glob`, also:
```
5.1.2
3 months ago
6.0.0
a month ago
```

is not affected, please update your deps locally `npm update`
