### ISSUE TITLE
ObjectPattern interface is missing `transformAll`

### ISSUE THREAD

**Issue by lukenofurther** [webpack-contrib/copy-webpack-plugin#612]
- Operating System: MacOS Catalina
- Node Version: 14.15.3
- NPM Version: 6.14.9
- webpack Version: 5.39.0
- copy-webpack-plugin Version: 9.0.0 (@types/copy-webpack-plugin: @8.0.0)

### Expected Behavior

Typescript recognition of `tranformAll` option passed to `new CopyWebpackPlugin`.

### Actual Behavior

Error: `Object literal may only specify known properties, and 'transformAll' does not exist in type 'ObjectPattern'.ts(2322)`

### Code

```ts
new CopyWebpackPlugin({
  patterns: [{
    from: '../repo/public/locales/**/*',
    to: 'data/tokens.js',
    transformAll(files) {
      let merged = {};

      files.forEach((file) => {
        merged = {
          ...merged,
          ...JSON.parse(file.data.toString()),
        };
      });

      return `window.tokens = ${JSON.stringify(merged, null, 2)}`;
    },
  }],
}),
```

### How Do We Reproduce?
Include the above in a typescript webpack config file.

**Comment by lukenofurther** [comment]
I see that `tranformAll` is a very recent addition. Great addition btw, very useful.

**Comment by alexander-akait** [comment]
Please use https://www.npmjs.com/package/@types/copy-webpack-plugin to avoid ts errors, we don't have types right now here, but it is in our roadmap
