### ISSUE TITLE
Help: Could you tell me why this plugin can not ignore the corresponding files

### ISSUE THREAD

**Issue by luckyjolly** [webpack-contrib/copy-webpack-plugin#623]
```js
new CopyWebpackPlugin({
  patterns: [{
    from: path.resolve(__dirname, '../static'),
    to: 'static',
    globOptions: {
      ignore: ['.*'] 
    }
  }]
})
```
copy-webpack-plugin version: 9.0.1

At frist, I set the value of 'igore' option to ['.*']. I just wanted to ignore the files start with dot. But failed. The result is shown in f ollowing image:
![image](https://user-images.githubusercontent.com/16423464/130027019-f618978c-121e-4878-bcf1-1ee8b6b58ba6.png)
As the result, those files 'static/.gitkeep' and 'static/.html' was copyed to the directory 'dist/statc/'.
Then I changed the value of 'ingore' to ['.*', '.gitkeep'], also failed.
Then I changed the value of 'ingore' to ['.*', '**.gitkeep'], and I igored the file '.gitkeep' successfully.
At last, I also tried this values ['*.*'], ['*.**'], ['**.**'], ['**.*'], all failed. And now, I can't understand the following rules.
![image](https://user-images.githubusercontent.com/16423464/130028540-bcd4ac06-0562-41f8-ba74-51c94de4acf4.png)

**Comment by alexander-akait** [comment]
Ask this in `globby`/`fast-glob` package, we use it under the hood

**Comment by zjjjjjjjjjjd** [comment]
some problem
