### ISSUE TITLE
Examples of patterns are confusing

### ISSUE THREAD

**Issue by scott-ln** [webpack-contrib/copy-webpack-plugin#628]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [x] Confusing
- [ ] Not Sure?

### Please Explain in Detail...

The plugin's signature is described as containing:
```js
      patterns: [
        { from: "source", to: "dest" },
        { from: "other", to: "public" },
      ],
```

This implies that a "pattern" is an object with `from` and `to` values. But in the section titled `webpack.config.js` the following example is given:

```js
      patterns: [
        "relative/path/to/file.ext",
        "relative/path/to/dir",
        path.resolve(__dirname, "src", "file.ext"),
        path.resolve(__dirname, "src", "dir"),
        "**/*",
        {
          from: "**/*",
        },
        path.posix.join(
          path.resolve(__dirname, "src").replace(/\\/g, "/"),
          "*.txt"
        ),
      ],
```

What are these strings for? Are they sources or destinations, and what distinguishes those?

### Your Proposal for Changes

Please explain the above more clearly. Thank you.

**Comment by alexander-akait** [comment]
By default we copy files in your `output.path`, if you need to change path you need to use `{ from: "source", to: "dest" }`

**Comment by scott-ln** [comment]
So would you please update the documentation to make that clear? I'm not just asking for myself but anyone else who might have the same question.

**Comment by alexander-akait** [comment]
I don't understated what you don't understand, please clarify

**Comment by alexander-akait** [comment]
> What are these strings for? Are they sources or destinations, and what distinguishes those?

Source, for any copy tools you provide firstly source of files

Here files/directories/globs

**Comment by scott-ln** [comment]
OK, thank you, that is clear. May I suggest that you update the description of the plugin's signature to something like this?

```js
      patterns: [
        { from: "source", to: "dest" },
        "path/to/source", // absolute or relative, files/directories/globs - see below for examples
      ],
```

Thanks again.

**Comment by alexander-akait** [comment]
PR welcome, it is easy

**Comment by scott-ln** [comment]
Sorry, I can't. My employer's bureaucracy is incompatible with the CLA process required to make a pull request to this project.
