### ISSUE TITLE
0kb copied file after electron make

### ISSUE THREAD

**Issue by zbouslikhin** [webpack-contrib/copy-webpack-plugin#630]
Hi,

I'm trying to copy a folder that contains a bunch of zip files.
I'm using electron forge for production and so building goes as expected, but when trying to install the generated installer, it crashes right when trying to copy the very first zip file found inside of the directory

```js
const rendererPlugins = [
    new CopyWebpackPlugin({
        patterns: [
            {
                from: path.resolve(__dirname, "src", "demo"), // demo is the folder full of zips
                to: path.resolve(__dirname, ".webpack", "test"),
                noErrorOnMissing: true
            }
        ]
    }),
]
```

Any help is much appreciated!

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Sorry I can't help your without more infromation
