### ISSUE TITLE
How to prohibit automatic license split 

### ISSUE THREAD

**Issue by MandaJC** [webpack-contrib/copy-webpack-plugin#633]
Documentation Is:https://webpack.js.org/plugins/copy-webpack-plugin/#getting-started

- [x] Missing
- [x] Needed
- [ ] Confusing
- [ ] Not Sure?

### Your Proposal for Changes
My version information：
![image](https://user-images.githubusercontent.com/37771526/138209991-4726d903-f54c-4f04-9d57-326032e121df.png)

Before：
When I use copy-webpack-plugin, it will copy the original file

Now：
e.g. jquery
When I use copy-webpack-plugin, it will copy and then split the original file, like this:

Original file:
![image](https://user-images.githubusercontent.com/37771526/138210259-a9690a66-8ea2-46d0-8603-3d0d460f0613.png)

After using copy-webpack-plugin：
![image](https://user-images.githubusercontent.com/37771526/138210301-1603eeec-107e-472c-a7b6-1c0bc4470835.png)
![image](https://user-images.githubusercontent.com/37771526/138210339-2acb6302-610a-4b56-862a-bf474c1f017f.png)

I just want the original file, so how should I configure it？

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments
