### ISSUE TITLE
BUG? Copied TypeScript-Files are not considered by the compiler

### ISSUE THREAD

**Issue by githtz** [webpack-contrib/copy-webpack-plugin#635]
I'm using the `copy-webpack-plugin@6.4.1` with `webpack@4.44.1` to copy some typescript files from another location into my project.
```js
new CopyPlugin({
	patterns: [
		{
			from: path.resolve(__dirname, "../../../some-other-project/some-dir/some-typescript-module.*"),
			to: path.resolve(__dirname, "some-dir/some-typescript-module.[ext]")
		},
	],
}),
```
Expectation:
When running `> webpack`, the copied files should be used in the compilation.

Actual behavior:
When running  `> webpack` the first time, the copied TypeScript module is not found, but the files are copied. When running `> webpack` a second time, the already copied sources are found used in the compilation.

**Comment by alexander-akait** [comment]
No, expected, we don't add them to graph, you should import them in `ts` files, this plugin just for copy files

**Comment by githtz** [comment]
Alrighty, thanks for the clarification :)
