### ISSUE TITLE
watch file not working in watch mode

### ISSUE THREAD

**Issue by youngwind** [webpack-contrib/copy-webpack-plugin#64]
As readme says:

>  By default, we only copy modified files during a watch or webpack-dev-server build.

But it's not working in my project. Here is the webpack.config.js

```
var webpack = require('webpack');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var path = require('path');

module.exports = {
    watch: true,
    entry: './deal/static/js/index.js',
    output: {
        path: './dist',
        filename: 'build.js'
    },
    plugins: [

        new CopyWebpackPlugin([
            {
                from: 'deal/page/index.html',
                to: 'index.html'
            }
        ])
    ]
};
```

PS: the index.html copied to the dist directory successfully, but can not watch the index.html.
Any suggestion will be helpful.

**Comment by mikevaleriano** [comment]
+1

**Comment by kevlened** [comment]
I'd enable debugging (`info` level) with the latest version of the plugin (v4.0.0). Are you using webpack-dev-server or `--watch`?

**Comment by Bnaya** [comment]
I have the same issue here

**Comment by denizdogan** [comment]
@Bnaya Thank you very much, I didn't realize that! Someone™ should add Something™ to the documentation about this :)

**Comment by jyane** [comment]
:+1:
This bug is still remaining

**Comment by jyane** [comment]
sorry, it was already fixed. It seems working.

**Comment by michael-ciniawsky** [comment]
Reopen if still regressions
