### ISSUE TITLE
error Command failed with exit code 1 (webpack 5)

### ISSUE THREAD

**Issue by olegKusov** [webpack-contrib/copy-webpack-plugin#644]
### Actual Behavior

When use webpack 5 with copy-webpack-plugin on yarn start (dev server start) it throws error "error Command failed with exit code 1".

### Expected Behavior

No error

### How Do We Reproduce?

[Link to webpack config](https://gist.github.com/olegKusov/b12a5bb74f76fa79013b4bf473ed949e)

System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 71.33 MB / 16.00 GB
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0.1
    Safari: 15.0
  Packages:
    clean-webpack-plugin: ^4.0.0-alpha.0 => 4.0.0-alpha.0 
    copy-webpack-plugin: ^10.0.0 => 10.0.0 
    css-minimizer-webpack-plugin: ^3.0.2 => 3.0.2 
    html-webpack-plugin: ^5.3.2 => 5.3.2 
    webpack: ^5.46.0 => 5.46.0 
    webpack-cli: ^4.7.2 => 4.7.2 
    webpack-dev-server: ^3.11.2 => 3.11.2 
    webpack-dotenv-plugin: ^2.1.0 => 2.1.0

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/copy-webpack-plugin/issues/643, bug in yarn, sorry, we can't fix it here
