### ISSUE TITLE
segmentation fault in import("globby") when running under jest since 10.0

### ISSUE THREAD

**Issue by wood1986** [webpack-contrib/copy-webpack-plugin#646]
### Bug report

My jest test will create webpack and webpackDevServer. And my webpack config will use copy-webpack-plugin. After upgrading to 10.0, it does not running any tests. I found that import("globby") causing this issue

I think it is related to this issue https://github.com/nodejs/node/issues/35889

On this consumer side, this package lives in node_modules and jest cannot transform it. Maybe you should transform it before publish

### Actual Behavior

When I use `node --experimental-vm-modules ./node_modules/jest/bin/jest.js`

it shows

```
16710 segmentation fault  node --experimental-vm-modules ./node_modules/jest/bin/jest.js
```

### Expected Behavior

it should not have segmentation fault

**Comment by mariusvirb** [comment]
I'm experiencing the same

**Comment by alexander-akait** [comment]
Yes, bug in jest and Node.js, sorry we can't fix it here, please read you can ping Node.js/v8 developer in https://github.com/nodejs/node/issues/35889, we switched to ESM version globby because new version in ESM and we should move to ESM

**Comment by wood1986** [comment]
But you may block people from using the latest version if you have features or bug fix afterwards.

**Comment by alexander-akait** [comment]
But how I should fix it? I can't fix v8/Node.js bug here, revert to non ESM old version is not acceptable

**Comment by mariusvirb** [comment]
Thanks @alexander-akait for the info!
I'm experiencing this in v16.11.1, seems really like node issue :cry: will try to find a working node version, otherwise we're stuck with v9 for time being/

**Comment by alexander-akait** [comment]
@mariusvirb For tests purpose you can bundle globby/transpile to commonjs, we use it https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/globalSetup.js#L30 for testing, yes this is a very sad problem, my comment on it https://github.com/nodejs/node/issues/35889#issuecomment-949639126

**Comment by mariusvirb** [comment]
thanks @alexander-akait it's not a high priority for us right now, but I'll definitely take a look! Seems a bunch of organizations are affected!
