### ISSUE TITLE
webpack5 hookWebpackError

### ISSUE THREAD

**Issue by viviScript** [webpack-contrib/copy-webpack-plugin#648]
![image](https://user-images.githubusercontent.com/20518195/145344665-48fc20e2-70cf-4ba7-9b94-17d6f5549961.png)

**Comment by guytzaban** [comment]
you need node js version 12 and above

**Comment by viviScript** [comment]
![image](https://user-images.githubusercontent.com/20518195/145368073-6bfda4c8-c408-40a9-ad54-e0f07875214b.png)

**Comment by guytzaban** [comment]
![image](https://user-images.githubusercontent.com/95845750/145372127-fbdcff18-bb2d-441b-bc0b-96415a6437fd.png)

**Comment by snitin315** [comment]
@viviScript `node >= 12.20.0`
https://github.com/webpack-contrib/copy-webpack-plugin/blob/568a66ccca7afe8776664b3d0c456105a96012f3/package.json#L16

**Comment by alexander-akait** [comment]
Answer above, please use thee issue template in future to do better communication, please update Node.js version, you need support dynamic import
