### ISSUE TITLE
webpack-dev-middleware support

### ISSUE THREAD

**Issue by patriciussanctus** [webpack-contrib/copy-webpack-plugin#65]
i use serve webpack-dev-middleware, how i can use copy-webpack-plugin?

**Comment by acanimal** [comment]
+1 

I'm in the same situation. I have a universal app where pages are served by my own express app though the use of webpack-dev-middleware and the plugin is not executed.

**Comment by kevlened** [comment]
If you're writing to an absolute path, there was an issue prior to v4.0.0. If upgrading to the latest version doesn't fix your problem, enable debugging (info level) to investigate.

**Comment by michael-ciniawsky** [comment]
If still any regressions in `>= v4.0.0` feel free to reopen 😛
