### ISSUE TITLE
If the project is placed in a folder named "program files (x86)", the file cannot be copied successfully. What should I do

### ISSUE THREAD

**Issue by chenhuifengf8** [webpack-contrib/copy-webpack-plugin#656]
Question:  If the project is placed in a folder named "program files (x86)", the file cannot be copied successfully. What should I do,

Plug in version I used:  "copy-webpack-plugin": "^5.0.5",

Webpack Config:   

  new CopyPlugin([{
            from: path.resolve(process.cwd(), 'app/scripts/util/aa/bb'),
            to: 'dd/'
  }])

**Comment by alexander-akait** [comment]
Please update plugin to the latest version
