### ISSUE TITLE
TypeScript: `{ minimized: true }` is not allowed by type definition.

### ISSUE THREAD

**Issue by babatakao** [webpack-contrib/copy-webpack-plugin#663]
### Bug report

[README](https://github.com/webpack-contrib/copy-webpack-plugin#info) says that `info` takes `{ minimized: true }` option. However, [the type definition](https://github.com/webpack-contrib/copy-webpack-plugin/blob/v10.2.1/types/index.d.ts#L266) only takes `string` value.

### Actual Behavior

This code described in README causes an error `Type 'boolean' is not assignable to type 'string'.ts(2322)` in TypeScript.

```ts
  plugins: [
    new CopyPlugin({
      patterns: [
        "relative/path/to/file.ext",
        {
          from: "**/*",
          // Terser skip this file for minimization
          info: { minimized: true },
        },
      ],
    }),
  ],
```

### Expected Behavior

`info: { minimized: true }` should be a valid `Pattern`.

### How Do We Reproduce?

Write webpack.config.ts in TypeScript and use CopyWebPackPlugin with `info: { minimized: true }` option.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 27.13 GB / 63.75 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.20.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.76)
    Internet Explorer: 11.0.19041.1202
  Packages:
    copy-webpack-plugin: ^10.2.1 => 10.2.1
    fork-ts-checker-webpack-plugin: ^6.5.0 => 6.5.0
    ts-loader: ^9.2.6 => 9.2.6
    webpack: ^5.67.0 => 5.67.0
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-dev-server: ^4.7.3 => 4.7.
```

**Comment by babatakao** [comment]
Thank you for quickly addressing the issue!

I've just tested with 10.2.3, but the problem is not solved. #664 modifies `type CopiedResult`, but the type error seems happen on `type Info` which is not modified. Could you please confirm it again?

**Comment by alexander-akait** [comment]
We have `any` https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/types/index.d.ts#L23

**Comment by babatakao** [comment]
`ObjectPattern.info` references `Info` https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/types/index.d.ts#L268 which still take `[key: string]: string;`.

**Comment by alexander-akait** [comment]
oh, I see, WIP

**Comment by babatakao** [comment]
10.2.4 solves the issue. Thank you again for the quick response!
