### ISSUE TITLE
Skip if already exists

### ISSUE THREAD

**Issue by mikeerickson** [webpack-contrib/copy-webpack-plugin#67]
Is there a switch to skip the copy process if the destination file already exists?
- And check if the destination is the same as source

I have my copy workflow moving bootstrap fonts to destination directory? Not sure if it is work the effort, but if I also perform task for images, etc. it would surely optimize the process.

**Comment by mikeerickson** [comment]
@kevlened ping ;-)

**Comment by kevlened** [comment]
I'm not sure if this would actually speed up the build, because in order to check for changes, you'd have to read every file.

The feature is possible to build though.

**Comment by michael-ciniawsky** [comment]
For watch mode see #91, but to check the `dist` folder before a new run is likely not worth the effort as `@kevlened` already mentioned
