### ISSUE TITLE
JS files modified after copy in webpack production mode

### ISSUE THREAD

**Issue by vidhem** [webpack-contrib/copy-webpack-plugin#670]
### Actual Behavior

When using `copy-webpack-plugin` to copy a simple JS file containing a JS object with keys as quoted string, quotes are stripped if webpack production mode is used. For example, a file with following contents –
```JavaScript
module.exports={'foo':'bar'};
```
is copied as 
```
module.exports={foo:"bar"};
```
While this is a valid JS this could break some assumptions for downstream consumers of this file (It does for us) - for example, when the value is treated as a literal string and used with something like `JSON.parse`

### Expected Behavior
Copy should not be content-aware and just produce files as is. The correct output for example case should be same as source –
```JavaScript
module.exports={'foo':'bar'};
```

### How Do We Reproduce?
Can be reproduced via the following unit test

```JavaScript
it("should copy a js file with same contents in production mode", async () => {
      const compiler = getCompiler({ mode: "production" });

      await runEmit({
        compiler,
        expectedAssetKeys: ["file.js"],
        expectedAssetContent: {
          "file.js": "module.exports={'foo':'bar'};",
        },
        patterns: [
          {
            from: "file.js",
          },
        ],
      });
});
```
(`file.js` is present in `test/fixtures` with contents same as report section)

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
➜  copy-webpack-plugin git:(master) ✗ npx webpack-cli info
npx: installed 50 in 1.404s

  System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 25.46 MB / 8.00 GB
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 15.1
  Packages:
    file-loader: ^6.2.0 => 6.2.0 
    webpack: ^5.68.0 => 5.68.0 
```

**Comment by alexander-akait** [comment]
Because copied files are minified, if you want to prevent - disable minification - https://github.com/webpack-contrib/copy-webpack-plugin#info

**Comment by vidhem** [comment]
Ah, thanks for the quick revert! My bad – Sounds good.
