### ISSUE TITLE
Livereload is not triggered on file change

### ISSUE THREAD

**Issue by alan-agius4** [webpack-contrib/copy-webpack-plugin#674]
### Actual Behavior

Live reload is not triggered on file change

### Expected Behavior

Live reload is triggered on file change

### How Do We Reproduce?
```
git clone https://github.com/alan-agius4/copy-webpack-plugin-issue.git
yarn
yarn webpack-dev-server --open
mv asset/2.jpeg asset/1.jpeg
```

Notice that the image is not changed as live reload is not triggered.

```
  System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 4.29 GB / 64.00 GB
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 91.6.0
    Safari: 15.3
  Packages:
    copy-webpack-plugin: ^10.2.4 => 10.2.4 
    webpack: ^5.70.0 => 5.70.0 
    webpack-cli: ^4.9.2 => 4.9.2 
    webpack-dev-server: ^4.7.4 => 4.7.4 
```

**Comment by alexander-akait** [comment]
Can you reproduce it using 5.69.0?

**Comment by alexander-akait** [comment]
Because we have https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L331

**Comment by alan-agius4** [comment]
I did try that and I still didn't work. I also tried older version like 5.10 and it still didn't work.

**Comment by alan-agius4** [comment]
I asked the user that original reported the issue originally in https://github.com/angular/angular-cli/issues/22751 to provide more about their system.

Did live reload work for you when you tried the reproduction?

**Comment by alexander-akait** [comment]
@alan-agius4 I haven't tried it yet, I've set it to my task, I can look tomorrow, just ask more information as possible

**Comment by alan-agius4** [comment]
Looks like the user that reported the issue is also using Mac.

**Comment by alexander-akait** [comment]
@alan-agius4 Sorry for delay, looks like problem in webpack, because hash of compilation is the same, so dev server doesn't reload page, I have two workarounds, but want to verify it is valid fixes, I will return to this today/tomorrow (waiting answer)

**Comment by alan-agius4** [comment]
Thanks @alexander-akait!

**Comment by alan-agius4** [comment]
Gentle reminder @alexander-akait

**Comment by alexander-akait** [comment]
@alan-agius4 oh, sorry, missed that, put in my TODO for tomorrow

**Comment by Mylogin-info** [comment]
@alexander-akait

Same issue on Windows. Angular 14.

[webpack-dev-server] App updated. Recompiling...
[webpack-dev-server] Nothing changed.

Change in files in the app folder and globel scss files are detected. Change in files in the assets folder are not detected.

![image](https://user-images.githubusercontent.com/16088627/172398151-f3694a9b-cd71-4de8-b4c2-5805acc86c87.png)

**Comment by alexander-akait** [comment]
@alan-agius4 @Mylogin-info bug in webpack-dev-server, we can't fix it here https://github.com/webpack/webpack-dev-server/issues/3794, shorty - update an issue and put example, copy-webapck-plugin does right job, dev server doesn't respect

**Comment by alan-agius4** [comment]
@alexander-akait, thanks let's continue tracking this in https://github.com/webpack/webpack-dev-server/issues/3794

**Comment by Trirandom** [comment]
Same issue on Windows. Angular 14.

[webpack-dev-server] App updated. Recompiling...
[webpack-dev-server] Nothing changed.

Force those who are looking for a workaround,
I used the package "@angular-builders/custom-webpack": "^14.1.0" that allows to use an extra webpack config, and in this file:

```
module.exports = {
    devServer: {
        watchFiles: ["src/**/*"],
    },
};
```

This solved my issue, hope it helps.
