### ISSUE TITLE
Use the latest version to set the info field The file is still packed and compressed

### ISSUE THREAD

**Issue by mianmalife** [webpack-contrib/copy-webpack-plugin#684]
const CopyPlugin = require("copy-webpack-plugin")

    new CopyPlugin({
      patterns: [
        './configV2.js',
        './library',
        {
          from: '**/*',
          to: 'staticV2',
          info: { minimized: true }
        }
      ]

**Comment by mianmalife** [comment]
I hope I can only copy, not pack and compress  thanks~

**Comment by alexander-akait** [comment]
There is solution to not compress minify files https://github.com/webpack-contrib/copy-webpack-plugin#skip-running-javascript-files-through-a-minimizer
