### ISSUE TITLE
`HookWebpackError: WebAssembly.instantiate(): Out of memory: wasm memory` in version 10.2.4 when nested in a `osc` build pipeline

### ISSUE THREAD

**Issue by Etheryte** [webpack-contrib/copy-webpack-plugin#685]
### Bug report

This is a very convoluted bug that I don't expect anyone to realistically dig after. I'm documenting it for posterity because there's no good Google results for the error message and it took me ages to figure out a solution.  

Running `CopyWebpackPlugin` version 10.2.4 as a part of a Webpack build nested in an [`osc`](https://en.opensuse.org/openSUSE:OSC) build pipeline (such as [uyuni/rel-eng/build-packages-local-obs.sh](https://github.com/uyuni-project/uyuni/blob/master/rel-eng/build-packages-local-obs.sh)) yields the following error:  

```sh
HookWebpackError: WebAssembly.instantiate(): Out of memory: wasm memory
    at makeWebpackError (/home/abuild/rpmbuild/BUILD/spacewalk-web-git-101.8f61615/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/abuild/rpmbuild/BUILD/spacewalk-web-git-101.8f61615/node_modules/webpack/lib/Compilation.js:3059:12
    at eval (eval at create (/home/abuild/rpmbuild/BUILD/spacewalk-web-git-101.8f61615/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:78:1)
    at /home/abuild/rpmbuild/BUILD/spacewalk-web-git-101.8f61615/node_modules/webpack/lib/Compilation.js:510:26
    at /home/abuild/rpmbuild/BUILD/spacewalk-web-git-101.8f61615/node_modules/copy-webpack-plugin/dist/index.js:708:13
```

The issue is not present when running the Webpack build standalone and also not present when the artefacts are simply passed to `osc`, so the problem stems from somewhere in how the two interact even though `osc` doesn't do any anything special besides calling the Webpack build script.  

Downgrading to 5.1.2 fixes the problem. I didn't bisect to a specific version, this was simply the first one I found that doesn't reproduce the issue.  

### How Do We Reproduce?

I recommend you don't try to reproduce, but if you really want to, here's the steps:  

 0. (Run openSUSE or comparable, or do all of this in a comparable VM)
 1. Install `osc` and `tito`
 2. Create an account at [OBS](https://build.opensuse.org/)
 3. Fork `spacewalk-web` on OBS: `osc branch systemsmanagement:Uyuni:Master spacewalk-web`
 4. Check it out: `osc co home:<USERNAME>:branches:systemsmanagement:Uyuni:Master/spacewalk-web`
 5. Clone Uyuni at [this commit](https://github.com/uyuni-project/uyuni/commit/2e3f7d942fc6d738392434b07627c202b66e4f2e)
 6. Install dependencies: `cd uyuni && yarn install`
 7. Run a local build of `spacewalk-web` with `osc` and friends: `/uyuni/rel-eng/build-packages-local-obs.sh --osc_project_wc=/home:<USERNAME>:branches:systemsmanagement:Uyuni:Master --repository=openSUSE_Leap_15.3 --packages=spacewalk-web --osc_api=https://api.opensuse.org`

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

(This is the relevant information for my VM, but the issue reproduces on real hardware too.)

```
  System:
    OS: Linux 5.3 openSUSE Leap 15.3
    CPU: (2) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.85 GB / 9.71 GB
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/bin/npm
```

**Comment by Etheryte** [comment]
Closing as I made this ticket only to document the interaction.

**Comment by alexander-akait** [comment]
Sounds like bug in V8 (or Node.js) due `import(...)` https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L802
