### ISSUE TITLE
keep the directory structure

### ISSUE THREAD

**Issue by DarrenHou1993** [webpack-contrib/copy-webpack-plugin#69]
form：bower_components/ammap/dist/ammap/images;
to : webpack_src/assets/img/theme/vendor;

I hope the result that my directory structure is 'webpack_src/assets/img/theme/vendor/ammap/dist/ammap/images'
but now my directory structure is  ' webpack_src/assets/img/theme/vendor/allfile'。
sometime i also hope the result that my directory structure is  webpack_src/assets/img/theme/vendor/dist/ammap/images.  
Do I express clearly? Forgive me for this rookie. Thank you very much for your help.

**Comment by kevlened** [comment]
There are a few ways to do what you want, but it depends if you want the entire directory, or just the image files.

Entire directory:
```
{
  from: 'bower_components/ammap',
  to: 'webpack_src/assets/img/theme/vendor/ammap'
}
```

Just image files:
```
{
  from: 'bower_components/ammap/dist/ammap/images',
  to: 'webpack_src/assets/img/theme/vendor/ammap/dist/ammap/images'
}
```

I'm curious you're trying to copy to webpack_src before your webpack build, during, or after?
