### ISSUE TITLE
HookWebpackError: Must use import to load ES Module

### ISSUE THREAD

**Issue by tavareshenrique** [webpack-contrib/copy-webpack-plugin#709]
### Bug report

I updated `copy-webpack-plugin` to version `10.2.4` and it started showing the error in the photo below. I'm using version `12.22.7` of `Node`.

![image](https://user-images.githubusercontent.com/27022914/189415724-b5b06a5b-c86e-45f4-aeb4-c74ea6426583.png)

### How Do We Reproduce?

Just try running `copy-webpack-plugin` on version `10.2.4` on `Node` `12.22.7`.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

![image](https://user-images.githubusercontent.com/27022914/189416201-b86359b5-abfd-472c-a8df-a9caa74dda82.png)

**Comment by alexander-akait** [comment]
Sorry, we can't fix it here, we need to use `import(...)` to load `globby` (ESM). Sounds like you override `globby` version or something another

**Comment by KubaLorenc** [comment]
> Sorry, we can't fix it here, we need to use `import(...)` to load `globby` (ESM). Sounds like you override `globby` version or something another

What do you mean you can't fix it here? You have dependency to globby version 13. In version 11 there is no problem, so you should either downgrade globby to v11 or fix the way you import right?

**Comment by alexander-akait** [comment]
We can't downgrade globby because it is breaking change, I recommend to fix the problem on your side, I can help you if you provide me reproducible example
