### ISSUE TITLE
Lack of useful use case

### ISSUE THREAD

**Issue by xKRISTOFx** [webpack-contrib/copy-webpack-plugin#756]
Documentation Is:

- [ ] Missing
- [x] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...
 There is no use case of plugin with TS webpack

### Your Proposal for Changes
Add an example use case with TS

**Comment by evenstensberg** [comment]
Could you be more consise? 

This plugin makes it easier to copy assets like .favicon and external libraries/dependencies that could be created outside webpack but is used in a webapp.

**Comment by xKRISTOFx** [comment]
Actually, this is not the best place to report this.
