### ISSUE TITLE
Resolve Snyk vulnerability warning on 9th Jan from 'serialize-javascript' package

### ISSUE THREAD

**Issue by edwardmyung** [webpack-contrib/copy-webpack-plugin#758]
### Modification Proposal

Update `serialize-javascript` package to version 6.0.2, which doesn't have the vulnerability. See here: https://security.snyk.io/package/npm/serialize-javascript

### Expected Behavior / Situation

No vulnerability present

### Actual Behavior / Situation

Vulnerability is present, as specified here: https://security.snyk.io/vuln/SNYK-JS-SERIALIZEJAVASCRIPT-6147607

**Comment by alexander-akait** [comment]
We have `"serialize-javascript": "^6.0.1"`, i.e. we use `^` so you can update your dependecies locally, just refresh your lock file, feel free to feedback

**Comment by edwardmyung** [comment]
Gotcha, thank you
