### ISSUE TITLE
getCache is not a function

### ISSUE THREAD

**Issue by MrPotatoChips** [webpack-contrib/copy-webpack-plugin#774]
### Actual Behavior

TypeError: compilation.getCache is not a function

### Expected Behavior

{ patterns: [ { from: './node_modules/@pdftron/pdfjs-express-viewer/public', to: './public/pdfjsexpress', } ], options: { concurrency: 100, } }
### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz
    Memory: 5.40 GB / 15.71 GB

  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.22621.1

  Packages:
    cache-loader: ^4.1.0 => 4.1.0
    copy-webpack-plugin: ^12.0.2 => 12.0.2
    css-loader: ^3.6.0 => 3.6.0
    less-loader: ^5.0.0 => 5.0.0
    postcss-loader: ^3.0.0 => 3.0.0
    sass-loader: ^8.0.2 => 8.0.2
    stylus-loader: ^3.0.2 => 3.0.2
    url-loader: ^3.0.0 => 3.0.0
    vue-loader: ^15.9.8 => 15.10.2
    webpack: ^4.44.1 => 4.46.0

**Comment by alexander-akait** [comment]
Sorry, you need to update webpack to version 5 to use the latest version of this plugin
