### ISSUE TITLE
Copying an executable file strips it of its executable flag

### ISSUE THREAD

**Issue by darrenjaneczek** [webpack-contrib/copy-webpack-plugin#786]
### Actual Behavior

When copying a file with executable attributes, its attributes will be stripped on the destination file.

### Expected Behavior

The copied file should have identical attributes to the source file.

### How Do We Reproduce?

When setting this plugin up, set the target file with the executable flag.
Observe that the copy will not retain this flag.

**Comment by alexander-akait** [comment]
duplicate in favor https://github.com/webpack-contrib/copy-webpack-plugin/issues/35
