### ISSUE TITLE
[Feature] Event Hooks

### ISSUE THREAD

**Issue by QWp6t** [webpack-contrib/copy-webpack-plugin#86]
In my particular use case, I'm wanting to take the initial file name and output file name (in my case, hashed), and then use those to write to a manifests file. Having events in this plugin into which I could hook to get the file names would be awesome. There might be other use cases for events in other places as well, which is why I wasn't super specific with my issue title.

So if nothing else, would be possible to [fire an event right about here](https://github.com/kevlened/copy-webpack-plugin/blob/323b1d74ef35ed2221637d8028b1bef854deb523/src/writeFile.js#L83) with perhaps a signature of `function(file){}`?

Then I could use properties on `file` (`relativeFrom` and `webpackTo`, to be specific) to write my manifest.

**Comment by QWp6t** [comment]
I can submit a PR with the event I suggested, if you'd be receptive to it.

**Comment by kevlened** [comment]
I wonder if there's a way to integrate with [webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin) or [webpack-assets-manifest](https://www.npmjs.com/package/webpack-assets-manifest) instead of adding an extra event. This needs more investigation.

**Comment by QWp6t** [comment]
Yes, that's definitely possible. I do it in a [similar plugin that I wrote that's based on yours](https://github.com/roots/sage/blob/alpha4/assets/build/webpack.plugin.copyglobs.js#L72) (I assign the value to the manifest on [L94](https://github.com/roots/sage/blob/alpha4/assets/build/webpack.plugin.copyglobs.js#L94). I made a point to use the same property names as you so that it would be easy to read. As you can see, the manifest object is populated like `{ relativeFrom: webpackTo }`

[How it's used](https://github.com/roots/sage/blob/alpha4/assets/build/webpack.config.js#L122-L128):

```js
const myAwesomeManifest = {};
// ...
  plugins:
    new CopyGlobsPlugin({
      // It would be nice to switch to copy-webpack-plugin, but unfortunately it doesn't
      // provide a reliable way of tracking the before/after file names
      pattern: 'images/**/*',
      output: `[path][name]_[hash:8].[ext]`,
      manifest: myAwesomeManifest,
    }),
    new WebpackAssetsManifest({
      output: 'assets.json',
      assets: config.manifest,
    }),
  ]
```

**Comment by michael-ciniawsky** [comment]
Whats is the status here ? Still any need/interest in resolving this ? :)

**Comment by Levdbas** [comment]
Would love to know the status of this feature as well :)

**Comment by evilebottnawi** [comment]
@Levdbas can you describe use case for this?

**Comment by Levdbas** [comment]
@evilebottnawi , hashing the files for cache busting, adding them to the manifest file and refer to the manifest in my php for the hashed filename.

**Comment by evilebottnawi** [comment]
@Levdbas hashing already supported, maybe manifest is good idea

**Comment by evilebottnawi** [comment]
Seems now it is duplicate `https://github.com/webpack-contrib/copy-webpack-plugin/issues/104`. Feel free to reopen if you think differently.
