### ISSUE TITLE
[Feature] Persisting between full webpack builds

### ISSUE THREAD

**Issue by deiga** [webpack-contrib/copy-webpack-plugin#90]
You do have `copyUnmodified` set to `false` as default, but that cache is never stored anywhere and thus fails to actually cache anything

**Comment by kevlened** [comment]
We do cache, but only between `webpack --watch` and `webpack-dev-server` runs. Persisting between full webpack builds is a good idea though. I'll check out your PR

**Comment by evilebottnawi** [comment]
Impossible to solve on plugin side, should be solved on `globby` side (in theory `globby` should store cache between each run and return values from cache), but it is really hard to implement and i don't think it is increase performance very good. So i will close this issue, feel free to feedback
