### ISSUE TITLE
[Feature] Ignore files in entry point?

### ISSUE THREAD

**Issue by colepatrickturner** [webpack-contrib/copy-webpack-plugin#93]
Hello!

I'm wondering if it's possible to ignore files that are included in the entry point, or were included by the entries?

Cheers!

**Comment by kevlened** [comment]
There's both a global and pattern-level ignore that accepts globs.

**Comment by REEMERGEMEDIA** [comment]
@kevlened  I'd like to follow up here on this. I have an /assets and /assets/inline folder. I've tried specifying in both the pattern and global ignores to ignore the inline folder but to no avail. Here's where things currently stand

new CopyWebpackPlugin([{ from: 'assets/' }], { ignore: ['assets/inline/**/*'] })

Thanks in advance

**Comment by evilebottnawi** [comment]
@REEMERGEMEDIA problem still exists?
