### ISSUE TITLE
[Bug] Copy multiple time the same file does one input only

### ISSUE THREAD

**Issue by jdeniau** [webpack-contrib/copy-webpack-plugin#99]
I tried to do something like this:
```js
plugins: [
  new CopyWebpackPlugin([
    {
      from: 'a.js',
      to: 'b.js',
    },
    {
      from: 'a.js',
      to: 'c.js',
    },
  ]),
],
```

When doing that, only one output file is created. 
I had to do this to make it work:
```js
plugins: [
  new CopyWebpackPlugin([
    {
      from: 'a.js',
      to: 'b.js',
    },
  ]),
  new CopyWebpackPlugin([
    {
      from: 'a.js',
      to: 'c.js',
    },
  ]),
],
```

**Comment by jpsear** [comment]
Yup — I have exactly the same problem

**Comment by JeffreyWay** [comment]
Me too. Are we doing something wrong?

**Comment by jpsear** [comment]
That's exactly what I ended up doing. I'm assuming it's wrong!

**Comment by admosity** [comment]
I think i figured it out. Ran into the same issue with having to dupe across. It appears that in watch mode, when a file is encountered once, it is placed into a cache. I had to enable `copyUnmodified` in order to make it work:

```javascript
      new CopyWebpackPlugin([
        // backwards compat
        { from: 'src/assets/images', to: 'css/images' },
        { from: 'src/assets/images', to: 'images' },
        { from: 'src/assets/fonts', to: 'css/fonts' },

        { from: 'src/assets', to: 'assets' },
        { from: 'src/meta'},
      ], {
        copyUnmodified: true
      }),
```

**Comment by evilebottnawi** [comment]
Fixex in https://github.com/webpack-contrib/copy-webpack-plugin/pull/165, please update to latest version. Also feel free to reopen issue if you still have problem.
